SELECT C.[CODE], C.[NAME], C.[SYMBOL] 
FROM [CURRENCIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[IS_ACTIVE] = @PRM_CURRENCY_IS_ACTIVE 
ORDER BY C.[CODE] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 