SELECT AT.[ID], AT.[CODE], AT.[NAME], AT.[INTEREST_RATE] 
FROM [ACCOUNT_TYPES] AT 
WHERE AT.[IsDeleted] = 0 
	AND AT.[IS_ACTIVE] = @PRM_ACCOUNT_TYPE_IS_ACTIVE 
ORDER BY AT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 