//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.CustomerRelationship;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories
{
    public partial class CustomerRelationshipRepository : BaseRepository, ICustomerRelationshipRepository
    {
        public async Task<RepoResponse<int>> RemoveRelationshipAsync(int customerRelationshipId)
        {
            return await ExecuteWithExceptionHandling(CustomerRelationshipCrudSqlBindings.OperationNames.RemoveRelationship, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CustomerRelationship.Command.RemoveRelationship);
                var parameters = new
                {
                    PRM_CUSTOMER_RELATIONSHIP_ID = customerRelationshipId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}