//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.AccountType;
using AccountTypeEntity = QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities.AccountType;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings
{
    public static class AccountTypeMappings
    {
        public static List<AccountTypeDto> ToDto(this IEnumerable<AccountTypeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AccountTypeDto ToDto(this AccountTypeEntity model)
        {
            return new AccountTypeDto
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                InterestRate = model.InterestRate,
                MinimumBalance = model.MinimumBalance,
                IsActive = model.IsActive
            };
        }

        public static AccountTypeEntity ToEntity(this AccountTypeDto model)
        {
            return new AccountTypeEntity
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                InterestRate = model.InterestRate,
                MinimumBalance = model.MinimumBalance,
                IsActive = model.IsActive
            };
        }
    }
}