//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.AccountHolder;
using AccountHolderEntity = QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities.AccountHolder;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings
{
    public static class AccountHolderMappings
    {
        public static List<AccountHolderDto> ToDto(this IEnumerable<AccountHolderEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AccountHolderDto ToDto(this AccountHolderEntity model)
        {
            return new AccountHolderDto
            {
                AccountId = model.AccountId,
                CustomerId = model.CustomerId,
                Role = model.Role
            };
        }

        public static AccountHolderEntity ToEntity(this AccountHolderDto model)
        {
            return new AccountHolderEntity
            {
                AccountId = model.AccountId,
                CustomerId = model.CustomerId,
                Role = model.Role
            };
        }
    }
}