//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.AccountStatement;
using AccountStatementEntity = QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities.AccountStatement;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings
{
    public static class AccountStatementMappings
    {
        public static List<AccountStatementDto> ToDto(this IEnumerable<AccountStatementEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AccountStatementDto ToDto(this AccountStatementEntity model)
        {
            return new AccountStatementDto
            {
                Id = model.Id,
                AccountId = model.AccountId,
                StatementPeriodStart = model.StatementPeriodStart,
                StatementPeriodEnd = model.StatementPeriodEnd,
                GeneratedDate = model.GeneratedDate,
                OpeningBalance = model.OpeningBalance,
                ClosingBalance = model.ClosingBalance,
                StatementUrl = model.StatementUrl,
                Format = model.Format
            };
        }

        public static AccountStatementEntity ToEntity(this AccountStatementDto model)
        {
            return new AccountStatementEntity
            {
                Id = model.Id,
                AccountId = model.AccountId,
                StatementPeriodStart = model.StatementPeriodStart,
                StatementPeriodEnd = model.StatementPeriodEnd,
                GeneratedDate = model.GeneratedDate,
                OpeningBalance = model.OpeningBalance,
                ClosingBalance = model.ClosingBalance,
                StatementUrl = model.StatementUrl,
                Format = model.Format
            };
        }
    }
}