//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.CardType;
using CardTypeEntity = QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities.CardType;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings
{
    public static class CardTypeMappings
    {
        public static List<CardTypeDto> ToDto(this IEnumerable<CardTypeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CardTypeDto ToDto(this CardTypeEntity model)
        {
            return new CardTypeDto
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                Network = model.Network,
                IsActive = model.IsActive
            };
        }

        public static CardTypeEntity ToEntity(this CardTypeDto model)
        {
            return new CardTypeEntity
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                Network = model.Network,
                IsActive = model.IsActive
            };
        }
    }
}