INSERT INTO [dbo].[CONTACT_DETAILS] (
    [CUSTOMER_ID],
    [TYPE],
    [VALUE],
    [IS_VERIFIED]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CONTACT_DETAIL_CUSTOMER_ID,
    @PRM_CONTACT_DETAIL_TYPE,
    @PRM_CONTACT_DETAIL_VALUE,
    @PRM_CONTACT_DETAIL_IS_VERIFIED
    );