SELECT
    [ID],
    [CUSTOMER_ID],
    [TYPE],
    [VALUE],
    [IS_VERIFIED]
FROM [dbo].[CONTACT_DETAILS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;