UPDATE [dbo].[CONTACT_DETAILS]
SET
    [CUSTOMER_ID] = @PRM_CONTACT_DETAIL_CUSTOMER_ID,
    [TYPE] = @PRM_CONTACT_DETAIL_TYPE,
    [VALUE] = @PRM_CONTACT_DETAIL_VALUE,
    [IS_VERIFIED] = @PRM_CONTACT_DETAIL_IS_VERIFIED
WHERE
    [ID] = @PRM_CONTACT_DETAIL_ID
    AND [IsDeleted] = 0;