//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.CustomerType;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories
{
    public partial interface ICustomerTypeRepository : IBaseRepository<CustomerTypeDto>
    {
        Task<RepoResponse<CustomerTypeDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool customerTypeIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByCodeResponseDto>> GetByCodeAsync(string customerTypeCode);
        Task<RepoResponse<int>> DeactivateAsync(int customerTypeId, DeactivateRequestDto updateRequest);
    }
}