//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.Customer;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories
{
    public partial interface ICustomerRepository : IBaseRepository<CustomerDto>
    {
        Task<RepoResponse<CustomerDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByCustomerNumberResponseDto>> GetByCustomerNumberAsync(Guid customerCustomerNumber);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string customerLastName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetActiveCustomersResponseDto>>> GetActiveCustomersAsync(CustomerStatus customerStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetCustomersByTypeResponseDto>>> GetCustomersByTypeAsync(int customersCustomerTypeId, int customerTypesId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecentlyJoinedResponseDto>>> GetRecentlyJoinedAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetActiveCountByTypeAsync(int customersCustomerTypeId, CustomerStatus customersStatus, int customerTypesId);
        Task<RepoResponse<int>> ActivateCustomerAsync(int customerId, ActivateCustomerRequestDto updateRequest);
        Task<RepoResponse<int>> SuspendCustomerAsync(int customerId, SuspendCustomerRequestDto updateRequest);
        Task<RepoResponse<int>> CloseCustomerAsync(int customerId, CloseCustomerRequestDto updateRequest);
    }
}