//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.DocumentType;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories
{
    public partial interface IDocumentTypeRepository : IBaseRepository<DocumentTypeDto>
    {
        Task<RepoResponse<DocumentTypeDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool documentTypeIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByCodeResponseDto>> GetByCodeAsync(string documentTypeCode);
        Task<RepoResponse<int>> DeactivateAsync(int documentTypeId, DeactivateRequestDto updateRequest);
    }
}