//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.ContactDetail;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories;
internal static class ContactDetailCrudSqlBindings
{
    public const string StoreTableName = "CONTACT_DETAILS";
    public const string ParameterNamePrefix = "CONTACT_DETAIL";
    public const string IdParameterName = "PRM_CONTACT_DETAIL_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByCustomerId = "GetByCustomerId";
        public const string GetByPk = "GetByPk";
        public const string GetUnverifiedContacts = "GetUnverifiedContacts";
        public const string Insert = "Insert";
        public const string MarkAsVerified = "MarkAsVerified";
        public const string RemoveContact = "RemoveContact";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CUSTOMER_ID", nameof(ContactDetailDto.CustomerId)),
        ("TYPE", nameof(ContactDetailDto.Type)),
        ("VALUE", nameof(ContactDetailDto.Value)),
        ("IS_VERIFIED", nameof(ContactDetailDto.IsVerified))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CUSTOMER_ID", nameof(ContactDetailDto.CustomerId)),
        ("TYPE", nameof(ContactDetailDto.Type)),
        ("VALUE", nameof(ContactDetailDto.Value)),
        ("IS_VERIFIED", nameof(ContactDetailDto.IsVerified)),
        ("ID", nameof(ContactDetailDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(ContactDetailDto.Id))
    };
}