SELECT TT.[ID], TT.[CODE], TT.[NAME], TT.[DIRECTION] 
FROM [TRANSACTION_TYPES] TT 
WHERE TT.[IsDeleted] = 0 
	AND TT.[IS_ACTIVE] = @PRM_TRANSACTION_TYPE_IS_ACTIVE 
ORDER BY TT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 