//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.PermissionGroup;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories;
internal static class PermissionGroupCrudSqlBindings
{
    public const string StoreTableName = "PermissionGroups";
    public const string ParameterNamePrefix = "PermissionGroup";
    public const string NameParameterName = "PRM_PERMISSION_GROUP_NAME";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("Name", nameof(PermissionGroupDto.Name)),
        ("Description", nameof(PermissionGroupDto.Description))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("Description", nameof(PermissionGroupDto.Description)),
        ("Name", nameof(PermissionGroupDto.Name))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("Name", nameof(PermissionGroupDto.Name))
    };
}