//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.PermissionGroup;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class PermissionGroupRepository : BaseRepository, IPermissionGroupRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public PermissionGroupRepository(ILogger<PermissionGroupRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "PermissionGroup")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<PermissionGroupDto>> InsertAsync(PermissionGroupDto value)
        {
            return await ExecuteWithExceptionHandling(PermissionGroupCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(PermissionGroupCrudSqlBindings.ParameterNamePrefix, value, PermissionGroupCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.PermissionGroup>(sql, p);
                return new RepoResponse<PermissionGroupDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(PermissionGroupDto value)
        {
            return await ExecuteWithExceptionHandling(PermissionGroupCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(PermissionGroupCrudSqlBindings.ParameterNamePrefix, value, PermissionGroupCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(PermissionGroupDto value)
        {
            return await ExecuteWithExceptionHandling(PermissionGroupCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(PermissionGroupCrudSqlBindings.ParameterNamePrefix, value, PermissionGroupCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<PermissionGroupDto>> GetByPkAsync(string name)
        {
            return await ExecuteWithExceptionHandling(PermissionGroupCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(PermissionGroupCrudSqlBindings.NameParameterName, name);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.PermissionGroup>(sql, p);
                return row == null ? CreateNotFoundResponse<PermissionGroupDto>("Not found in PermissionGroup") : new RepoResponse<PermissionGroupDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<PermissionGroupDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(PermissionGroupCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<PermissionGroupDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.PermissionGroup>(sql, p);
                return new RepoResponse<List<PermissionGroupDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(PermissionGroupCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}