//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.ApiMethodAccessGrant;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodAccessGrantRepository : BaseRepository, IApiMethodAccessGrantRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public ApiMethodAccessGrantRepository(ILogger<ApiMethodAccessGrantRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "ApiMethodAccessGrant")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<ApiMethodAccessGrantDto>> InsertAsync(ApiMethodAccessGrantDto value)
        {
            return await ExecuteWithExceptionHandling(ApiMethodAccessGrantCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(ApiMethodAccessGrantCrudSqlBindings.ParameterNamePrefix, value, ApiMethodAccessGrantCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.ApiMethodAccessGrant>(sql, p);
                return new RepoResponse<ApiMethodAccessGrantDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ApiMethodAccessGrantDto value)
        {
            return await ExecuteWithExceptionHandling(ApiMethodAccessGrantCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(ApiMethodAccessGrantCrudSqlBindings.ParameterNamePrefix, value, ApiMethodAccessGrantCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ApiMethodAccessGrantDto value)
        {
            return await ExecuteWithExceptionHandling(ApiMethodAccessGrantCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(ApiMethodAccessGrantCrudSqlBindings.ParameterNamePrefix, value, ApiMethodAccessGrantCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<ApiMethodAccessGrantDto>> GetByPkAsync(string permissionGroupName, string apiMethodDefinitionKey)
        {
            return await ExecuteWithExceptionHandling(ApiMethodAccessGrantCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(ApiMethodAccessGrantCrudSqlBindings.PermissionGroupNameParameterName, permissionGroupName);
                p.Add(ApiMethodAccessGrantCrudSqlBindings.ApiMethodDefinitionKeyParameterName, apiMethodDefinitionKey);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.ApiMethodAccessGrant>(sql, p);
                return row == null ? CreateNotFoundResponse<ApiMethodAccessGrantDto>("Not found in ApiMethodAccessGrant") : new RepoResponse<ApiMethodAccessGrantDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<ApiMethodAccessGrantDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(ApiMethodAccessGrantCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ApiMethodAccessGrantDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.ApiMethodAccessGrant>(sql, p);
                return new RepoResponse<List<ApiMethodAccessGrantDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(ApiMethodAccessGrantCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}