//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanPayment;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories
{
    public partial class LoanPaymentRepository : BaseRepository, ILoanPaymentRepository
    {
        public async Task<RepoResponse<List<GetByLoanIdResponseDto>>> GetByLoanIdAsync(int loanPaymentLoanId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.GetByLoanId, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByLoanIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.LoanPayment.Query.GetByLoanId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_LOAN_PAYMENT_LOAN_ID = loanPaymentLoanId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByLoanIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in LoanPayment");
                }
            });
        }

        public async Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(int loanPaymentLoanId, DateTime loanPaymentPaymentDateFrom, DateTime loanPaymentPaymentDateTo, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.GetByDateRange, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByDateRangeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.LoanPayment.Query.GetByDateRange);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_LOAN_PAYMENT_LOAN_ID = loanPaymentLoanId,
                        PRM_LOAN_PAYMENT_PAYMENT_DATE_From = loanPaymentPaymentDateFrom,
                        PRM_LOAN_PAYMENT_PAYMENT_DATE_To = loanPaymentPaymentDateTo,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByDateRangeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in LoanPayment");
                }
            });
        }

        public async Task<RepoResponse<long>> GetTotalPaymentsForLoanAsync(int loanPaymentLoanId)
        {
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.GetTotalPaymentsForLoan, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanPayment.Query.GetTotalPaymentsForLoan);
                var parameters = new
                {
                    PRM_LOAN_PAYMENT_LOAN_ID = loanPaymentLoanId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result);
            });
        }
    }
}