//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanPayment;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories;
internal static class LoanPaymentCrudSqlBindings
{
    public const string StoreTableName = "LOAN_PAYMENTS";
    public const string ParameterNamePrefix = "LOAN_PAYMENT";
    public const string IdParameterName = "PRM_LOAN_PAYMENT_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByDateRange = "GetByDateRange";
        public const string GetByLoanId = "GetByLoanId";
        public const string GetByPk = "GetByPk";
        public const string GetTotalPaymentsForLoan = "GetTotalPaymentsForLoan";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("LOAN_ID", nameof(LoanPaymentDto.LoanId)),
        ("SCHEDULE_ID", nameof(LoanPaymentDto.ScheduleId)),
        ("PAYMENT_REFERENCE", nameof(LoanPaymentDto.PaymentReference)),
        ("AMOUNT_PAID", nameof(LoanPaymentDto.AmountPaid)),
        ("PAYMENT_DATE", nameof(LoanPaymentDto.PaymentDate)),
        ("PAYMENT_METHOD", nameof(LoanPaymentDto.PaymentMethod))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("LOAN_ID", nameof(LoanPaymentDto.LoanId)),
        ("SCHEDULE_ID", nameof(LoanPaymentDto.ScheduleId)),
        ("PAYMENT_REFERENCE", nameof(LoanPaymentDto.PaymentReference)),
        ("AMOUNT_PAID", nameof(LoanPaymentDto.AmountPaid)),
        ("PAYMENT_DATE", nameof(LoanPaymentDto.PaymentDate)),
        ("PAYMENT_METHOD", nameof(LoanPaymentDto.PaymentMethod)),
        ("ID", nameof(LoanPaymentDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(LoanPaymentDto.Id))
    };
}