//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanPayment;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories
{
    public partial class LoanPaymentRepository : BaseRepository, ILoanPaymentRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public LoanPaymentRepository(ILogger<LoanPaymentRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "LoanPayment")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<LoanPaymentDto>> InsertAsync(LoanPaymentDto value)
        {
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanPayment.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(LoanPaymentCrudSqlBindings.ParameterNamePrefix, value, LoanPaymentCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.LoanPayment>(sql, p);
                return new RepoResponse<LoanPaymentDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(LoanPaymentDto value)
        {
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanPayment.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(LoanPaymentCrudSqlBindings.ParameterNamePrefix, value, LoanPaymentCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(LoanPaymentDto value)
        {
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanPayment.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(LoanPaymentCrudSqlBindings.ParameterNamePrefix, value, LoanPaymentCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<LoanPaymentDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanPayment.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(LoanPaymentCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.LoanPayment>(sql, p);
                return row == null ? CreateNotFoundResponse<LoanPaymentDto>("Not found in LoanPayment") : new RepoResponse<LoanPaymentDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<LoanPaymentDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<LoanPaymentDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.LoanPayment.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.LoanPayment>(sql, p);
                return new RepoResponse<List<LoanPaymentDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(LoanPaymentCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanPayment.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}