INSERT INTO [dbo].[ACCOUNTS] (
    [ACCOUNT_NUMBER],
    [CUSTOMER_ID],
    [ACCOUNT_TYPE_ID],
    [CURRENCY_ID],
    [BALANCE],
    [STATUS],
    [OPENED_DATE],
    [CLOSED_DATE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_ACCOUNT_ACCOUNT_NUMBER,
    @PRM_ACCOUNT_CUSTOMER_ID,
    @PRM_ACCOUNT_ACCOUNT_TYPE_ID,
    @PRM_ACCOUNT_CURRENCY_ID,
    @PRM_ACCOUNT_BALANCE,
    @PRM_ACCOUNT_STATUS,
    @PRM_ACCOUNT_OPENED_DATE,
    @PRM_ACCOUNT_CLOSED_DATE,
    @PRM_ACCOUNT_IS_ACTIVE
    );