SELECT
    [ID],
    [ACCOUNT_NUMBER],
    [CUSTOMER_ID],
    [ACCOUNT_TYPE_ID],
    [CURRENCY_ID],
    [BALANCE],
    [STATUS],
    [OPENED_DATE],
    [CLOSED_DATE],
    [IS_ACTIVE]
FROM [dbo].[ACCOUNTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;