UPDATE [dbo].[ACCOUNTS]
SET
    [ACCOUNT_NUMBER] = @PRM_ACCOUNT_ACCOUNT_NUMBER,
    [CUSTOMER_ID] = @PRM_ACCOUNT_CUSTOMER_ID,
    [ACCOUNT_TYPE_ID] = @PRM_ACCOUNT_ACCOUNT_TYPE_ID,
    [CURRENCY_ID] = @PRM_ACCOUNT_CURRENCY_ID,
    [BALANCE] = @PRM_ACCOUNT_BALANCE,
    [STATUS] = @PRM_ACCOUNT_STATUS,
    [OPENED_DATE] = @PRM_ACCOUNT_OPENED_DATE,
    [CLOSED_DATE] = @PRM_ACCOUNT_CLOSED_DATE,
    [IS_ACTIVE] = @PRM_ACCOUNT_IS_ACTIVE
WHERE
    [ID] = @PRM_ACCOUNT_ID
    AND [IsDeleted] = 0;