UPDATE [dbo].[ACCOUNT_STATEMENTS]
SET
    [ACCOUNT_ID] = @PRM_ACCOUNT_STATEMENT_ACCOUNT_ID,
    [STATEMENT_PERIOD_START] = @PRM_ACCOUNT_STATEMENT_STATEMENT_PERIOD_START,
    [STATEMENT_PERIOD_END] = @PRM_ACCOUNT_STATEMENT_STATEMENT_PERIOD_END,
    [GENERATED_DATE] = @PRM_ACCOUNT_STATEMENT_GENERATED_DATE,
    [OPENING_BALANCE] = @PRM_ACCOUNT_STATEMENT_OPENING_BALANCE,
    [CLOSING_BALANCE] = @PRM_ACCOUNT_STATEMENT_CLOSING_BALANCE,
    [STATEMENT_URL] = @PRM_ACCOUNT_STATEMENT_STATEMENT_URL,
    [FORMAT] = @PRM_ACCOUNT_STATEMENT_FORMAT
WHERE
    [ID] = @PRM_ACCOUNT_STATEMENT_ID
    AND [IsDeleted] = 0;