SELECT
    [ID],
    [ACCOUNT_ID],
    [STATEMENT_PERIOD_START],
    [STATEMENT_PERIOD_END],
    [GENERATED_DATE],
    [OPENING_BALANCE],
    [CLOSING_BALANCE],
    [STATEMENT_URL],
    [FORMAT]
FROM [dbo].[ACCOUNT_STATEMENTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;