INSERT INTO [dbo].[ACCOUNT_STATEMENTS] (
    [ACCOUNT_ID],
    [STATEMENT_PERIOD_START],
    [STATEMENT_PERIOD_END],
    [GENERATED_DATE],
    [OPENING_BALANCE],
    [CLOSING_BALANCE],
    [STATEMENT_URL],
    [FORMAT]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_ACCOUNT_STATEMENT_ACCOUNT_ID,
    @PRM_ACCOUNT_STATEMENT_STATEMENT_PERIOD_START,
    @PRM_ACCOUNT_STATEMENT_STATEMENT_PERIOD_END,
    @PRM_ACCOUNT_STATEMENT_GENERATED_DATE,
    @PRM_ACCOUNT_STATEMENT_OPENING_BALANCE,
    @PRM_ACCOUNT_STATEMENT_CLOSING_BALANCE,
    @PRM_ACCOUNT_STATEMENT_STATEMENT_URL,
    @PRM_ACCOUNT_STATEMENT_FORMAT
    );