SELECT
    [ID],
    [ACCOUNT_ID],
    [STATEMENT_PERIOD_START],
    [STATEMENT_PERIOD_END],
    [GENERATED_DATE],
    [OPENING_BALANCE],
    [CLOSING_BALANCE],
    [STATEMENT_URL],
    [FORMAT]
FROM [dbo].[ACCOUNT_STATEMENTS]
WHERE
    [ID] = @PRM_ACCOUNT_STATEMENT_ID
    AND [IsDeleted] = 0;