IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COLLATERALS_LOAN_APPLICATIONS_LOAN_APPLICATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.COLLATERALS'))
BEGIN
    ALTER TABLE [dbo].[COLLATERALS] ADD CONSTRAINT [FK_COLLATERALS_LOAN_APPLICATIONS_LOAN_APPLICATION_ID] FOREIGN KEY ([LOAN_APPLICATION_ID]) REFERENCES [dbo].[LOAN_APPLICATIONS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COLLATERALS_COLLATERAL_TYPES_COLLATERAL_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.COLLATERALS'))
BEGIN
    ALTER TABLE [dbo].[COLLATERALS] ADD CONSTRAINT [FK_COLLATERALS_COLLATERAL_TYPES_COLLATERAL_TYPE_ID] FOREIGN KEY ([COLLATERAL_TYPE_ID]) REFERENCES [dbo].[COLLATERAL_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOANS_LOAN_APPLICATIONS_APPLICATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOANS'))
BEGIN
    ALTER TABLE [dbo].[LOANS] ADD CONSTRAINT [FK_LOANS_LOAN_APPLICATIONS_APPLICATION_ID] FOREIGN KEY ([APPLICATION_ID]) REFERENCES [dbo].[LOAN_APPLICATIONS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOAN_APPLICATIONS_LOAN_PRODUCTS_LOAN_PRODUCT_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOAN_APPLICATIONS'))
BEGIN
    ALTER TABLE [dbo].[LOAN_APPLICATIONS] ADD CONSTRAINT [FK_LOAN_APPLICATIONS_LOAN_PRODUCTS_LOAN_PRODUCT_ID] FOREIGN KEY ([LOAN_PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOAN_PAYMENTS_LOANS_LOAN_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOAN_PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[LOAN_PAYMENTS] ADD CONSTRAINT [FK_LOAN_PAYMENTS_LOANS_LOAN_ID] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOAN_PAYMENTS_REPAYMENT_SCHEDULES_SCHEDULE_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOAN_PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[LOAN_PAYMENTS] ADD CONSTRAINT [FK_LOAN_PAYMENTS_REPAYMENT_SCHEDULES_SCHEDULE_ID] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[REPAYMENT_SCHEDULES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_REPAYMENT_SCHEDULES_LOANS_LOAN_ID' AND parent_object_id = OBJECT_ID(N'dbo.REPAYMENT_SCHEDULES'))
BEGIN
    ALTER TABLE [dbo].[REPAYMENT_SCHEDULES] ADD CONSTRAINT [FK_REPAYMENT_SCHEDULES_LOANS_LOAN_ID] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([ID]);
END