IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COLLATERALS_LOAN_APPLICATIONS_LOAN_APPLICATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.COLLATERALS'))
BEGIN
    ALTER TABLE [dbo].[COLLATERALS] ADD CONSTRAINT [FK_COLLATERALS_LOAN_APPLICATIONS_LOAN_APPLICATION_ID] FOREIGN KEY ([LOAN_APPLICATION_ID]) REFERENCES [dbo].[LOAN_APPLICATIONS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COLLATERALS_COLLATERAL_TYPES_COLLATERAL_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.COLLATERALS'))
BEGIN
    ALTER TABLE [dbo].[COLLATERALS] ADD CONSTRAINT [FK_COLLATERALS_COLLATERAL_TYPES_COLLATERAL_TYPE_ID] FOREIGN KEY ([COLLATERAL_TYPE_ID]) REFERENCES [dbo].[COLLATERAL_TYPES] ([ID]);
END