IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_REPAYMENT_SCHEDULES_LOANS_LOAN_ID' AND parent_object_id = OBJECT_ID(N'dbo.REPAYMENT_SCHEDULES'))
BEGIN
    ALTER TABLE [dbo].[REPAYMENT_SCHEDULES] ADD CONSTRAINT [FK_REPAYMENT_SCHEDULES_LOANS_LOAN_ID] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([ID]);
END