IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOAN_PAYMENTS_LOANS_LOAN_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOAN_PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[LOAN_PAYMENTS] ADD CONSTRAINT [FK_LOAN_PAYMENTS_LOANS_LOAN_ID] FOREIGN KEY ([LOAN_ID]) REFERENCES [dbo].[LOANS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOAN_PAYMENTS_REPAYMENT_SCHEDULES_SCHEDULE_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOAN_PAYMENTS'))
BEGIN
    ALTER TABLE [dbo].[LOAN_PAYMENTS] ADD CONSTRAINT [FK_LOAN_PAYMENTS_REPAYMENT_SCHEDULES_SCHEDULE_ID] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[REPAYMENT_SCHEDULES] ([ID]);
END