IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOAN_APPLICATIONS_LOAN_PRODUCTS_LOAN_PRODUCT_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOAN_APPLICATIONS'))
BEGIN
    ALTER TABLE [dbo].[LOAN_APPLICATIONS] ADD CONSTRAINT [FK_LOAN_APPLICATIONS_LOAN_PRODUCTS_LOAN_PRODUCT_ID] FOREIGN KEY ([LOAN_PRODUCT_ID]) REFERENCES [dbo].[LOAN_PRODUCTS] ([ID]);
END