IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_LOANS_LOAN_APPLICATIONS_APPLICATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.LOANS'))
BEGIN
    ALTER TABLE [dbo].[LOANS] ADD CONSTRAINT [FK_LOANS_LOAN_APPLICATIONS_APPLICATION_ID] FOREIGN KEY ([APPLICATION_ID]) REFERENCES [dbo].[LOAN_APPLICATIONS] ([ID]);
END