UPDATE [dbo].[DOCUMENT_TYPES]
SET
    [CODE] = @PRM_DOCUMENT_TYPE_CODE,
    [NAME] = @PRM_DOCUMENT_TYPE_NAME,
    [IS_ACTIVE] = @PRM_DOCUMENT_TYPE_IS_ACTIVE
WHERE
    [ID] = @PRM_DOCUMENT_TYPE_ID
    AND [IsDeleted] = 0;