INSERT INTO [dbo].[DOCUMENT_TYPES] (
    [CODE],
    [NAME],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_DOCUMENT_TYPE_CODE,
    @PRM_DOCUMENT_TYPE_NAME,
    @PRM_DOCUMENT_TYPE_IS_ACTIVE
    );