//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.AspNetUser;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class AspNetUserRepository : BaseRepository, IAspNetUserRepository
    {
        public async Task<RepoResponse<GetUserResponseDto>> GetUserAsync(string? aspNetUserEmail)
        {
            return await ExecuteWithExceptionHandling(AspNetUserCrudSqlBindings.OperationNames.GetUser, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetUser.Query.GetUser);
                var parameters = new
                {
                    PRM_AspNetUser_Email = aspNetUserEmail
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetUserResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in AspNetUser");
            });
        }

        public async Task<RepoResponse<List<IdentityUserByIdResponseDto>>> IdentityUserByIdAsync(string aspNetUserId)
        {
            return await ExecuteWithExceptionHandling(AspNetUserCrudSqlBindings.OperationNames.IdentityUserById, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetUser.Query.IdentityUserById);
                var parameters = new
                {
                    PRM_AspNetUser_Id = aspNetUserId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<IdentityUserByIdResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in AspNetUser");
            });
        }

        public async Task<RepoResponse<List<IdentityUserByNormalizedEmailResponseDto>>> IdentityUserByNormalizedEmailAsync(string? aspNetUserNormalizedEmail)
        {
            return await ExecuteWithExceptionHandling(AspNetUserCrudSqlBindings.OperationNames.IdentityUserByNormalizedEmail, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetUser.Query.IdentityUserByNormalizedEmail);
                var parameters = new
                {
                    PRM_AspNetUser_NormalizedEmail = aspNetUserNormalizedEmail
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<IdentityUserByNormalizedEmailResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in AspNetUser");
            });
        }

        public async Task<RepoResponse<List<IdentityUserByNormalizedUsernameResponseDto>>> IdentityUserByNormalizedUsernameAsync(string? aspNetUserNormalizedUserName)
        {
            return await ExecuteWithExceptionHandling(AspNetUserCrudSqlBindings.OperationNames.IdentityUserByNormalizedUsername, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetUser.Query.IdentityUserByNormalizedUsername);
                var parameters = new
                {
                    PRM_AspNetUser_NormalizedUserName = aspNetUserNormalizedUserName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<IdentityUserByNormalizedUsernameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in AspNetUser");
            });
        }
    }
}