UPDATE [dbo].[PortalPageDefinitions]
SET
    [ModuleName] = @PRM_PORTAL_PAGE_DEFINITION_MODULE_NAME,
    [ModelName] = @PRM_PORTAL_PAGE_DEFINITION_MODEL_NAME,
    [PageAction] = @PRM_PORTAL_PAGE_DEFINITION_PAGE_ACTION,
    [PagePath] = @PRM_PORTAL_PAGE_DEFINITION_PAGE_PATH
WHERE
    [Key] = @PRM_PORTAL_PAGE_DEFINITION_KEY;