//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.Transaction;
using TransactionEntity = QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities.Transaction;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Mappings
{
    public static class TransactionMappings
    {
        public static List<TransactionDto> ToDto(this IEnumerable<TransactionEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TransactionDto ToDto(this TransactionEntity model)
        {
            return new TransactionDto
            {
                Id = model.Id,
                TransactionReference = model.TransactionReference,
                SourceAccountId = model.SourceAccountId,
                DestinationAccountId = model.DestinationAccountId,
                TransactionTypeId = model.TransactionTypeId,
                TransactionChannelId = model.TransactionChannelId,
                Amount = model.Amount,
                CurrencyCode = model.CurrencyCode,
                Description = model.Description,
                Status = model.Status,
                TransactionDate = model.TransactionDate,
                CompletedDate = model.CompletedDate
            };
        }

        public static TransactionEntity ToEntity(this TransactionDto model)
        {
            return new TransactionEntity
            {
                Id = model.Id,
                TransactionReference = model.TransactionReference,
                SourceAccountId = model.SourceAccountId,
                DestinationAccountId = model.DestinationAccountId,
                TransactionTypeId = model.TransactionTypeId,
                TransactionChannelId = model.TransactionChannelId,
                Amount = model.Amount,
                CurrencyCode = model.CurrencyCode,
                Description = model.Description,
                Status = model.Status,
                TransactionDate = model.TransactionDate,
                CompletedDate = model.CompletedDate
            };
        }
    }
}