//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.TransactionFee;
using TransactionFeeEntity = QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities.TransactionFee;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Mappings
{
    public static class TransactionFeeMappings
    {
        public static List<TransactionFeeDto> ToDto(this IEnumerable<TransactionFeeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TransactionFeeDto ToDto(this TransactionFeeEntity model)
        {
            return new TransactionFeeDto
            {
                Id = model.Id,
                TransactionId = model.TransactionId,
                FeeTypeId = model.FeeTypeId,
                FeeAmount = model.FeeAmount,
                AppliedDate = model.AppliedDate
            };
        }

        public static TransactionFeeEntity ToEntity(this TransactionFeeDto model)
        {
            return new TransactionFeeEntity
            {
                Id = model.Id,
                TransactionId = model.TransactionId,
                FeeTypeId = model.FeeTypeId,
                FeeAmount = model.FeeAmount,
                AppliedDate = model.AppliedDate
            };
        }
    }
}