//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.TransactionChannel;
using TransactionChannelEntity = QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities.TransactionChannel;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Mappings
{
    public static class TransactionChannelMappings
    {
        public static List<TransactionChannelDto> ToDto(this IEnumerable<TransactionChannelEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TransactionChannelDto ToDto(this TransactionChannelEntity model)
        {
            return new TransactionChannelDto
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                IsActive = model.IsActive
            };
        }

        public static TransactionChannelEntity ToEntity(this TransactionChannelDto model)
        {
            return new TransactionChannelEntity
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                IsActive = model.IsActive
            };
        }
    }
}