SELECT TOP 1 A.[ID], A.[ADDRESS_LINE_1], A.[CITY], A.[STATE], A.[POSTAL_CODE], A.[TYPE] 
FROM [ADDRESSES] A 
WHERE A.[IsDeleted] = 0 
	AND A.[CUSTOMER_ID] = @PRM_ADDRESS_CUSTOMER_ID 
	AND A.[IS_PRIMARY] = @PRM_ADDRESS_IS_PRIMARY 
ORDER BY A.[ID] 