SELECT A.[ID], A.[ADDRESS_LINE_1], A.[CITY], A.[STATE], A.[POSTAL_CODE], A.[TYPE], A.[IS_PRIMARY] 
FROM [ADDRESSES] A 
WHERE A.[IsDeleted] = 0 
	AND A.[CUSTOMER_ID] = @PRM_ADDRESS_CUSTOMER_ID 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 