UPDATE [dbo].[TRANSACTION_FEES]
SET
    [TRANSACTION_ID] = @PRM_TRANSACTION_FEE_TRANSACTION_ID,
    [FEE_TYPE_ID] = @PRM_TRANSACTION_FEE_FEE_TYPE_ID,
    [FEE_AMOUNT] = @PRM_TRANSACTION_FEE_FEE_AMOUNT,
    [APPLIED_DATE] = @PRM_TRANSACTION_FEE_APPLIED_DATE
WHERE
    [ID] = @PRM_TRANSACTION_FEE_ID
    AND [IsDeleted] = 0;