INSERT INTO [dbo].[TRANSACTION_FEES] (
    [TRANSACTION_ID],
    [FEE_TYPE_ID],
    [FEE_AMOUNT],
    [APPLIED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TRANSACTION_FEE_TRANSACTION_ID,
    @PRM_TRANSACTION_FEE_FEE_TYPE_ID,
    @PRM_TRANSACTION_FEE_FEE_AMOUNT,
    @PRM_TRANSACTION_FEE_APPLIED_DATE
    );