SELECT
    [ID],
    [TRANSACTION_ID],
    [FEE_TYPE_ID],
    [FEE_AMOUNT],
    [APPLIED_DATE]
FROM [dbo].[TRANSACTION_FEES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;