SELECT FT.[ID], FT.[CODE], FT.[NAME], FT.[FIXED_AMOUNT], FT.[PERCENTAGE_RATE] 
FROM [FEE_TYPES] FT 
WHERE FT.[IsDeleted] = 0 
	AND FT.[IS_ACTIVE] = @PRM_FEE_TYPE_IS_ACTIVE 
ORDER BY FT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 