//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanApplication
{
    public record LoanApplicationDto
    {
        public int Id { get; init; }
        public Guid ApplicationNumber { get; init; }
        public int CustomerId { get; init; }
        public int LoanProductId { get; init; }
        public decimal RequestedAmount { get; init; }
        public int RequestedTermMonths { get; init; }
        public string Purpose { get; init; }
        public LoanApplicationStatus Status { get; init; }
        public DateTime SubmittedDate { get; init; }
        public DateTime DecisionDate { get; init; }
    }
}