//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.AccountType;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories
{
    public partial class AccountTypeRepository : BaseRepository, IAccountTypeRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public AccountTypeRepository(ILogger<AccountTypeRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "AccountType")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<AccountTypeDto>> InsertAsync(AccountTypeDto value)
        {
            return await ExecuteWithExceptionHandling(AccountTypeCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountType.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(AccountTypeCrudSqlBindings.ParameterNamePrefix, value, AccountTypeCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.AccountType>(sql, p);
                return new RepoResponse<AccountTypeDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(AccountTypeDto value)
        {
            return await ExecuteWithExceptionHandling(AccountTypeCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountType.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(AccountTypeCrudSqlBindings.ParameterNamePrefix, value, AccountTypeCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(AccountTypeDto value)
        {
            return await ExecuteWithExceptionHandling(AccountTypeCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountType.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(AccountTypeCrudSqlBindings.ParameterNamePrefix, value, AccountTypeCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<AccountTypeDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(AccountTypeCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountType.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(AccountTypeCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.AccountType>(sql, p);
                return row == null ? CreateNotFoundResponse<AccountTypeDto>("Not found in AccountType") : new RepoResponse<AccountTypeDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<AccountTypeDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(AccountTypeCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<AccountTypeDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.AccountType.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.AccountType>(sql, p);
                return new RepoResponse<List<AccountTypeDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(AccountTypeCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountType.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}