UPDATE [dbo].[LOAN_APPLICATIONS]
SET
    [APPLICATION_NUMBER] = @PRM_LOAN_APPLICATION_APPLICATION_NUMBER,
    [CUSTOMER_ID] = @PRM_LOAN_APPLICATION_CUSTOMER_ID,
    [LOAN_PRODUCT_ID] = @PRM_LOAN_APPLICATION_LOAN_PRODUCT_ID,
    [REQUESTED_AMOUNT] = @PRM_LOAN_APPLICATION_REQUESTED_AMOUNT,
    [REQUESTED_TERM_MONTHS] = @PRM_LOAN_APPLICATION_REQUESTED_TERM_MONTHS,
    [PURPOSE] = @PRM_LOAN_APPLICATION_PURPOSE,
    [STATUS] = @PRM_LOAN_APPLICATION_STATUS,
    [SUBMITTED_DATE] = @PRM_LOAN_APPLICATION_SUBMITTED_DATE,
    [DECISION_DATE] = @PRM_LOAN_APPLICATION_DECISION_DATE
WHERE
    [ID] = @PRM_LOAN_APPLICATION_ID
    AND [IsDeleted] = 0;