SELECT
    [ID],
    [APPLICATION_NUMBER],
    [CUSTOMER_ID],
    [LOAN_PRODUCT_ID],
    [REQUESTED_AMOUNT],
    [REQUESTED_TERM_MONTHS],
    [PURPOSE],
    [STATUS],
    [SUBMITTED_DATE],
    [DECISION_DATE]
FROM [dbo].[LOAN_APPLICATIONS]
WHERE
    [ID] = @PRM_LOAN_APPLICATION_ID
    AND [IsDeleted] = 0;