SELECT
    [ID],
    [APPLICATION_NUMBER],
    [CUSTOMER_ID],
    [LOAN_PRODUCT_ID],
    [REQUESTED_AMOUNT],
    [REQUESTED_TERM_MONTHS],
    [PURPOSE],
    [STATUS],
    [SUBMITTED_DATE],
    [DECISION_DATE]
FROM [dbo].[LOAN_APPLICATIONS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;