INSERT INTO [dbo].[LOAN_APPLICATIONS] (
    [APPLICATION_NUMBER],
    [CUSTOMER_ID],
    [LOAN_PRODUCT_ID],
    [REQUESTED_AMOUNT],
    [REQUESTED_TERM_MONTHS],
    [PURPOSE],
    [STATUS],
    [SUBMITTED_DATE],
    [DECISION_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_LOAN_APPLICATION_APPLICATION_NUMBER,
    @PRM_LOAN_APPLICATION_CUSTOMER_ID,
    @PRM_LOAN_APPLICATION_LOAN_PRODUCT_ID,
    @PRM_LOAN_APPLICATION_REQUESTED_AMOUNT,
    @PRM_LOAN_APPLICATION_REQUESTED_TERM_MONTHS,
    @PRM_LOAN_APPLICATION_PURPOSE,
    @PRM_LOAN_APPLICATION_STATUS,
    @PRM_LOAN_APPLICATION_SUBMITTED_DATE,
    @PRM_LOAN_APPLICATION_DECISION_DATE
    );