//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.AccountHolder;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories
{
    public partial class AccountHolderRepository : BaseRepository, IAccountHolderRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public AccountHolderRepository(ILogger<AccountHolderRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "AccountHolder")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<AccountHolderDto>> InsertAsync(AccountHolderDto value)
        {
            return await ExecuteWithExceptionHandling(AccountHolderCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountHolder.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(AccountHolderCrudSqlBindings.ParameterNamePrefix, value, AccountHolderCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.AccountHolder>(sql, p);
                return new RepoResponse<AccountHolderDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(AccountHolderDto value)
        {
            return await ExecuteWithExceptionHandling(AccountHolderCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountHolder.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(AccountHolderCrudSqlBindings.ParameterNamePrefix, value, AccountHolderCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(AccountHolderDto value)
        {
            return await ExecuteWithExceptionHandling(AccountHolderCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountHolder.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(AccountHolderCrudSqlBindings.ParameterNamePrefix, value, AccountHolderCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<AccountHolderDto>> GetByPkAsync(int accountId, int customerId)
        {
            return await ExecuteWithExceptionHandling(AccountHolderCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountHolder.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(AccountHolderCrudSqlBindings.AccountIdParameterName, accountId);
                p.Add(AccountHolderCrudSqlBindings.CustomerIdParameterName, customerId);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.AccountHolder>(sql, p);
                return row == null ? CreateNotFoundResponse<AccountHolderDto>("Not found in AccountHolder") : new RepoResponse<AccountHolderDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<AccountHolderDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(AccountHolderCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<AccountHolderDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.AccountHolder.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.AccountHolder>(sql, p);
                return new RepoResponse<List<AccountHolderDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(AccountHolderCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AccountHolder.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}