//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.AccountHolder;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories;
internal static class AccountHolderCrudSqlBindings
{
    public const string StoreTableName = "ACCOUNT_HOLDERS";
    public const string ParameterNamePrefix = "ACCOUNT_HOLDER";
    public const string AccountIdParameterName = "PRM_ACCOUNT_HOLDER_ACCOUNT_ID";
    public const string CustomerIdParameterName = "PRM_ACCOUNT_HOLDER_CUSTOMER_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetAccountsByHolderId = "GetAccountsByHolderId";
        public const string GetByPk = "GetByPk";
        public const string GetHoldersByAccountId = "GetHoldersByAccountId";
        public const string Insert = "Insert";
        public const string RemoveHolder = "RemoveHolder";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("ACCOUNT_ID", nameof(AccountHolderDto.AccountId)),
        ("CUSTOMER_ID", nameof(AccountHolderDto.CustomerId)),
        ("ROLE", nameof(AccountHolderDto.Role))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("ROLE", nameof(AccountHolderDto.Role)),
        ("ACCOUNT_ID", nameof(AccountHolderDto.AccountId)),
        ("CUSTOMER_ID", nameof(AccountHolderDto.CustomerId))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ACCOUNT_ID", nameof(AccountHolderDto.AccountId)),
        ("CUSTOMER_ID", nameof(AccountHolderDto.CustomerId))
    };
}