INSERT INTO [dbo].[ACCOUNT_HOLDERS] (
    [ACCOUNT_ID],
    [CUSTOMER_ID],
    [ROLE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_ACCOUNT_HOLDER_ACCOUNT_ID,
    @PRM_ACCOUNT_HOLDER_CUSTOMER_ID,
    @PRM_ACCOUNT_HOLDER_ROLE
    );