SELECT
    [ACCOUNT_ID],
    [CUSTOMER_ID],
    [ROLE]
FROM [dbo].[ACCOUNT_HOLDERS]
WHERE EXISTS (
    SELECT 1
    FROM [dbo].[ACCOUNTS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[ACCOUNT_HOLDERS].[ACCOUNT_ID]
      AND qc_sd_p.[IsDeleted] = 0)
ORDER BY
    [ACCOUNT_ID],
    [CUSTOMER_ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;