INSERT INTO [dbo].[CARD_TYPES] (
    [CODE],
    [NAME],
    [NETWORK],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CARD_TYPE_CODE,
    @PRM_CARD_TYPE_NAME,
    @PRM_CARD_TYPE_NETWORK,
    @PRM_CARD_TYPE_IS_ACTIVE
    );