UPDATE [dbo].[CARD_TYPES]
SET
    [CODE] = @PRM_CARD_TYPE_CODE,
    [NAME] = @PRM_CARD_TYPE_NAME,
    [NETWORK] = @PRM_CARD_TYPE_NETWORK,
    [IS_ACTIVE] = @PRM_CARD_TYPE_IS_ACTIVE
WHERE
    [ID] = @PRM_CARD_TYPE_ID
    AND [IsDeleted] = 0;