INSERT INTO [dbo].[BENEFICIARIES] (
    [CUSTOMER_ID],
    [NICKNAME],
    [BENEFICIARY_ACCOUNT_NUMBER],
    [BENEFICIARY_NAME],
    [BANK_NAME],
    [BANK_CODE],
    [TYPE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_BENEFICIARY_CUSTOMER_ID,
    @PRM_BENEFICIARY_NICKNAME,
    @PRM_BENEFICIARY_BENEFICIARY_ACCOUNT_NUMBER,
    @PRM_BENEFICIARY_BENEFICIARY_NAME,
    @PRM_BENEFICIARY_BANK_NAME,
    @PRM_BENEFICIARY_BANK_CODE,
    @PRM_BENEFICIARY_TYPE,
    @PRM_BENEFICIARY_IS_ACTIVE
    );