SELECT
    [ID],
    [CUSTOMER_ID],
    [NICKNAME],
    [BENEFICIARY_ACCOUNT_NUMBER],
    [BENEFICIARY_NAME],
    [BANK_NAME],
    [BANK_CODE],
    [TYPE],
    [IS_ACTIVE]
FROM [dbo].[BENEFICIARIES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;