UPDATE [dbo].[BENEFICIARIES]
SET
    [CUSTOMER_ID] = @PRM_BENEFICIARY_CUSTOMER_ID,
    [NICKNAME] = @PRM_BENEFICIARY_NICKNAME,
    [BENEFICIARY_ACCOUNT_NUMBER] = @PRM_BENEFICIARY_BENEFICIARY_ACCOUNT_NUMBER,
    [BENEFICIARY_NAME] = @PRM_BENEFICIARY_BENEFICIARY_NAME,
    [BANK_NAME] = @PRM_BENEFICIARY_BANK_NAME,
    [BANK_CODE] = @PRM_BENEFICIARY_BANK_CODE,
    [TYPE] = @PRM_BENEFICIARY_TYPE,
    [IS_ACTIVE] = @PRM_BENEFICIARY_IS_ACTIVE
WHERE
    [ID] = @PRM_BENEFICIARY_ID
    AND [IsDeleted] = 0;