INSERT INTO [dbo].[ACCOUNT_TYPES] (
    [CODE],
    [NAME],
    [INTEREST_RATE],
    [MINIMUM_BALANCE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_ACCOUNT_TYPE_CODE,
    @PRM_ACCOUNT_TYPE_NAME,
    @PRM_ACCOUNT_TYPE_INTEREST_RATE,
    @PRM_ACCOUNT_TYPE_MINIMUM_BALANCE,
    @PRM_ACCOUNT_TYPE_IS_ACTIVE
    );