UPDATE [dbo].[ACCOUNT_TYPES]
SET
    [CODE] = @PRM_ACCOUNT_TYPE_CODE,
    [NAME] = @PRM_ACCOUNT_TYPE_NAME,
    [INTEREST_RATE] = @PRM_ACCOUNT_TYPE_INTEREST_RATE,
    [MINIMUM_BALANCE] = @PRM_ACCOUNT_TYPE_MINIMUM_BALANCE,
    [IS_ACTIVE] = @PRM_ACCOUNT_TYPE_IS_ACTIVE
WHERE
    [ID] = @PRM_ACCOUNT_TYPE_ID
    AND [IsDeleted] = 0;