//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.PendingTransfer;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Repositories;
internal static class PendingTransferCrudSqlBindings
{
    public const string StoreTableName = "PENDING_TRANSFERS";
    public const string ParameterNamePrefix = "PENDING_TRANSFER";
    public const string IdParameterName = "PRM_PENDING_TRANSFER_ID";
    public static class OperationNames
    {
        public const string ApproveTransfer = "ApproveTransfer";
        public const string CancelScheduledTransfer = "CancelScheduledTransfer";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string GetBySourceAccount = "GetBySourceAccount";
        public const string GetPendingApproval = "GetPendingApproval";
        public const string GetScheduledTransfers = "GetScheduledTransfers";
        public const string Insert = "Insert";
        public const string RejectTransfer = "RejectTransfer";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("TRANSFER_REFERENCE", nameof(PendingTransferDto.TransferReference)),
        ("SOURCE_ACCOUNT_ID", nameof(PendingTransferDto.SourceAccountId)),
        ("BENEFICIARY_ID", nameof(PendingTransferDto.BeneficiaryId)),
        ("AMOUNT", nameof(PendingTransferDto.Amount)),
        ("SCHEDULED_DATE", nameof(PendingTransferDto.ScheduledDate)),
        ("STATUS", nameof(PendingTransferDto.Status)),
        ("CREATED_DATE", nameof(PendingTransferDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("TRANSFER_REFERENCE", nameof(PendingTransferDto.TransferReference)),
        ("SOURCE_ACCOUNT_ID", nameof(PendingTransferDto.SourceAccountId)),
        ("BENEFICIARY_ID", nameof(PendingTransferDto.BeneficiaryId)),
        ("AMOUNT", nameof(PendingTransferDto.Amount)),
        ("SCHEDULED_DATE", nameof(PendingTransferDto.ScheduledDate)),
        ("STATUS", nameof(PendingTransferDto.Status)),
        ("CREATED_DATE", nameof(PendingTransferDto.CreatedDate)),
        ("ID", nameof(PendingTransferDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(PendingTransferDto.Id))
    };
}