SELECT CD.[ID], CD.[CUSTOMER_ID], CD.[TYPE], CD.[VALUE] 
FROM [CONTACT_DETAILS] CD 
WHERE CD.[IsDeleted] = 0 
	AND CD.[IS_VERIFIED] = @PRM_CONTACT_DETAIL_IS_VERIFIED 
ORDER BY CD.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 