SELECT CD.[ID], CD.[TYPE], CD.[VALUE], CD.[IS_VERIFIED] 
FROM [CONTACT_DETAILS] CD 
WHERE CD.[IsDeleted] = 0 
	AND CD.[CUSTOMER_ID] = @PRM_CONTACT_DETAIL_CUSTOMER_ID 
ORDER BY CD.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 