SELECT
    [ID],
    [CUSTOMER_NUMBER],
    [FIRST_NAME],
    [LAST_NAME],
    [DATE_OF_BIRTH],
    [CUSTOMER_TYPE_ID],
    [STATUS],
    [CREATED_DATE],
    [IS_ACTIVE]
FROM [dbo].[CUSTOMERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;