UPDATE [dbo].[CUSTOMERS]
SET
    [CUSTOMER_NUMBER] = @PRM_CUSTOMER_CUSTOMER_NUMBER,
    [FIRST_NAME] = @PRM_CUSTOMER_FIRST_NAME,
    [LAST_NAME] = @PRM_CUSTOMER_LAST_NAME,
    [DATE_OF_BIRTH] = @PRM_CUSTOMER_DATE_OF_BIRTH,
    [CUSTOMER_TYPE_ID] = @PRM_CUSTOMER_CUSTOMER_TYPE_ID,
    [STATUS] = @PRM_CUSTOMER_STATUS,
    [CREATED_DATE] = @PRM_CUSTOMER_CREATED_DATE,
    [IS_ACTIVE] = @PRM_CUSTOMER_IS_ACTIVE
WHERE
    [ID] = @PRM_CUSTOMER_ID
    AND [IsDeleted] = 0;