INSERT INTO [dbo].[CUSTOMERS] (
    [CUSTOMER_NUMBER],
    [FIRST_NAME],
    [LAST_NAME],
    [DATE_OF_BIRTH],
    [CUSTOMER_TYPE_ID],
    [STATUS],
    [CREATED_DATE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CUSTOMER_CUSTOMER_NUMBER,
    @PRM_CUSTOMER_FIRST_NAME,
    @PRM_CUSTOMER_LAST_NAME,
    @PRM_CUSTOMER_DATE_OF_BIRTH,
    @PRM_CUSTOMER_CUSTOMER_TYPE_ID,
    @PRM_CUSTOMER_STATUS,
    @PRM_CUSTOMER_CREATED_DATE,
    @PRM_CUSTOMER_IS_ACTIVE
    );