SELECT TC.[ID], TC.[CODE], TC.[NAME] 
FROM [TRANSACTION_CHANNELS] TC 
WHERE TC.[IsDeleted] = 0 
	AND TC.[IS_ACTIVE] = @PRM_TRANSACTION_CHANNEL_IS_ACTIVE 
ORDER BY TC.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 