UPDATE [dbo].[TRANSACTION_CHANNELS]
SET
    [CODE] = @PRM_TRANSACTION_CHANNEL_CODE,
    [NAME] = @PRM_TRANSACTION_CHANNEL_NAME,
    [IS_ACTIVE] = @PRM_TRANSACTION_CHANNEL_IS_ACTIVE
WHERE
    [ID] = @PRM_TRANSACTION_CHANNEL_ID
    AND [IsDeleted] = 0;