INSERT INTO [dbo].[TRANSACTION_CHANNELS] (
    [CODE],
    [NAME],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TRANSACTION_CHANNEL_CODE,
    @PRM_TRANSACTION_CHANNEL_NAME,
    @PRM_TRANSACTION_CHANNEL_IS_ACTIVE
    );