//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.RefreshToken;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class RefreshTokenRepository : BaseRepository, IRefreshTokenRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public RefreshTokenRepository(ILogger<RefreshTokenRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "RefreshToken")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<RefreshTokenDto>> InsertAsync(RefreshTokenDto value)
        {
            return await ExecuteWithExceptionHandling(RefreshTokenCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(RefreshTokenCrudSqlBindings.ParameterNamePrefix, value, RefreshTokenCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.RefreshToken>(sql, p);
                return new RepoResponse<RefreshTokenDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(RefreshTokenDto value)
        {
            return await ExecuteWithExceptionHandling(RefreshTokenCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(RefreshTokenCrudSqlBindings.ParameterNamePrefix, value, RefreshTokenCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(RefreshTokenDto value)
        {
            return await ExecuteWithExceptionHandling(RefreshTokenCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(RefreshTokenCrudSqlBindings.ParameterNamePrefix, value, RefreshTokenCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<RefreshTokenDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(RefreshTokenCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(RefreshTokenCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.RefreshToken>(sql, p);
                return row == null ? CreateNotFoundResponse<RefreshTokenDto>("Not found in RefreshToken") : new RepoResponse<RefreshTokenDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<RefreshTokenDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(RefreshTokenCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<RefreshTokenDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.RefreshToken>(sql, p);
                return new RepoResponse<List<RefreshTokenDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(RefreshTokenCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}