//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.RefreshToken;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories;
internal static class RefreshTokenCrudSqlBindings
{
    public const string StoreTableName = "RefreshTokens";
    public const string ParameterNamePrefix = "RefreshToken";
    public const string IdParameterName = "PRM_REFRESH_TOKEN_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string GetRefreshToken = "GetRefreshToken";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateRefreshTokens = "UpdateRefreshTokens";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("UserId", nameof(RefreshTokenDto.UserId)),
        ("Token", nameof(RefreshTokenDto.Token)),
        ("ExpiryDate", nameof(RefreshTokenDto.ExpiryDate)),
        ("CreatedDate", nameof(RefreshTokenDto.CreatedDate)),
        ("IsRevoked", nameof(RefreshTokenDto.IsRevoked))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("UserId", nameof(RefreshTokenDto.UserId)),
        ("Token", nameof(RefreshTokenDto.Token)),
        ("ExpiryDate", nameof(RefreshTokenDto.ExpiryDate)),
        ("CreatedDate", nameof(RefreshTokenDto.CreatedDate)),
        ("IsRevoked", nameof(RefreshTokenDto.IsRevoked)),
        ("Id", nameof(RefreshTokenDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("Id", nameof(RefreshTokenDto.Id))
    };
}