//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.RepaymentSchedule;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories;
internal static class RepaymentScheduleCrudSqlBindings
{
    public const string StoreTableName = "REPAYMENT_SCHEDULES";
    public const string ParameterNamePrefix = "REPAYMENT_SCHEDULE";
    public const string IdParameterName = "PRM_REPAYMENT_SCHEDULE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByLoanId = "GetByLoanId";
        public const string GetByPk = "GetByPk";
        public const string GetOverduePayments = "GetOverduePayments";
        public const string GetUpcomingPayments = "GetUpcomingPayments";
        public const string Insert = "Insert";
        public const string MarkAsPaid = "MarkAsPaid";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("LOAN_ID", nameof(RepaymentScheduleDto.LoanId)),
        ("INSTALLMENT_NUMBER", nameof(RepaymentScheduleDto.InstallmentNumber)),
        ("DUE_DATE", nameof(RepaymentScheduleDto.DueDate)),
        ("PRINCIPAL_AMOUNT", nameof(RepaymentScheduleDto.PrincipalAmount)),
        ("INTEREST_AMOUNT", nameof(RepaymentScheduleDto.InterestAmount)),
        ("TOTAL_AMOUNT", nameof(RepaymentScheduleDto.TotalAmount)),
        ("STATUS", nameof(RepaymentScheduleDto.Status))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("LOAN_ID", nameof(RepaymentScheduleDto.LoanId)),
        ("INSTALLMENT_NUMBER", nameof(RepaymentScheduleDto.InstallmentNumber)),
        ("DUE_DATE", nameof(RepaymentScheduleDto.DueDate)),
        ("PRINCIPAL_AMOUNT", nameof(RepaymentScheduleDto.PrincipalAmount)),
        ("INTEREST_AMOUNT", nameof(RepaymentScheduleDto.InterestAmount)),
        ("TOTAL_AMOUNT", nameof(RepaymentScheduleDto.TotalAmount)),
        ("STATUS", nameof(RepaymentScheduleDto.Status)),
        ("ID", nameof(RepaymentScheduleDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(RepaymentScheduleDto.Id))
    };
}