//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.RepaymentSchedule;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories
{
    public partial class RepaymentScheduleRepository : BaseRepository, IRepaymentScheduleRepository
    {
        public async Task<RepoResponse<int>> MarkAsPaidAsync(int repaymentScheduleId, MarkAsPaidRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(RepaymentScheduleCrudSqlBindings.OperationNames.MarkAsPaid, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RepaymentSchedule.Command.MarkAsPaid);
                var parameters = new
                {
                    PRM_REPAYMENT_SCHEDULE_ID = repaymentScheduleId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}