//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.TransactionFee;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Mappings;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Sql;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Repositories
{
    public partial class TransactionFeeRepository : BaseRepository, ITransactionFeeRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public TransactionFeeRepository(ILogger<TransactionFeeRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "TransactionFee")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<TransactionFeeDto>> InsertAsync(TransactionFeeDto value)
        {
            return await ExecuteWithExceptionHandling(TransactionFeeCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TransactionFee.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(TransactionFeeCrudSqlBindings.ParameterNamePrefix, value, TransactionFeeCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.TransactionFee>(sql, p);
                return new RepoResponse<TransactionFeeDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(TransactionFeeDto value)
        {
            return await ExecuteWithExceptionHandling(TransactionFeeCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TransactionFee.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(TransactionFeeCrudSqlBindings.ParameterNamePrefix, value, TransactionFeeCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(TransactionFeeDto value)
        {
            return await ExecuteWithExceptionHandling(TransactionFeeCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TransactionFee.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(TransactionFeeCrudSqlBindings.ParameterNamePrefix, value, TransactionFeeCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<TransactionFeeDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(TransactionFeeCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TransactionFee.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(TransactionFeeCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.TransactionFee>(sql, p);
                return row == null ? CreateNotFoundResponse<TransactionFeeDto>("Not found in TransactionFee") : new RepoResponse<TransactionFeeDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<TransactionFeeDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(TransactionFeeCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<TransactionFeeDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.TransactionFee.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.TransactionFee>(sql, p);
                return new RepoResponse<List<TransactionFeeDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(TransactionFeeCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TransactionFee.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}