//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.TransactionFee;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Repositories;
internal static class TransactionFeeCrudSqlBindings
{
    public const string StoreTableName = "TRANSACTION_FEES";
    public const string ParameterNamePrefix = "TRANSACTION_FEE";
    public const string IdParameterName = "PRM_TRANSACTION_FEE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string GetFeesByTransactionId = "GetFeesByTransactionId";
        public const string GetFeesWithDetails = "GetFeesWithDetails";
        public const string GetTotalFeesByType = "GetTotalFeesByType";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("TRANSACTION_ID", nameof(TransactionFeeDto.TransactionId)),
        ("FEE_TYPE_ID", nameof(TransactionFeeDto.FeeTypeId)),
        ("FEE_AMOUNT", nameof(TransactionFeeDto.FeeAmount)),
        ("APPLIED_DATE", nameof(TransactionFeeDto.AppliedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("TRANSACTION_ID", nameof(TransactionFeeDto.TransactionId)),
        ("FEE_TYPE_ID", nameof(TransactionFeeDto.FeeTypeId)),
        ("FEE_AMOUNT", nameof(TransactionFeeDto.FeeAmount)),
        ("APPLIED_DATE", nameof(TransactionFeeDto.AppliedDate)),
        ("ID", nameof(TransactionFeeDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(TransactionFeeDto.Id))
    };
}