//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.Account;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories
{
    public partial class AccountRepository : BaseRepository, IAccountRepository
    {
        public async Task<RepoResponse<GetByAccountNumberResponseDto>> GetByAccountNumberAsync(string accountAccountNumber)
        {
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.GetByAccountNumber, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Account.Query.GetByAccountNumber);
                var parameters = new
                {
                    PRM_ACCOUNT_ACCOUNT_NUMBER = accountAccountNumber
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByAccountNumberResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Account");
            });
        }

        public async Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int accountCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.GetByCustomerId, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Account.Query.GetByCustomerId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ACCOUNT_CUSTOMER_ID = accountCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCustomerIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Account");
                }
            });
        }

        public async Task<RepoResponse<List<GetAccountsWithDetailsResponseDto>>> GetAccountsWithDetailsAsync(int accountsCustomerId, int accountAccountTypeId, int accountCurrencyId, int accountTypeId, int currencyId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.GetAccountsWithDetails, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetAccountsWithDetailsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Account.Query.GetAccountsWithDetails);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ACCOUNTS_CUSTOMER_ID = accountsCustomerId,
                        PRM_ACCOUNTS_ACCOUNT_TYPE_ID = accountAccountTypeId,
                        PRM_ACCOUNT_TYPES_ID = accountTypeId,
                        PRM_ACCOUNTS_CURRENCY_ID = accountCurrencyId,
                        PRM_CURRENCIES_ID = currencyId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetAccountsWithDetailsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Account");
                }
            });
        }

        public async Task<RepoResponse<List<GetLowBalanceAccountsResponseDto>>> GetLowBalanceAccountsAsync(AccountStatus accountStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.GetLowBalanceAccounts, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetLowBalanceAccountsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Account.Query.GetLowBalanceAccounts);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ACCOUNT_STATUS = accountStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetLowBalanceAccountsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Account");
                }
            });
        }

        public async Task<RepoResponse<List<GetDormantAccountsResponseDto>>> GetDormantAccountsAsync(AccountStatus accountStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.GetDormantAccounts, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetDormantAccountsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Account.Query.GetDormantAccounts);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ACCOUNT_STATUS = accountStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetDormantAccountsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Account");
                }
            });
        }

        public async Task<RepoResponse<long>> GetTotalBalanceByCustomerAsync(int accountCustomerId, AccountStatus accountStatus)
        {
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.GetTotalBalanceByCustomer, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Account.Query.GetTotalBalanceByCustomer);
                var parameters = new
                {
                    PRM_ACCOUNT_CUSTOMER_ID = accountCustomerId,
                    PRM_ACCOUNT_STATUS = accountStatus
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result);
            });
        }
    }
}