//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.Account;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories;
internal static class AccountCrudSqlBindings
{
    public const string StoreTableName = "ACCOUNTS";
    public const string ParameterNamePrefix = "ACCOUNT";
    public const string IdParameterName = "PRM_ACCOUNT_ID";
    public static class OperationNames
    {
        public const string ApproveAccount = "ApproveAccount";
        public const string CloseAccount = "CloseAccount";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string FreezeAccount = "FreezeAccount";
        public const string GetAccountsWithDetails = "GetAccountsWithDetails";
        public const string GetByAccountNumber = "GetByAccountNumber";
        public const string GetByCustomerId = "GetByCustomerId";
        public const string GetByPk = "GetByPk";
        public const string GetDormantAccounts = "GetDormantAccounts";
        public const string GetLowBalanceAccounts = "GetLowBalanceAccounts";
        public const string GetTotalBalanceByCustomer = "GetTotalBalanceByCustomer";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateBalance = "UpdateBalance";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("ACCOUNT_NUMBER", nameof(AccountDto.AccountNumber)),
        ("CUSTOMER_ID", nameof(AccountDto.CustomerId)),
        ("ACCOUNT_TYPE_ID", nameof(AccountDto.AccountTypeId)),
        ("CURRENCY_ID", nameof(AccountDto.CurrencyId)),
        ("BALANCE", nameof(AccountDto.Balance)),
        ("STATUS", nameof(AccountDto.Status)),
        ("OPENED_DATE", nameof(AccountDto.OpenedDate)),
        ("CLOSED_DATE", nameof(AccountDto.ClosedDate)),
        ("IS_ACTIVE", nameof(AccountDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("ACCOUNT_NUMBER", nameof(AccountDto.AccountNumber)),
        ("CUSTOMER_ID", nameof(AccountDto.CustomerId)),
        ("ACCOUNT_TYPE_ID", nameof(AccountDto.AccountTypeId)),
        ("CURRENCY_ID", nameof(AccountDto.CurrencyId)),
        ("BALANCE", nameof(AccountDto.Balance)),
        ("STATUS", nameof(AccountDto.Status)),
        ("OPENED_DATE", nameof(AccountDto.OpenedDate)),
        ("CLOSED_DATE", nameof(AccountDto.ClosedDate)),
        ("IS_ACTIVE", nameof(AccountDto.IsActive)),
        ("ID", nameof(AccountDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(AccountDto.Id))
    };
}