//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.Account;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories
{
    public partial class AccountRepository : BaseRepository, IAccountRepository
    {
        public async Task<RepoResponse<int>> ApproveAccountAsync(int accountId, ApproveAccountRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.ApproveAccount, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Account.Command.ApproveAccount);
                var parameters = new
                {
                    PRM_ACCOUNT_ID = accountId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> FreezeAccountAsync(int accountId, FreezeAccountRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.FreezeAccount, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Account.Command.FreezeAccount);
                var parameters = new
                {
                    PRM_ACCOUNT_ID = accountId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> CloseAccountAsync(int accountId, CloseAccountRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.CloseAccount, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Account.Command.CloseAccount);
                var parameters = new
                {
                    PRM_ACCOUNT_ID = accountId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdateBalanceAsync(int accountId, UpdateBalanceRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(AccountCrudSqlBindings.OperationNames.UpdateBalance, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Account.Command.UpdateBalance);
                var parameters = new
                {
                    ACCOUNT_BALANCE = updateRequest.AccountBalance,
                    PRM_ACCOUNT_ID = accountId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}