SELECT C.[ID], C.[CUSTOMER_NUMBER], C.[FIRST_NAME], C.[LAST_NAME], CR.[RELATIONSHIP_TYPE] 
FROM [CUSTOMER_RELATIONSHIPS] CR 
	INNER JOIN [CUSTOMERS] C 
			ON CR.[PRIMARY_CUSTOMER_ID] = C.[ID] 
WHERE CR.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND CR.[PRIMARY_CUSTOMER_ID] = @PRM_CUSTOMER_RELATIONSHIPS_PRIMARY_CUSTOMER_ID 
	AND CR.[RELATED_CUSTOMER_ID] = @PRM_CUSTOMER_RELATIONSHIPS_RELATED_CUSTOMER_ID 
	AND C.[ID] = @PRM_CUSTOMERS_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 