SELECT CR.[ID], CR.[RELATED_CUSTOMER_ID], CR.[RELATIONSHIP_TYPE] 
FROM [CUSTOMER_RELATIONSHIPS] CR 
WHERE CR.[IsDeleted] = 0 
	AND CR.[PRIMARY_CUSTOMER_ID] = @PRM_CUSTOMER_RELATIONSHIP_PRIMARY_CUSTOMER_ID 
ORDER BY CR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 