//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.KafkaEvent;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories;
internal static class KafkaEventCrudSqlBindings
{
    public const string StoreTableName = "KafkaEvents";
    public const string ParameterNamePrefix = "KafkaEvent";
    public const string TopicNameParameterName = "PRM_KAFKA_EVENT_TOPIC_NAME";
    public static class OperationNames
    {
        public const string CleanKafkaEventsWithModelName = "CleanKafkaEventsWithModelName";
        public const string CleanKafkaEventsWithModuleName = "CleanKafkaEventsWithModuleName";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetActiveKafkaEvents = "GetActiveKafkaEvents";
        public const string GetByPk = "GetByPk";
        public const string GetKafkaEvents = "GetKafkaEvents";
        public const string GetTopicWorkflows = "GetTopicWorkflows";
        public const string GetTopicWorkflowsKafkaEvents = "GetTopicWorkflowsKafkaEvents";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("TopicName", nameof(KafkaEventDto.TopicName)),
        ("ApiMethodDefinitionKey", nameof(KafkaEventDto.ApiMethodDefinitionKey)),
        ("IsActive", nameof(KafkaEventDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("ApiMethodDefinitionKey", nameof(KafkaEventDto.ApiMethodDefinitionKey)),
        ("IsActive", nameof(KafkaEventDto.IsActive)),
        ("TopicName", nameof(KafkaEventDto.TopicName))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("TopicName", nameof(KafkaEventDto.TopicName))
    };
}