UPDATE [dbo].[COLLATERAL_TYPES]
SET
    [CODE] = @PRM_COLLATERAL_TYPE_CODE,
    [NAME] = @PRM_COLLATERAL_TYPE_NAME,
    [IS_ACTIVE] = @PRM_COLLATERAL_TYPE_IS_ACTIVE
WHERE
    [ID] = @PRM_COLLATERAL_TYPE_ID
    AND [IsDeleted] = 0;