INSERT INTO [dbo].[COLLATERAL_TYPES] (
    [CODE],
    [NAME],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_COLLATERAL_TYPE_CODE,
    @PRM_COLLATERAL_TYPE_NAME,
    @PRM_COLLATERAL_TYPE_IS_ACTIVE
    );