DELETE FROM [dbo].[ApiMethodAccessGrants]
WHERE
    [PermissionGroupName] = @PRM_API_METHOD_ACCESS_GRANT_PERMISSION_GROUP_NAME AND
    [ApiMethodDefinitionKey] = @PRM_API_METHOD_ACCESS_GRANT_API_METHOD_DEFINITION_KEY;