UPDATE [dbo].[ApiMethodAccessGrants]
SET
    [ModifiedBy] = @PRM_API_METHOD_ACCESS_GRANT_MODIFIED_BY,
    [IsActive] = @PRM_API_METHOD_ACCESS_GRANT_IS_ACTIVE
WHERE
    [PermissionGroupName] = @PRM_API_METHOD_ACCESS_GRANT_PERMISSION_GROUP_NAME AND
    [ApiMethodDefinitionKey] = @PRM_API_METHOD_ACCESS_GRANT_API_METHOD_DEFINITION_KEY;