//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.IdentificationDocument;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories
{
    public partial class IdentificationDocumentRepository : BaseRepository, IIdentificationDocumentRepository
    {
        public async Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int identificationDocumentCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(IdentificationDocumentCrudSqlBindings.OperationNames.GetByCustomerId, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.IdentificationDocument.Query.GetByCustomerId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_IDENTIFICATION_DOCUMENT_CUSTOMER_ID = identificationDocumentCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCustomerIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in IdentificationDocument");
                }
            });
        }

        public async Task<RepoResponse<List<GetDocumentsWithTypeResponseDto>>> GetDocumentsWithTypeAsync(int identificationDocumentsCustomerId, int identificationDocumentsDocumentTypeId, int documentTypesId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(IdentificationDocumentCrudSqlBindings.OperationNames.GetDocumentsWithType, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetDocumentsWithTypeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.IdentificationDocument.Query.GetDocumentsWithType);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_IDENTIFICATION_DOCUMENTS_CUSTOMER_ID = identificationDocumentsCustomerId,
                        PRM_IDENTIFICATION_DOCUMENTS_DOCUMENT_TYPE_ID = identificationDocumentsDocumentTypeId,
                        PRM_DOCUMENT_TYPES_ID = documentTypesId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetDocumentsWithTypeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in IdentificationDocument");
                }
            });
        }

        public async Task<RepoResponse<List<GetExpiringSoonResponseDto>>> GetExpiringSoonAsync(DocumentStatus identificationDocumentStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(IdentificationDocumentCrudSqlBindings.OperationNames.GetExpiringSoon, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetExpiringSoonResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.IdentificationDocument.Query.GetExpiringSoon);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_IDENTIFICATION_DOCUMENT_STATUS = identificationDocumentStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetExpiringSoonResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in IdentificationDocument");
                }
            });
        }
    }
}