//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.AspNetRole;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class AspNetRoleRepository : BaseRepository, IAspNetRoleRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public AspNetRoleRepository(ILogger<AspNetRoleRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "AspNetRole")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<AspNetRoleDto>> InsertAsync(AspNetRoleDto value)
        {
            return await ExecuteWithExceptionHandling(AspNetRoleCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(AspNetRoleCrudSqlBindings.ParameterNamePrefix, value, AspNetRoleCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.AspNetRole>(sql, p);
                return new RepoResponse<AspNetRoleDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(AspNetRoleDto value)
        {
            return await ExecuteWithExceptionHandling(AspNetRoleCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(AspNetRoleCrudSqlBindings.ParameterNamePrefix, value, AspNetRoleCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(AspNetRoleDto value)
        {
            return await ExecuteWithExceptionHandling(AspNetRoleCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(AspNetRoleCrudSqlBindings.ParameterNamePrefix, value, AspNetRoleCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<AspNetRoleDto>> GetByPkAsync(string id)
        {
            return await ExecuteWithExceptionHandling(AspNetRoleCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(AspNetRoleCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.AspNetRole>(sql, p);
                return row == null ? CreateNotFoundResponse<AspNetRoleDto>("Not found in AspNetRole") : new RepoResponse<AspNetRoleDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<AspNetRoleDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(AspNetRoleCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<AspNetRoleDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.AspNetRole>(sql, p);
                return new RepoResponse<List<AspNetRoleDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(AspNetRoleCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}