SELECT AH.[ACCOUNT_ID], AH.[ROLE] 
FROM [ACCOUNT_HOLDERS] AH 
WHERE AH.[CUSTOMER_ID] = @PRM_ACCOUNT_HOLDER_CUSTOMER_ID 
ORDER BY AH.[ACCOUNT_ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 