SELECT AH.[CUSTOMER_ID], AH.[ROLE] 
FROM [ACCOUNT_HOLDERS] AH 
WHERE AH.[ACCOUNT_ID] = @PRM_ACCOUNT_HOLDER_ACCOUNT_ID 
ORDER BY AH.[CUSTOMER_ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 