//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.AccountStatement;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories;
internal static class AccountStatementCrudSqlBindings
{
    public const string StoreTableName = "ACCOUNT_STATEMENTS";
    public const string ParameterNamePrefix = "ACCOUNT_STATEMENT";
    public const string IdParameterName = "PRM_ACCOUNT_STATEMENT_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string DeleteStatement = "DeleteStatement";
        public const string GetByAccountId = "GetByAccountId";
        public const string GetByDateRange = "GetByDateRange";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("ACCOUNT_ID", nameof(AccountStatementDto.AccountId)),
        ("STATEMENT_PERIOD_START", nameof(AccountStatementDto.StatementPeriodStart)),
        ("STATEMENT_PERIOD_END", nameof(AccountStatementDto.StatementPeriodEnd)),
        ("GENERATED_DATE", nameof(AccountStatementDto.GeneratedDate)),
        ("OPENING_BALANCE", nameof(AccountStatementDto.OpeningBalance)),
        ("CLOSING_BALANCE", nameof(AccountStatementDto.ClosingBalance)),
        ("STATEMENT_URL", nameof(AccountStatementDto.StatementUrl)),
        ("FORMAT", nameof(AccountStatementDto.Format))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("ACCOUNT_ID", nameof(AccountStatementDto.AccountId)),
        ("STATEMENT_PERIOD_START", nameof(AccountStatementDto.StatementPeriodStart)),
        ("STATEMENT_PERIOD_END", nameof(AccountStatementDto.StatementPeriodEnd)),
        ("GENERATED_DATE", nameof(AccountStatementDto.GeneratedDate)),
        ("OPENING_BALANCE", nameof(AccountStatementDto.OpeningBalance)),
        ("CLOSING_BALANCE", nameof(AccountStatementDto.ClosingBalance)),
        ("STATEMENT_URL", nameof(AccountStatementDto.StatementUrl)),
        ("FORMAT", nameof(AccountStatementDto.Format)),
        ("ID", nameof(AccountStatementDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(AccountStatementDto.Id))
    };
}