SELECT CT.[ID], CT.[CODE], CT.[NAME], CT.[NETWORK] 
FROM [CARD_TYPES] CT 
WHERE CT.[IsDeleted] = 0 
	AND CT.[IS_ACTIVE] = @PRM_CARD_TYPE_IS_ACTIVE 
ORDER BY CT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 