//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Contexts;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.Model;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class ModelRepository : BaseRepository, IModelRepository
    {
        public async Task<RepoResponse<bool>> ModuleNameIsExistsAsync(string modelModuleName)
        {
            return await ExecuteWithExceptionHandling("ModuleNameIsExists", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Model.Query.ModuleNameIsExists);
                var parameters = new
                {
                    PRM_Model_ModuleName = modelModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in Model");
            });
        }
    }
}