//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.Transaction;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Mappings;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Sql;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Repositories
{
    public partial class TransactionRepository : BaseRepository, ITransactionRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public TransactionRepository(ILogger<TransactionRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "Transaction")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<TransactionDto>> InsertAsync(TransactionDto value)
        {
            return await ExecuteWithExceptionHandling(TransactionCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Transaction.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(TransactionCrudSqlBindings.ParameterNamePrefix, value, TransactionCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.Transaction>(sql, p);
                return new RepoResponse<TransactionDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(TransactionDto value)
        {
            return await ExecuteWithExceptionHandling(TransactionCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Transaction.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(TransactionCrudSqlBindings.ParameterNamePrefix, value, TransactionCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(TransactionDto value)
        {
            return await ExecuteWithExceptionHandling(TransactionCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Transaction.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(TransactionCrudSqlBindings.ParameterNamePrefix, value, TransactionCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<TransactionDto>> GetByPkAsync(long id)
        {
            return await ExecuteWithExceptionHandling(TransactionCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Transaction.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(TransactionCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.Transaction>(sql, p);
                return row == null ? CreateNotFoundResponse<TransactionDto>("Not found in Transaction") : new RepoResponse<TransactionDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<TransactionDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(TransactionCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<TransactionDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.Transaction.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.Transaction>(sql, p);
                return new RepoResponse<List<TransactionDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(TransactionCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Transaction.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}