//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.Transaction;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Repositories;
internal static class TransactionCrudSqlBindings
{
    public const string StoreTableName = "TRANSACTIONS";
    public const string ParameterNamePrefix = "TRANSACTION";
    public const string IdParameterName = "PRM_TRANSACTION_ID";
    public static class OperationNames
    {
        public const string CompleteTransaction = "CompleteTransaction";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string FailTransaction = "FailTransaction";
        public const string GetByDateRange = "GetByDateRange";
        public const string GetByDestinationAccount = "GetByDestinationAccount";
        public const string GetByPk = "GetByPk";
        public const string GetByReference = "GetByReference";
        public const string GetBySourceAccount = "GetBySourceAccount";
        public const string GetDailyVolume = "GetDailyVolume";
        public const string GetFailedTransactions = "GetFailedTransactions";
        public const string GetTransactionsWithDetails = "GetTransactionsWithDetails";
        public const string Insert = "Insert";
        public const string ReverseTransaction = "ReverseTransaction";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("TRANSACTION_REFERENCE", nameof(TransactionDto.TransactionReference)),
        ("SOURCE_ACCOUNT_ID", nameof(TransactionDto.SourceAccountId)),
        ("DESTINATION_ACCOUNT_ID", nameof(TransactionDto.DestinationAccountId)),
        ("TRANSACTION_TYPE_ID", nameof(TransactionDto.TransactionTypeId)),
        ("TRANSACTION_CHANNEL_ID", nameof(TransactionDto.TransactionChannelId)),
        ("AMOUNT", nameof(TransactionDto.Amount)),
        ("CURRENCY_CODE", nameof(TransactionDto.CurrencyCode)),
        ("DESCRIPTION", nameof(TransactionDto.Description)),
        ("STATUS", nameof(TransactionDto.Status)),
        ("TRANSACTION_DATE", nameof(TransactionDto.TransactionDate)),
        ("COMPLETED_DATE", nameof(TransactionDto.CompletedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("TRANSACTION_REFERENCE", nameof(TransactionDto.TransactionReference)),
        ("SOURCE_ACCOUNT_ID", nameof(TransactionDto.SourceAccountId)),
        ("DESTINATION_ACCOUNT_ID", nameof(TransactionDto.DestinationAccountId)),
        ("TRANSACTION_TYPE_ID", nameof(TransactionDto.TransactionTypeId)),
        ("TRANSACTION_CHANNEL_ID", nameof(TransactionDto.TransactionChannelId)),
        ("AMOUNT", nameof(TransactionDto.Amount)),
        ("CURRENCY_CODE", nameof(TransactionDto.CurrencyCode)),
        ("DESCRIPTION", nameof(TransactionDto.Description)),
        ("STATUS", nameof(TransactionDto.Status)),
        ("TRANSACTION_DATE", nameof(TransactionDto.TransactionDate)),
        ("COMPLETED_DATE", nameof(TransactionDto.CompletedDate)),
        ("ID", nameof(TransactionDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(TransactionDto.Id))
    };
}