SELECT T.[ID], T.[TRANSACTION_REFERENCE], T.[AMOUNT], T.[STATUS], T.[TRANSACTION_DATE] 
FROM [TRANSACTIONS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[SOURCE_ACCOUNT_ID] = @PRM_TRANSACTION_SOURCE_ACCOUNT_ID 
	AND T.[TRANSACTION_DATE] BETWEEN @PRM_TRANSACTION_TRANSACTION_DATE_From 
	AND @PRM_TRANSACTION_TRANSACTION_DATE_To 
ORDER BY T.[TRANSACTION_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 