SELECT T.[ID], T.[TRANSACTION_REFERENCE], T.[SOURCE_ACCOUNT_ID], T.[AMOUNT] 
FROM [TRANSACTIONS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[STATUS] = @PRM_TRANSACTION_STATUS 
ORDER BY T.[TRANSACTION_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 