SELECT T.[ID], T.[TRANSACTION_REFERENCE], TT.[NAME] AS TRANSACTION_TYPE,
	TC.[NAME] AS CHANNEL,
	T.[AMOUNT], T.[STATUS], T.[TRANSACTION_DATE] 
FROM [TRANSACTIONS] T 
	INNER JOIN [TRANSACTION_TYPES] TT 
			ON T.[TRANSACTION_TYPE_ID] = TT.[ID] 
	INNER JOIN [TRANSACTION_CHANNELS] TC 
			ON T.[TRANSACTION_CHANNEL_ID] = TC.[ID] 
WHERE T.[IsDeleted] = 0 
	AND TT.[IsDeleted] = 0 
	AND TC.[IsDeleted] = 0 
	AND T.[SOURCE_ACCOUNT_ID] = @PRM_TRANSACTIONS_SOURCE_ACCOUNT_ID 
	AND T.[TRANSACTION_TYPE_ID] = @PRM_TRANSACTIONS_TRANSACTION_TYPE_ID 
	AND TT.[ID] = @PRM_TRANSACTION_TYPES_ID 
	AND T.[TRANSACTION_CHANNEL_ID] = @PRM_TRANSACTIONS_TRANSACTION_CHANNEL_ID 
	AND TC.[ID] = @PRM_TRANSACTION_CHANNELS_ID 
ORDER BY T.[TRANSACTION_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 