SELECT T.[ID], T.[TRANSACTION_REFERENCE], T.[SOURCE_ACCOUNT_ID], T.[AMOUNT], T.[STATUS], T.[TRANSACTION_DATE] 
FROM [TRANSACTIONS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[DESTINATION_ACCOUNT_ID] = @PRM_TRANSACTION_DESTINATION_ACCOUNT_ID 
ORDER BY T.[TRANSACTION_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 