SELECT TOP 1 T.[ID], T.[TRANSACTION_REFERENCE], T.[SOURCE_ACCOUNT_ID], T.[DESTINATION_ACCOUNT_ID], T.[AMOUNT], T.[STATUS] 
FROM [TRANSACTIONS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[TRANSACTION_REFERENCE] = @PRM_TRANSACTION_TRANSACTION_REFERENCE 
ORDER BY T.[ID] 