//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.CustomerRelationship
{
    public record CustomerRelationshipDto
    {
        public int Id { get; init; }
        public int PrimaryCustomerId { get; init; }
        public int RelatedCustomerId { get; init; }
        public string RelationshipType { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}