SELECT
    [ID],
    [CUSTOMER_ID],
    [ADDRESS_LINE_1],
    [ADDRESS_LINE_2],
    [CITY],
    [STATE],
    [POSTAL_CODE],
    [COUNTRY_CODE],
    [TYPE],
    [IS_PRIMARY]
FROM [dbo].[ADDRESSES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;