UPDATE [dbo].[ADDRESSES]
SET
    [CUSTOMER_ID] = @PRM_ADDRESS_CUSTOMER_ID,
    [ADDRESS_LINE_1] = @PRM_ADDRESS_ADDRESS_LINE_1,
    [ADDRESS_LINE_2] = @PRM_ADDRESS_ADDRESS_LINE_2,
    [CITY] = @PRM_ADDRESS_CITY,
    [STATE] = @PRM_ADDRESS_STATE,
    [POSTAL_CODE] = @PRM_ADDRESS_POSTAL_CODE,
    [COUNTRY_CODE] = @PRM_ADDRESS_COUNTRY_CODE,
    [TYPE] = @PRM_ADDRESS_TYPE,
    [IS_PRIMARY] = @PRM_ADDRESS_IS_PRIMARY
WHERE
    [ID] = @PRM_ADDRESS_ID
    AND [IsDeleted] = 0;