INSERT INTO [dbo].[ADDRESSES] (
    [CUSTOMER_ID],
    [ADDRESS_LINE_1],
    [ADDRESS_LINE_2],
    [CITY],
    [STATE],
    [POSTAL_CODE],
    [COUNTRY_CODE],
    [TYPE],
    [IS_PRIMARY]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_ADDRESS_CUSTOMER_ID,
    @PRM_ADDRESS_ADDRESS_LINE_1,
    @PRM_ADDRESS_ADDRESS_LINE_2,
    @PRM_ADDRESS_CITY,
    @PRM_ADDRESS_STATE,
    @PRM_ADDRESS_POSTAL_CODE,
    @PRM_ADDRESS_COUNTRY_CODE,
    @PRM_ADDRESS_TYPE,
    @PRM_ADDRESS_IS_PRIMARY
    );