//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Contexts;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodDefinitionRepository : BaseRepository, IApiMethodDefinitionRepository
    {
        public async Task<RepoResponse<List<GetKafkaEventsApiMethodDefinitionsResponseDto>>> GetKafkaEventsApiMethodDefinitionsAsync(string apiMethodDefinitionsKey, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetKafkaEventsApiMethodDefinitions", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetKafkaEventsApiMethodDefinitionsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetKafkaEventsApiMethodDefinitions);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ApiMethodDefinitions_Key = apiMethodDefinitionsKey,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetKafkaEventsApiMethodDefinitionsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ApiMethodDefinition");
                }
            });
        }

        public async Task<RepoResponse<List<GetApiMethodDefinitionsWithModuleNameResponseDto>>> GetApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModuleName = apiMethodDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsWithModuleNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodDefinitionsWithModelNameResponseDto>>> GetApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModelName = apiMethodDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsWithModelNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("ExistsApiMethodDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.ExistsApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModuleName = apiMethodDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("ExistsApiMethodDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.ExistsApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModelName = apiMethodDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in ApiMethodDefinition");
            });
        }
    }
}