//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodDefinitionRepository : BaseRepository, IApiMethodDefinitionRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public ApiMethodDefinitionRepository(ILogger<ApiMethodDefinitionRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "ApiMethodDefinition")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<ApiMethodDefinitionDto>> InsertAsync(ApiMethodDefinitionDto value)
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(ApiMethodDefinitionCrudSqlBindings.ParameterNamePrefix, value, ApiMethodDefinitionCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.ApiMethodDefinition>(sql, p);
                return new RepoResponse<ApiMethodDefinitionDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ApiMethodDefinitionDto value)
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(ApiMethodDefinitionCrudSqlBindings.ParameterNamePrefix, value, ApiMethodDefinitionCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ApiMethodDefinitionDto value)
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(ApiMethodDefinitionCrudSqlBindings.ParameterNamePrefix, value, ApiMethodDefinitionCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<ApiMethodDefinitionDto>> GetByPkAsync(string key)
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(ApiMethodDefinitionCrudSqlBindings.KeyParameterName, key);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.ApiMethodDefinition>(sql, p);
                return row == null ? CreateNotFoundResponse<ApiMethodDefinitionDto>("Not found in ApiMethodDefinition") : new RepoResponse<ApiMethodDefinitionDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<ApiMethodDefinitionDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ApiMethodDefinitionDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.ApiMethodDefinition>(sql, p);
                return new RepoResponse<List<ApiMethodDefinitionDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(ApiMethodDefinitionCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}