SELECT
    [ID],
    [LOAN_ACCOUNT_NUMBER],
    [APPLICATION_ID],
    [CUSTOMER_ID],
    [PRINCIPAL_AMOUNT],
    [OUTSTANDING_BALANCE],
    [INTEREST_RATE],
    [TERM_MONTHS],
    [DISBURSEMENT_DATE],
    [MATURITY_DATE],
    [STATUS]
FROM [dbo].[LOANS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;