SELECT
    [ID],
    [LOAN_ACCOUNT_NUMBER],
    [APPLICATION_ID],
    [CUSTOMER_ID],
    [PRINCIPAL_AMOUNT],
    [OUTSTANDING_BALANCE],
    [INTEREST_RATE],
    [TERM_MONTHS],
    [DISBURSEMENT_DATE],
    [MATURITY_DATE],
    [STATUS]
FROM [dbo].[LOANS]
WHERE
    [ID] = @PRM_LOAN_ID
    AND [IsDeleted] = 0;