INSERT INTO [dbo].[LOANS] (
    [LOAN_ACCOUNT_NUMBER],
    [APPLICATION_ID],
    [CUSTOMER_ID],
    [PRINCIPAL_AMOUNT],
    [OUTSTANDING_BALANCE],
    [INTEREST_RATE],
    [TERM_MONTHS],
    [DISBURSEMENT_DATE],
    [MATURITY_DATE],
    [STATUS]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_LOAN_LOAN_ACCOUNT_NUMBER,
    @PRM_LOAN_APPLICATION_ID,
    @PRM_LOAN_CUSTOMER_ID,
    @PRM_LOAN_PRINCIPAL_AMOUNT,
    @PRM_LOAN_OUTSTANDING_BALANCE,
    @PRM_LOAN_INTEREST_RATE,
    @PRM_LOAN_TERM_MONTHS,
    @PRM_LOAN_DISBURSEMENT_DATE,
    @PRM_LOAN_MATURITY_DATE,
    @PRM_LOAN_STATUS
    );