//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.CollateralType;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories
{
    public partial class CollateralTypeRepository : BaseRepository, ICollateralTypeRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public CollateralTypeRepository(ILogger<CollateralTypeRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "CollateralType")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<CollateralTypeDto>> InsertAsync(CollateralTypeDto value)
        {
            return await ExecuteWithExceptionHandling(CollateralTypeCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CollateralType.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(CollateralTypeCrudSqlBindings.ParameterNamePrefix, value, CollateralTypeCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.CollateralType>(sql, p);
                return new RepoResponse<CollateralTypeDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CollateralTypeDto value)
        {
            return await ExecuteWithExceptionHandling(CollateralTypeCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CollateralType.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(CollateralTypeCrudSqlBindings.ParameterNamePrefix, value, CollateralTypeCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CollateralTypeDto value)
        {
            return await ExecuteWithExceptionHandling(CollateralTypeCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CollateralType.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(CollateralTypeCrudSqlBindings.ParameterNamePrefix, value, CollateralTypeCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<CollateralTypeDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(CollateralTypeCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CollateralType.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(CollateralTypeCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.CollateralType>(sql, p);
                return row == null ? CreateNotFoundResponse<CollateralTypeDto>("Not found in CollateralType") : new RepoResponse<CollateralTypeDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<CollateralTypeDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(CollateralTypeCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CollateralTypeDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.CollateralType.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.CollateralType>(sql, p);
                return new RepoResponse<List<CollateralTypeDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(CollateralTypeCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CollateralType.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}