//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.CollateralType;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories;
internal static class CollateralTypeCrudSqlBindings
{
    public const string StoreTableName = "COLLATERAL_TYPES";
    public const string ParameterNamePrefix = "COLLATERAL_TYPE";
    public const string IdParameterName = "PRM_COLLATERAL_TYPE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCode = "GetByCode";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CODE", nameof(CollateralTypeDto.Code)),
        ("NAME", nameof(CollateralTypeDto.Name)),
        ("IS_ACTIVE", nameof(CollateralTypeDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CODE", nameof(CollateralTypeDto.Code)),
        ("NAME", nameof(CollateralTypeDto.Name)),
        ("IS_ACTIVE", nameof(CollateralTypeDto.IsActive)),
        ("ID", nameof(CollateralTypeDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CollateralTypeDto.Id))
    };
}