UPDATE [dbo].[CARDS]
SET
    [ACCOUNT_ID] = @PRM_CARD_ACCOUNT_ID,
    [CARD_NUMBER] = @PRM_CARD_CARD_NUMBER,
    [CARD_HOLDER_NAME] = @PRM_CARD_CARD_HOLDER_NAME,
    [CARD_TYPE_ID] = @PRM_CARD_CARD_TYPE_ID,
    [EXPIRY_MONTH] = @PRM_CARD_EXPIRY_MONTH,
    [EXPIRY_YEAR] = @PRM_CARD_EXPIRY_YEAR,
    [CVV] = @PRM_CARD_CVV,
    [STATUS] = @PRM_CARD_STATUS,
    [ACTIVATION_DATE] = @PRM_CARD_ACTIVATION_DATE,
    [IS_ACTIVE] = @PRM_CARD_IS_ACTIVE
WHERE
    [ID] = @PRM_CARD_ID
    AND [IsDeleted] = 0;