SELECT
    [ID],
    [ACCOUNT_ID],
    [CARD_NUMBER],
    [CARD_HOLDER_NAME],
    [CARD_TYPE_ID],
    [EXPIRY_MONTH],
    [EXPIRY_YEAR],
    [CVV],
    [STATUS],
    [ACTIVATION_DATE],
    [IS_ACTIVE]
FROM [dbo].[CARDS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;