INSERT INTO [dbo].[CARDS] (
    [ACCOUNT_ID],
    [CARD_NUMBER],
    [CARD_HOLDER_NAME],
    [CARD_TYPE_ID],
    [EXPIRY_MONTH],
    [EXPIRY_YEAR],
    [CVV],
    [STATUS],
    [ACTIVATION_DATE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CARD_ACCOUNT_ID,
    @PRM_CARD_CARD_NUMBER,
    @PRM_CARD_CARD_HOLDER_NAME,
    @PRM_CARD_CARD_TYPE_ID,
    @PRM_CARD_EXPIRY_MONTH,
    @PRM_CARD_EXPIRY_YEAR,
    @PRM_CARD_CVV,
    @PRM_CARD_STATUS,
    @PRM_CARD_ACTIVATION_DATE,
    @PRM_CARD_IS_ACTIVE
    );