UPDATE [dbo].[TRANSACTIONS]
SET
    [TRANSACTION_REFERENCE] = @PRM_TRANSACTION_TRANSACTION_REFERENCE,
    [SOURCE_ACCOUNT_ID] = @PRM_TRANSACTION_SOURCE_ACCOUNT_ID,
    [DESTINATION_ACCOUNT_ID] = @PRM_TRANSACTION_DESTINATION_ACCOUNT_ID,
    [TRANSACTION_TYPE_ID] = @PRM_TRANSACTION_TRANSACTION_TYPE_ID,
    [TRANSACTION_CHANNEL_ID] = @PRM_TRANSACTION_TRANSACTION_CHANNEL_ID,
    [AMOUNT] = @PRM_TRANSACTION_AMOUNT,
    [CURRENCY_CODE] = @PRM_TRANSACTION_CURRENCY_CODE,
    [DESCRIPTION] = @PRM_TRANSACTION_DESCRIPTION,
    [STATUS] = @PRM_TRANSACTION_STATUS,
    [TRANSACTION_DATE] = @PRM_TRANSACTION_TRANSACTION_DATE,
    [COMPLETED_DATE] = @PRM_TRANSACTION_COMPLETED_DATE
WHERE
    [ID] = @PRM_TRANSACTION_ID
    AND [IsDeleted] = 0;