SELECT
    [ID],
    [TRANSACTION_REFERENCE],
    [SOURCE_ACCOUNT_ID],
    [DESTINATION_ACCOUNT_ID],
    [TRANSACTION_TYPE_ID],
    [TRANSACTION_CHANNEL_ID],
    [AMOUNT],
    [CURRENCY_CODE],
    [DESCRIPTION],
    [STATUS],
    [TRANSACTION_DATE],
    [COMPLETED_DATE]
FROM [dbo].[TRANSACTIONS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;