SELECT
    [ID],
    [TRANSACTION_REFERENCE],
    [SOURCE_ACCOUNT_ID],
    [DESTINATION_ACCOUNT_ID],
    [TRANSACTION_TYPE_ID],
    [TRANSACTION_CHANNEL_ID],
    [AMOUNT],
    [CURRENCY_CODE],
    [DESCRIPTION],
    [STATUS],
    [TRANSACTION_DATE],
    [COMPLETED_DATE]
FROM [dbo].[TRANSACTIONS]
WHERE
    [ID] = @PRM_TRANSACTION_ID
    AND [IsDeleted] = 0;