INSERT INTO [dbo].[TRANSACTIONS] (
    [TRANSACTION_REFERENCE],
    [SOURCE_ACCOUNT_ID],
    [DESTINATION_ACCOUNT_ID],
    [TRANSACTION_TYPE_ID],
    [TRANSACTION_CHANNEL_ID],
    [AMOUNT],
    [CURRENCY_CODE],
    [DESCRIPTION],
    [STATUS],
    [TRANSACTION_DATE],
    [COMPLETED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TRANSACTION_TRANSACTION_REFERENCE,
    @PRM_TRANSACTION_SOURCE_ACCOUNT_ID,
    @PRM_TRANSACTION_DESTINATION_ACCOUNT_ID,
    @PRM_TRANSACTION_TRANSACTION_TYPE_ID,
    @PRM_TRANSACTION_TRANSACTION_CHANNEL_ID,
    @PRM_TRANSACTION_AMOUNT,
    @PRM_TRANSACTION_CURRENCY_CODE,
    @PRM_TRANSACTION_DESCRIPTION,
    @PRM_TRANSACTION_STATUS,
    @PRM_TRANSACTION_TRANSACTION_DATE,
    @PRM_TRANSACTION_COMPLETED_DATE
    );