//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.Currency;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories;
internal static class CurrencyCrudSqlBindings
{
    public const string StoreTableName = "CURRENCIES";
    public const string ParameterNamePrefix = "CURRENCY";
    public const string IdParameterName = "PRM_CURRENCY_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCode = "GetByCode";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CODE", nameof(CurrencyDto.Code)),
        ("NAME", nameof(CurrencyDto.Name)),
        ("SYMBOL", nameof(CurrencyDto.Symbol)),
        ("IS_ACTIVE", nameof(CurrencyDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CODE", nameof(CurrencyDto.Code)),
        ("NAME", nameof(CurrencyDto.Name)),
        ("SYMBOL", nameof(CurrencyDto.Symbol)),
        ("IS_ACTIVE", nameof(CurrencyDto.IsActive)),
        ("ID", nameof(CurrencyDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CurrencyDto.Id))
    };
}