SELECT AS.[ID], AS.[STATEMENT_PERIOD_START], AS.[STATEMENT_PERIOD_END], AS.[CLOSING_BALANCE] 
FROM [ACCOUNT_STATEMENTS] AS 
WHERE AS.[IsDeleted] = 0 
	AND AS.[ACCOUNT_ID] = @PRM_ACCOUNT_STATEMENT_ACCOUNT_ID 
	AND AS.[GENERATED_DATE] BETWEEN @PRM_ACCOUNT_STATEMENT_GENERATED_DATE_From 
	AND @PRM_ACCOUNT_STATEMENT_GENERATED_DATE_To 
ORDER BY AS.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 