SELECT AS.[ID], AS.[STATEMENT_PERIOD_START], AS.[STATEMENT_PERIOD_END], AS.[CLOSING_BALANCE], AS.[FORMAT] 
FROM [ACCOUNT_STATEMENTS] AS 
WHERE AS.[IsDeleted] = 0 
	AND AS.[ACCOUNT_ID] = @PRM_ACCOUNT_STATEMENT_ACCOUNT_ID 
ORDER BY AS.[STATEMENT_PERIOD_END] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 