//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.AuditLog;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories;
internal static class AuditLogCrudSqlBindings
{
    public const string StoreTableName = "AUDIT_LOGS";
    public const string ParameterNamePrefix = "AUDIT_LOG";
    public const string IdParameterName = "PRM_AUDIT_LOG_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("ID", nameof(AuditLogDto.Id)),
        ("ENTITY_NAME", nameof(AuditLogDto.EntityName)),
        ("ENTITY_ID", nameof(AuditLogDto.EntityId)),
        ("ACTION", nameof(AuditLogDto.Action)),
        ("USER_ID", nameof(AuditLogDto.UserId)),
        ("USER_NAME", nameof(AuditLogDto.UserName)),
        ("USER_GROUP", nameof(AuditLogDto.UserGroup)),
        ("TIMESTAMP", nameof(AuditLogDto.Timestamp)),
        ("OLD_VALUES", nameof(AuditLogDto.OldValues)),
        ("NEW_VALUES", nameof(AuditLogDto.NewValues)),
        ("CHANGED_COLUMNS", nameof(AuditLogDto.ChangedColumns)),
        ("IS_CHANGED", nameof(AuditLogDto.IsChanged)),
        ("CHANGE_SUMMARY", nameof(AuditLogDto.ChangeSummary)),
        ("IP_ADDRESS", nameof(AuditLogDto.IpAddress)),
        ("USER_AGENT", nameof(AuditLogDto.UserAgent)),
        ("CORRELATION_ID", nameof(AuditLogDto.CorrelationId)),
        ("IS_SUCCESS", nameof(AuditLogDto.IsSuccess)),
        ("ERROR_MESSAGE", nameof(AuditLogDto.ErrorMessage)),
        ("HASH", nameof(AuditLogDto.Hash))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("ENTITY_NAME", nameof(AuditLogDto.EntityName)),
        ("ENTITY_ID", nameof(AuditLogDto.EntityId)),
        ("ACTION", nameof(AuditLogDto.Action)),
        ("USER_ID", nameof(AuditLogDto.UserId)),
        ("USER_NAME", nameof(AuditLogDto.UserName)),
        ("USER_GROUP", nameof(AuditLogDto.UserGroup)),
        ("TIMESTAMP", nameof(AuditLogDto.Timestamp)),
        ("OLD_VALUES", nameof(AuditLogDto.OldValues)),
        ("NEW_VALUES", nameof(AuditLogDto.NewValues)),
        ("CHANGED_COLUMNS", nameof(AuditLogDto.ChangedColumns)),
        ("IS_CHANGED", nameof(AuditLogDto.IsChanged)),
        ("CHANGE_SUMMARY", nameof(AuditLogDto.ChangeSummary)),
        ("IP_ADDRESS", nameof(AuditLogDto.IpAddress)),
        ("USER_AGENT", nameof(AuditLogDto.UserAgent)),
        ("CORRELATION_ID", nameof(AuditLogDto.CorrelationId)),
        ("IS_SUCCESS", nameof(AuditLogDto.IsSuccess)),
        ("ERROR_MESSAGE", nameof(AuditLogDto.ErrorMessage)),
        ("HASH", nameof(AuditLogDto.Hash)),
        ("ID", nameof(AuditLogDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(AuditLogDto.Id))
    };
}