//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanPayment;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories
{
    public partial interface ILoanPaymentRepository : IBaseRepository<LoanPaymentDto>
    {
        Task<RepoResponse<LoanPaymentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByLoanIdResponseDto>>> GetByLoanIdAsync(int loanPaymentLoanId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(int loanPaymentLoanId, DateTime loanPaymentPaymentDateFrom, DateTime loanPaymentPaymentDateTo, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetTotalPaymentsForLoanAsync(int loanPaymentLoanId);
    }
}