//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanProduct;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories
{
    public partial interface ILoanProductRepository : IBaseRepository<LoanProductDto>
    {
        Task<RepoResponse<LoanProductDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool loanProductIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByCodeResponseDto>> GetByCodeAsync(string loanProductCode);
        Task<RepoResponse<int>> UpdateInterestRateAsync(int loanProductId, UpdateInterestRateRequestDto updateRequest);
        Task<RepoResponse<int>> DeactivateAsync(int loanProductId, DeactivateRequestDto updateRequest);
    }
}