//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanApplication;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories
{
    public partial interface ILoanApplicationRepository : IBaseRepository<LoanApplicationDto>
    {
        Task<RepoResponse<LoanApplicationDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByApplicationNumberResponseDto>> GetByApplicationNumberAsync(Guid loanApplicationApplicationNumber);
        Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int loanApplicationCustomerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPendingReviewResponseDto>>> GetPendingReviewAsync(LoanApplicationStatus loanApplicationStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetApplicationsWithProductResponseDto>>> GetApplicationsWithProductAsync(int loanApplicationsCustomerId, int loanApplicationsLoanProductId, int loanProductsId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> SubmitApplicationAsync(int loanApplicationId, SubmitApplicationRequestDto updateRequest);
        Task<RepoResponse<int>> ApproveApplicationAsync(int loanApplicationId, ApproveApplicationRequestDto updateRequest);
        Task<RepoResponse<int>> RejectApplicationAsync(int loanApplicationId, RejectApplicationRequestDto updateRequest);
        Task<RepoResponse<int>> WithdrawApplicationAsync(int loanApplicationId, WithdrawApplicationRequestDto updateRequest);
    }
}