//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.Loan;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories
{
    public partial interface ILoanRepository : IBaseRepository<LoanDto>
    {
        Task<RepoResponse<LoanDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByAccountNumberResponseDto>> GetByAccountNumberAsync(string loanLoanAccountNumber);
        Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int loanCustomerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetActiveLoansResponseDto>>> GetActiveLoansAsync(LoanStatus loanStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetDefaultedLoansResponseDto>>> GetDefaultedLoansAsync(LoanStatus loanStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetTotalOutstandingLoansAsync(LoanStatus loanStatus);
        Task<RepoResponse<int>> UpdateOutstandingBalanceAsync(int loanId, UpdateOutstandingBalanceRequestDto updateRequest);
        Task<RepoResponse<int>> MarkAsPaidOffAsync(int loanId, MarkAsPaidOffRequestDto updateRequest);
        Task<RepoResponse<int>> MarkAsDefaultedAsync(int loanId, MarkAsDefaultedRequestDto updateRequest);
    }
}