//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.RepaymentSchedule;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories
{
    public partial interface IRepaymentScheduleRepository : IBaseRepository<RepaymentScheduleDto>
    {
        Task<RepoResponse<RepaymentScheduleDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByLoanIdResponseDto>>> GetByLoanIdAsync(int repaymentScheduleLoanId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetUpcomingPaymentsResponseDto>>> GetUpcomingPaymentsAsync(int repaymentScheduleLoanId, PaymentStatus repaymentScheduleStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetOverduePaymentsResponseDto>>> GetOverduePaymentsAsync(int repaymentScheduleLoanId, PaymentStatus repaymentScheduleStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> MarkAsPaidAsync(int repaymentScheduleId, MarkAsPaidRequestDto updateRequest);
    }
}