//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.Address;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories
{
    public partial class AddressRepository : BaseRepository, IAddressRepository
    {
        public async Task<RepoResponse<int>> SetAsPrimaryAsync(int addressId, int addressCustomerId, SetAsPrimaryRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.SetAsPrimary, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Command.SetAsPrimary);
                var parameters = new
                {
                    PRM_ADDRESS_ID = addressId,
                    PRM_ADDRESS_CUSTOMER_ID = addressCustomerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UnsetPrimaryAsync(int addressCustomerId, UnsetPrimaryRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.UnsetPrimary, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Command.UnsetPrimary);
                var parameters = new
                {
                    PRM_ADDRESS_CUSTOMER_ID = addressCustomerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> RemoveAddressAsync(int addressId, int addressCustomerId)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.RemoveAddress, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Command.RemoveAddress);
                var parameters = new
                {
                    PRM_ADDRESS_ID = addressId,
                    PRM_ADDRESS_CUSTOMER_ID = addressCustomerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}