//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
// Runtime Version:1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QcEntity = global::QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Data;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.Address;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories
{
    public partial class AddressRepository : BaseRepository, IAddressRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public AddressRepository(ILogger<AddressRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "Address")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<AddressDto>> InsertAsync(AddressDto value)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(AddressCrudSqlBindings.ParameterNamePrefix, value, AddressCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.Address>(sql, p);
                return new RepoResponse<AddressDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(AddressDto value)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(AddressCrudSqlBindings.ParameterNamePrefix, value, AddressCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(AddressDto value)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(AddressCrudSqlBindings.ParameterNamePrefix, value, AddressCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<AddressDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(AddressCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.Address>(sql, p);
                return row == null ? CreateNotFoundResponse<AddressDto>("Not found in Address") : new RepoResponse<AddressDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<AddressDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<AddressDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.Address.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.Address>(sql, p);
                return new RepoResponse<List<AddressDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(AddressCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Address.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}