//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.Address;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories;
internal static class AddressCrudSqlBindings
{
    public const string StoreTableName = "ADDRESSES";
    public const string ParameterNamePrefix = "ADDRESS";
    public const string IdParameterName = "PRM_ADDRESS_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByCustomerId = "GetByCustomerId";
        public const string GetByPk = "GetByPk";
        public const string GetPrimaryByCustomerId = "GetPrimaryByCustomerId";
        public const string Insert = "Insert";
        public const string RemoveAddress = "RemoveAddress";
        public const string Select = "Select";
        public const string SetAsPrimary = "SetAsPrimary";
        public const string UnsetPrimary = "UnsetPrimary";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CUSTOMER_ID", nameof(AddressDto.CustomerId)),
        ("ADDRESS_LINE_1", nameof(AddressDto.AddressLine1)),
        ("ADDRESS_LINE_2", nameof(AddressDto.AddressLine2)),
        ("CITY", nameof(AddressDto.City)),
        ("STATE", nameof(AddressDto.State)),
        ("POSTAL_CODE", nameof(AddressDto.PostalCode)),
        ("COUNTRY_CODE", nameof(AddressDto.CountryCode)),
        ("TYPE", nameof(AddressDto.Type)),
        ("IS_PRIMARY", nameof(AddressDto.IsPrimary))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CUSTOMER_ID", nameof(AddressDto.CustomerId)),
        ("ADDRESS_LINE_1", nameof(AddressDto.AddressLine1)),
        ("ADDRESS_LINE_2", nameof(AddressDto.AddressLine2)),
        ("CITY", nameof(AddressDto.City)),
        ("STATE", nameof(AddressDto.State)),
        ("POSTAL_CODE", nameof(AddressDto.PostalCode)),
        ("COUNTRY_CODE", nameof(AddressDto.CountryCode)),
        ("TYPE", nameof(AddressDto.Type)),
        ("IS_PRIMARY", nameof(AddressDto.IsPrimary)),
        ("ID", nameof(AddressDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(AddressDto.Id))
    };
}