//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.FeeType;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Mappings;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Sql;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Repositories
{
    public partial class FeeTypeRepository : BaseRepository, IFeeTypeRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool feeTypeIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(FeeTypeCrudSqlBindings.OperationNames.GetActive, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.FeeType.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_FEE_TYPE_IS_ACTIVE = feeTypeIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in FeeType");
                }
            });
        }

        public async Task<RepoResponse<GetByCodeResponseDto>> GetByCodeAsync(string feeTypeCode)
        {
            return await ExecuteWithExceptionHandling(FeeTypeCrudSqlBindings.OperationNames.GetByCode, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FeeType.Query.GetByCode);
                var parameters = new
                {
                    PRM_FEE_TYPE_CODE = feeTypeCode
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByCodeResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in FeeType");
            });
        }
    }
}