//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.AspNetUser;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IAspNetUserRepository : IBaseRepository<AspNetUserDto>
    {
        Task<RepoResponse<AspNetUserDto>> GetByPkAsync(string id);
        Task<RepoResponse<GetUserResponseDto>> GetUserAsync(string? aspNetUserEmail);
        Task<RepoResponse<List<IdentityUserByIdResponseDto>>> IdentityUserByIdAsync(string aspNetUserId);
        Task<RepoResponse<List<IdentityUserByNormalizedEmailResponseDto>>> IdentityUserByNormalizedEmailAsync(string? aspNetUserNormalizedEmail);
        Task<RepoResponse<List<IdentityUserByNormalizedUsernameResponseDto>>> IdentityUserByNormalizedUsernameAsync(string? aspNetUserNormalizedUserName);
    }
}