//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.CustomerType;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories;
internal static class CustomerTypeCrudSqlBindings
{
    public const string StoreTableName = "CUSTOMER_TYPES";
    public const string ParameterNamePrefix = "CUSTOMER_TYPE";
    public const string IdParameterName = "PRM_CUSTOMER_TYPE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCode = "GetByCode";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CODE", nameof(CustomerTypeDto.Code)),
        ("NAME", nameof(CustomerTypeDto.Name)),
        ("DESCRIPTION", nameof(CustomerTypeDto.Description)),
        ("IS_ACTIVE", nameof(CustomerTypeDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CODE", nameof(CustomerTypeDto.Code)),
        ("NAME", nameof(CustomerTypeDto.Name)),
        ("DESCRIPTION", nameof(CustomerTypeDto.Description)),
        ("IS_ACTIVE", nameof(CustomerTypeDto.IsActive)),
        ("ID", nameof(CustomerTypeDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CustomerTypeDto.Id))
    };
}