SELECT C.[ID], C.[CARD_NUMBER], C.[CARD_HOLDER_NAME], C.[STATUS] 
FROM [CARDS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[ACCOUNT_ID] = @PRM_CARD_ACCOUNT_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 