SELECT C.[ID], C.[CARD_NUMBER], CT.[NAME] AS CARD_TYPE_NAME,
	C.[STATUS] 
FROM [CARDS] C 
	INNER JOIN [CARD_TYPES] CT 
			ON C.[CARD_TYPE_ID] = CT.[ID] 
WHERE C.[IsDeleted] = 0 
	AND CT.[IsDeleted] = 0 
	AND C.[ACCOUNT_ID] = @PRM_CARDS_ACCOUNT_ID 
	AND C.[CARD_TYPE_ID] = @PRM_CARDS_CARD_TYPE_ID 
	AND CT.[ID] = @PRM_CARD_TYPES_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 