SELECT ID.[ID], ID.[DOCUMENT_TYPE_ID], ID.[DOCUMENT_NUMBER], ID.[EXPIRY_DATE], ID.[STATUS] 
FROM [IDENTIFICATION_DOCUMENTS] ID 
WHERE ID.[IsDeleted] = 0 
	AND ID.[CUSTOMER_ID] = @PRM_IDENTIFICATION_DOCUMENT_CUSTOMER_ID 
ORDER BY ID.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 