SELECT ID.[ID], DT.[NAME] AS DOCUMENT_TYPE,
	ID.[DOCUMENT_NUMBER], ID.[EXPIRY_DATE], ID.[STATUS] 
FROM [IDENTIFICATION_DOCUMENTS] ID 
	INNER JOIN [DOCUMENT_TYPES] DT 
			ON ID.[DOCUMENT_TYPE_ID] = DT.[ID] 
WHERE ID.[IsDeleted] = 0 
	AND DT.[IsDeleted] = 0 
	AND ID.[CUSTOMER_ID] = @PRM_IDENTIFICATION_DOCUMENTS_CUSTOMER_ID 
	AND ID.[DOCUMENT_TYPE_ID] = @PRM_IDENTIFICATION_DOCUMENTS_DOCUMENT_TYPE_ID 
	AND DT.[ID] = @PRM_DOCUMENT_TYPES_ID 
ORDER BY ID.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 