SELECT ID.[ID], ID.[CUSTOMER_ID], ID.[DOCUMENT_NUMBER], ID.[EXPIRY_DATE] 
FROM [IDENTIFICATION_DOCUMENTS] ID 
WHERE ID.[IsDeleted] = 0 
	AND ID.[EXPIRY_DATE] < DATEADD(DAY,
	30,
	GETDATE()) 
	AND ID.[STATUS] = @PRM_IDENTIFICATION_DOCUMENT_STATUS 
ORDER BY ID.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 