IF OBJECT_ID(N'dbo.ACCOUNT_HOLDERS', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ACCOUNT_HOLDERS] (
        [ACCOUNT_ID] int NOT NULL,
        [CUSTOMER_ID] int NOT NULL,
        [ROLE] nvarchar(50) NOT NULL,
        CONSTRAINT [PK_ACCOUNT_HOLDERS] PRIMARY KEY ([ACCOUNT_ID], [CUSTOMER_ID])
    );
END;