IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNT_STATEMENTS_ACCOUNTS_ACCOUNT_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNT_STATEMENTS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNT_STATEMENTS] ADD CONSTRAINT [FK_ACCOUNT_STATEMENTS_ACCOUNTS_ACCOUNT_ID] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNTS] ([ID]);
END