IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNTS_ACCOUNT_TYPES_ACCOUNT_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNTS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_ACCOUNT_TYPES_ACCOUNT_TYPE_ID] FOREIGN KEY ([ACCOUNT_TYPE_ID]) REFERENCES [dbo].[ACCOUNT_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNTS_CURRENCIES_CURRENCY_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNTS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_CURRENCIES_CURRENCY_ID] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNT_HOLDERS_ACCOUNTS_ACCOUNT_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNT_HOLDERS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNT_HOLDERS] ADD CONSTRAINT [FK_ACCOUNT_HOLDERS_ACCOUNTS_ACCOUNT_ID] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNT_STATEMENTS_ACCOUNTS_ACCOUNT_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNT_STATEMENTS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNT_STATEMENTS] ADD CONSTRAINT [FK_ACCOUNT_STATEMENTS_ACCOUNTS_ACCOUNT_ID] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CARDS_ACCOUNTS_ACCOUNT_ID' AND parent_object_id = OBJECT_ID(N'dbo.CARDS'))
BEGIN
    ALTER TABLE [dbo].[CARDS] ADD CONSTRAINT [FK_CARDS_ACCOUNTS_ACCOUNT_ID] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CARDS_CARD_TYPES_CARD_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CARDS'))
BEGIN
    ALTER TABLE [dbo].[CARDS] ADD CONSTRAINT [FK_CARDS_CARD_TYPES_CARD_TYPE_ID] FOREIGN KEY ([CARD_TYPE_ID]) REFERENCES [dbo].[CARD_TYPES] ([ID]);
END