IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNT_HOLDERS_ACCOUNTS_ACCOUNT_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNT_HOLDERS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNT_HOLDERS] ADD CONSTRAINT [FK_ACCOUNT_HOLDERS_ACCOUNTS_ACCOUNT_ID] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNTS] ([ID]);
END