IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CARDS_ACCOUNTS_ACCOUNT_ID' AND parent_object_id = OBJECT_ID(N'dbo.CARDS'))
BEGIN
    ALTER TABLE [dbo].[CARDS] ADD CONSTRAINT [FK_CARDS_ACCOUNTS_ACCOUNT_ID] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CARDS_CARD_TYPES_CARD_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CARDS'))
BEGIN
    ALTER TABLE [dbo].[CARDS] ADD CONSTRAINT [FK_CARDS_CARD_TYPES_CARD_TYPE_ID] FOREIGN KEY ([CARD_TYPE_ID]) REFERENCES [dbo].[CARD_TYPES] ([ID]);
END