IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNTS_ACCOUNT_TYPES_ACCOUNT_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNTS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_ACCOUNT_TYPES_ACCOUNT_TYPE_ID] FOREIGN KEY ([ACCOUNT_TYPE_ID]) REFERENCES [dbo].[ACCOUNT_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ACCOUNTS_CURRENCIES_CURRENCY_ID' AND parent_object_id = OBJECT_ID(N'dbo.ACCOUNTS'))
BEGIN
    ALTER TABLE [dbo].[ACCOUNTS] ADD CONSTRAINT [FK_ACCOUNTS_CURRENCIES_CURRENCY_ID] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCIES] ([ID]);
END