SELECT DT.[ID], DT.[CODE], DT.[NAME] 
FROM [DOCUMENT_TYPES] DT 
WHERE DT.[IsDeleted] = 0 
	AND DT.[IS_ACTIVE] = @PRM_DOCUMENT_TYPE_IS_ACTIVE 
ORDER BY DT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 