INSERT INTO [dbo].[CUSTOMER_TYPES] (
    [CODE],
    [NAME],
    [DESCRIPTION],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CUSTOMER_TYPE_CODE,
    @PRM_CUSTOMER_TYPE_NAME,
    @PRM_CUSTOMER_TYPE_DESCRIPTION,
    @PRM_CUSTOMER_TYPE_IS_ACTIVE
    );