UPDATE [dbo].[CUSTOMER_TYPES]
SET
    [CODE] = @PRM_CUSTOMER_TYPE_CODE,
    [NAME] = @PRM_CUSTOMER_TYPE_NAME,
    [DESCRIPTION] = @PRM_CUSTOMER_TYPE_DESCRIPTION,
    [IS_ACTIVE] = @PRM_CUSTOMER_TYPE_IS_ACTIVE
WHERE
    [ID] = @PRM_CUSTOMER_TYPE_ID
    AND [IsDeleted] = 0;