UPDATE [dbo].[PortalPageAccessGrants]
SET
    [ModifiedBy] = @PRM_PORTAL_PAGE_ACCESS_GRANT_MODIFIED_BY,
    [IsActive] = @PRM_PORTAL_PAGE_ACCESS_GRANT_IS_ACTIVE
WHERE
    [PermissionGroupName] = @PRM_PORTAL_PAGE_ACCESS_GRANT_PERMISSION_GROUP_NAME AND
    [PortalPageDefinitionKey] = @PRM_PORTAL_PAGE_ACCESS_GRANT_PORTAL_PAGE_DEFINITION_KEY AND
    [PageAction] = @PRM_PORTAL_PAGE_ACCESS_GRANT_PAGE_ACTION;