INSERT INTO [dbo].[PortalPageAccessGrants] (
    [PermissionGroupName],
    [PortalPageDefinitionKey],
    [PageAction],
    [ModifiedBy],
    [IsActive]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PORTAL_PAGE_ACCESS_GRANT_PERMISSION_GROUP_NAME,
    @PRM_PORTAL_PAGE_ACCESS_GRANT_PORTAL_PAGE_DEFINITION_KEY,
    @PRM_PORTAL_PAGE_ACCESS_GRANT_PAGE_ACTION,
    @PRM_PORTAL_PAGE_ACCESS_GRANT_MODIFIED_BY,
    @PRM_PORTAL_PAGE_ACCESS_GRANT_IS_ACTIVE
    );