UPDATE [dbo].[FEE_TYPES]
SET
    [CODE] = @PRM_FEE_TYPE_CODE,
    [NAME] = @PRM_FEE_TYPE_NAME,
    [FIXED_AMOUNT] = @PRM_FEE_TYPE_FIXED_AMOUNT,
    [PERCENTAGE_RATE] = @PRM_FEE_TYPE_PERCENTAGE_RATE,
    [IS_ACTIVE] = @PRM_FEE_TYPE_IS_ACTIVE
WHERE
    [ID] = @PRM_FEE_TYPE_ID
    AND [IsDeleted] = 0;