INSERT INTO [dbo].[FEE_TYPES] (
    [CODE],
    [NAME],
    [FIXED_AMOUNT],
    [PERCENTAGE_RATE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_FEE_TYPE_CODE,
    @PRM_FEE_TYPE_NAME,
    @PRM_FEE_TYPE_FIXED_AMOUNT,
    @PRM_FEE_TYPE_PERCENTAGE_RATE,
    @PRM_FEE_TYPE_IS_ACTIVE
    );