SELECT
    [ID],
    [CODE],
    [NAME],
    [FIXED_AMOUNT],
    [PERCENTAGE_RATE],
    [IS_ACTIVE]
FROM [dbo].[FEE_TYPES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;