SELECT L.[ID], L.[LOAN_ACCOUNT_NUMBER], L.[PRINCIPAL_AMOUNT], L.[OUTSTANDING_BALANCE], L.[STATUS] 
FROM [LOANS] L 
WHERE L.[IsDeleted] = 0 
	AND L.[CUSTOMER_ID] = @PRM_LOAN_CUSTOMER_ID 
ORDER BY L.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 