SELECT L.[ID], L.[LOAN_ACCOUNT_NUMBER], L.[CUSTOMER_ID], L.[OUTSTANDING_BALANCE] 
FROM [LOANS] L 
WHERE L.[IsDeleted] = 0 
	AND L.[STATUS] = @PRM_LOAN_STATUS 
ORDER BY L.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 