SELECT TOP 1 L.[ID], L.[LOAN_ACCOUNT_NUMBER], L.[CUSTOMER_ID], L.[OUTSTANDING_BALANCE], L.[STATUS] 
FROM [LOANS] L 
WHERE L.[IsDeleted] = 0 
	AND L.[LOAN_ACCOUNT_NUMBER] = @PRM_LOAN_LOAN_ACCOUNT_NUMBER 
ORDER BY L.[ID] 