INSERT INTO [dbo].[IDENTIFICATION_DOCUMENTS] (
    [CUSTOMER_ID],
    [DOCUMENT_TYPE_ID],
    [DOCUMENT_NUMBER],
    [ISSUE_DATE],
    [EXPIRY_DATE],
    [ISSUING_COUNTRY],
    [DOCUMENT_URL],
    [STATUS]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_IDENTIFICATION_DOCUMENT_CUSTOMER_ID,
    @PRM_IDENTIFICATION_DOCUMENT_DOCUMENT_TYPE_ID,
    @PRM_IDENTIFICATION_DOCUMENT_DOCUMENT_NUMBER,
    @PRM_IDENTIFICATION_DOCUMENT_ISSUE_DATE,
    @PRM_IDENTIFICATION_DOCUMENT_EXPIRY_DATE,
    @PRM_IDENTIFICATION_DOCUMENT_ISSUING_COUNTRY,
    @PRM_IDENTIFICATION_DOCUMENT_DOCUMENT_URL,
    @PRM_IDENTIFICATION_DOCUMENT_STATUS
    );