SELECT
    [ID],
    [CUSTOMER_ID],
    [DOCUMENT_TYPE_ID],
    [DOCUMENT_NUMBER],
    [ISSUE_DATE],
    [EXPIRY_DATE],
    [ISSUING_COUNTRY],
    [DOCUMENT_URL],
    [STATUS]
FROM [dbo].[IDENTIFICATION_DOCUMENTS]
WHERE
    [ID] = @PRM_IDENTIFICATION_DOCUMENT_ID
    AND [IsDeleted] = 0;