UPDATE [dbo].[IDENTIFICATION_DOCUMENTS]
SET
    [CUSTOMER_ID] = @PRM_IDENTIFICATION_DOCUMENT_CUSTOMER_ID,
    [DOCUMENT_TYPE_ID] = @PRM_IDENTIFICATION_DOCUMENT_DOCUMENT_TYPE_ID,
    [DOCUMENT_NUMBER] = @PRM_IDENTIFICATION_DOCUMENT_DOCUMENT_NUMBER,
    [ISSUE_DATE] = @PRM_IDENTIFICATION_DOCUMENT_ISSUE_DATE,
    [EXPIRY_DATE] = @PRM_IDENTIFICATION_DOCUMENT_EXPIRY_DATE,
    [ISSUING_COUNTRY] = @PRM_IDENTIFICATION_DOCUMENT_ISSUING_COUNTRY,
    [DOCUMENT_URL] = @PRM_IDENTIFICATION_DOCUMENT_DOCUMENT_URL,
    [STATUS] = @PRM_IDENTIFICATION_DOCUMENT_STATUS
WHERE
    [ID] = @PRM_IDENTIFICATION_DOCUMENT_ID
    AND [IsDeleted] = 0;