SELECT
    [ID],
    [CUSTOMER_ID],
    [DOCUMENT_TYPE_ID],
    [DOCUMENT_NUMBER],
    [ISSUE_DATE],
    [EXPIRY_DATE],
    [ISSUING_COUNTRY],
    [DOCUMENT_URL],
    [STATUS]
FROM [dbo].[IDENTIFICATION_DOCUMENTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;