IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ADDRESSES_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.ADDRESSES'))
BEGIN
    ALTER TABLE [dbo].[ADDRESSES] ADD CONSTRAINT [FK_ADDRESSES_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END