IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CONTACT_DETAILS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CONTACT_DETAILS'))
BEGIN
    ALTER TABLE [dbo].[CONTACT_DETAILS] ADD CONSTRAINT [FK_CONTACT_DETAILS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END