IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMERS_CUSTOMER_TYPES_CUSTOMER_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMERS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMERS] ADD CONSTRAINT [FK_CUSTOMERS_CUSTOMER_TYPES_CUSTOMER_TYPE_ID] FOREIGN KEY ([CUSTOMER_TYPE_ID]) REFERENCES [dbo].[CUSTOMER_TYPES] ([ID]);
END