IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ADDRESSES_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.ADDRESSES'))
BEGIN
    ALTER TABLE [dbo].[ADDRESSES] ADD CONSTRAINT [FK_ADDRESSES_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CONTACT_DETAILS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CONTACT_DETAILS'))
BEGIN
    ALTER TABLE [dbo].[CONTACT_DETAILS] ADD CONSTRAINT [FK_CONTACT_DETAILS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMERS_CUSTOMER_TYPES_CUSTOMER_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMERS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMERS] ADD CONSTRAINT [FK_CUSTOMERS_CUSTOMER_TYPES_CUSTOMER_TYPE_ID] FOREIGN KEY ([CUSTOMER_TYPE_ID]) REFERENCES [dbo].[CUSTOMER_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_PRIMARY_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMER_RELATIONSHIPS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMER_RELATIONSHIPS] ADD CONSTRAINT [FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_PRIMARY_CUSTOMER_ID] FOREIGN KEY ([PRIMARY_CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_RELATED_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMER_RELATIONSHIPS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMER_RELATIONSHIPS] ADD CONSTRAINT [FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_RELATED_CUSTOMER_ID] FOREIGN KEY ([RELATED_CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_IDENTIFICATION_DOCUMENTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.IDENTIFICATION_DOCUMENTS'))
BEGIN
    ALTER TABLE [dbo].[IDENTIFICATION_DOCUMENTS] ADD CONSTRAINT [FK_IDENTIFICATION_DOCUMENTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_IDENTIFICATION_DOCUMENTS_DOCUMENT_TYPES_DOCUMENT_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.IDENTIFICATION_DOCUMENTS'))
BEGIN
    ALTER TABLE [dbo].[IDENTIFICATION_DOCUMENTS] ADD CONSTRAINT [FK_IDENTIFICATION_DOCUMENTS_DOCUMENT_TYPES_DOCUMENT_TYPE_ID] FOREIGN KEY ([DOCUMENT_TYPE_ID]) REFERENCES [dbo].[DOCUMENT_TYPES] ([ID]);
END