IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_PRIMARY_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMER_RELATIONSHIPS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMER_RELATIONSHIPS] ADD CONSTRAINT [FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_PRIMARY_CUSTOMER_ID] FOREIGN KEY ([PRIMARY_CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_RELATED_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.CUSTOMER_RELATIONSHIPS'))
BEGIN
    ALTER TABLE [dbo].[CUSTOMER_RELATIONSHIPS] ADD CONSTRAINT [FK_CUSTOMER_RELATIONSHIPS_CUSTOMERS_RELATED_CUSTOMER_ID] FOREIGN KEY ([RELATED_CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END