IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_IDENTIFICATION_DOCUMENTS_CUSTOMERS_CUSTOMER_ID' AND parent_object_id = OBJECT_ID(N'dbo.IDENTIFICATION_DOCUMENTS'))
BEGIN
    ALTER TABLE [dbo].[IDENTIFICATION_DOCUMENTS] ADD CONSTRAINT [FK_IDENTIFICATION_DOCUMENTS_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_IDENTIFICATION_DOCUMENTS_DOCUMENT_TYPES_DOCUMENT_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.IDENTIFICATION_DOCUMENTS'))
BEGIN
    ALTER TABLE [dbo].[IDENTIFICATION_DOCUMENTS] ADD CONSTRAINT [FK_IDENTIFICATION_DOCUMENTS_DOCUMENT_TYPES_DOCUMENT_TYPE_ID] FOREIGN KEY ([DOCUMENT_TYPE_ID]) REFERENCES [dbo].[DOCUMENT_TYPES] ([ID]);
END