IF OBJECT_ID(N'dbo.CUSTOMER_RELATIONSHIPS', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[CUSTOMER_RELATIONSHIPS] (
        [ID] int IDENTITY(1,1) NOT NULL,
        [PRIMARY_CUSTOMER_ID] int NOT NULL,
        [RELATED_CUSTOMER_ID] int NOT NULL,
        [RELATIONSHIP_TYPE] nvarchar(50) NOT NULL,
        [CREATED_DATE] datetime2(7) NOT NULL,
        [IsDeleted] bit NOT NULL DEFAULT 0,
        [DeletedOnUtc] datetime2(7) NULL,
        CONSTRAINT [PK_CUSTOMER_RELATIONSHIPS] PRIMARY KEY ([ID])
    );
END;