// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Contexts;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20811231999990_BaseData")]
    partial class BaseData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
