SELECT C.[ID], CT.[NAME] AS COLLATERAL_TYPE,
	C.[DESCRIPTION], C.[MARKET_VALUE] 
FROM [COLLATERALS] C 
	INNER JOIN [COLLATERAL_TYPES] CT 
			ON C.[COLLATERAL_TYPE_ID] = CT.[ID] 
WHERE C.[IsDeleted] = 0 
	AND CT.[IsDeleted] = 0 
	AND C.[LOAN_APPLICATION_ID] = @PRM_COLLATERALS_LOAN_APPLICATION_ID 
	AND C.[COLLATERAL_TYPE_ID] = @PRM_COLLATERALS_COLLATERAL_TYPE_ID 
	AND CT.[ID] = @PRM_COLLATERAL_TYPES_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 