SELECT C.[ID], C.[COLLATERAL_TYPE_ID], C.[DESCRIPTION], C.[MARKET_VALUE] 
FROM [COLLATERALS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[LOAN_APPLICATION_ID] = @PRM_COLLATERAL_LOAN_APPLICATION_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 