UPDATE [dbo].[REPAYMENT_SCHEDULES]
SET
    [LOAN_ID] = @PRM_REPAYMENT_SCHEDULE_LOAN_ID,
    [INSTALLMENT_NUMBER] = @PRM_REPAYMENT_SCHEDULE_INSTALLMENT_NUMBER,
    [DUE_DATE] = @PRM_REPAYMENT_SCHEDULE_DUE_DATE,
    [PRINCIPAL_AMOUNT] = @PRM_REPAYMENT_SCHEDULE_PRINCIPAL_AMOUNT,
    [INTEREST_AMOUNT] = @PRM_REPAYMENT_SCHEDULE_INTEREST_AMOUNT,
    [TOTAL_AMOUNT] = @PRM_REPAYMENT_SCHEDULE_TOTAL_AMOUNT,
    [STATUS] = @PRM_REPAYMENT_SCHEDULE_STATUS
WHERE
    [ID] = @PRM_REPAYMENT_SCHEDULE_ID
    AND [IsDeleted] = 0;