SELECT
    [ID],
    [LOAN_ID],
    [INSTALLMENT_NUMBER],
    [DUE_DATE],
    [PRINCIPAL_AMOUNT],
    [INTEREST_AMOUNT],
    [TOTAL_AMOUNT],
    [STATUS]
FROM [dbo].[REPAYMENT_SCHEDULES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;