INSERT INTO [dbo].[REPAYMENT_SCHEDULES] (
    [LOAN_ID],
    [INSTALLMENT_NUMBER],
    [DUE_DATE],
    [PRINCIPAL_AMOUNT],
    [INTEREST_AMOUNT],
    [TOTAL_AMOUNT],
    [STATUS]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_REPAYMENT_SCHEDULE_LOAN_ID,
    @PRM_REPAYMENT_SCHEDULE_INSTALLMENT_NUMBER,
    @PRM_REPAYMENT_SCHEDULE_DUE_DATE,
    @PRM_REPAYMENT_SCHEDULE_PRINCIPAL_AMOUNT,
    @PRM_REPAYMENT_SCHEDULE_INTEREST_AMOUNT,
    @PRM_REPAYMENT_SCHEDULE_TOTAL_AMOUNT,
    @PRM_REPAYMENT_SCHEDULE_STATUS
    );