SELECT
    [ID],
    [LOAN_ID],
    [INSTALLMENT_NUMBER],
    [DUE_DATE],
    [PRINCIPAL_AMOUNT],
    [INTEREST_AMOUNT],
    [TOTAL_AMOUNT],
    [STATUS]
FROM [dbo].[REPAYMENT_SCHEDULES]
WHERE
    [ID] = @PRM_REPAYMENT_SCHEDULE_ID
    AND [IsDeleted] = 0;