INSERT INTO [dbo].[CURRENCIES] (
    [CODE],
    [NAME],
    [SYMBOL],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CURRENCY_CODE,
    @PRM_CURRENCY_NAME,
    @PRM_CURRENCY_SYMBOL,
    @PRM_CURRENCY_IS_ACTIVE
    );