UPDATE [dbo].[CURRENCIES]
SET
    [CODE] = @PRM_CURRENCY_CODE,
    [NAME] = @PRM_CURRENCY_NAME,
    [SYMBOL] = @PRM_CURRENCY_SYMBOL,
    [IS_ACTIVE] = @PRM_CURRENCY_IS_ACTIVE
WHERE
    [ID] = @PRM_CURRENCY_ID
    AND [IsDeleted] = 0;