INSERT INTO [dbo].[COLLATERALS] (
    [LOAN_APPLICATION_ID],
    [COLLATERAL_TYPE_ID],
    [DESCRIPTION],
    [MARKET_VALUE],
    [VALUATION_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_COLLATERAL_LOAN_APPLICATION_ID,
    @PRM_COLLATERAL_COLLATERAL_TYPE_ID,
    @PRM_COLLATERAL_DESCRIPTION,
    @PRM_COLLATERAL_MARKET_VALUE,
    @PRM_COLLATERAL_VALUATION_DATE
    );