SELECT
    [ID],
    [LOAN_APPLICATION_ID],
    [COLLATERAL_TYPE_ID],
    [DESCRIPTION],
    [MARKET_VALUE],
    [VALUATION_DATE]
FROM [dbo].[COLLATERALS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;