SELECT
    [ID],
    [LOAN_APPLICATION_ID],
    [COLLATERAL_TYPE_ID],
    [DESCRIPTION],
    [MARKET_VALUE],
    [VALUATION_DATE]
FROM [dbo].[COLLATERALS]
WHERE
    [ID] = @PRM_COLLATERAL_ID
    AND [IsDeleted] = 0;