UPDATE [dbo].[COLLATERALS]
SET
    [LOAN_APPLICATION_ID] = @PRM_COLLATERAL_LOAN_APPLICATION_ID,
    [COLLATERAL_TYPE_ID] = @PRM_COLLATERAL_COLLATERAL_TYPE_ID,
    [DESCRIPTION] = @PRM_COLLATERAL_DESCRIPTION,
    [MARKET_VALUE] = @PRM_COLLATERAL_MARKET_VALUE,
    [VALUATION_DATE] = @PRM_COLLATERAL_VALUATION_DATE
WHERE
    [ID] = @PRM_COLLATERAL_ID
    AND [IsDeleted] = 0;