SELECT PT.[ID], PT.[TRANSFER_REFERENCE], PT.[AMOUNT], PT.[SCHEDULED_DATE], PT.[STATUS] 
FROM [PENDING_TRANSFERS] PT 
WHERE PT.[IsDeleted] = 0 
	AND PT.[SOURCE_ACCOUNT_ID] = @PRM_PENDING_TRANSFER_SOURCE_ACCOUNT_ID 
ORDER BY PT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 