SELECT PT.[ID], PT.[TRANSFER_REFERENCE], PT.[SOURCE_ACCOUNT_ID], PT.[AMOUNT] 
FROM [PENDING_TRANSFERS] PT 
WHERE PT.[IsDeleted] = 0 
	AND PT.[STATUS] = @PRM_PENDING_TRANSFER_STATUS 
ORDER BY PT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 