SELECT TOP 1 C.[ID], C.[CUSTOMER_NUMBER], C.[FIRST_NAME], C.[LAST_NAME], C.[STATUS] 
FROM [CUSTOMERS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[CUSTOMER_NUMBER] = @PRM_CUSTOMER_CUSTOMER_NUMBER 
ORDER BY C.[ID] 