SELECT C.[ID], C.[CUSTOMER_NUMBER], C.[FIRST_NAME], C.[LAST_NAME], C.[STATUS] 
FROM [CUSTOMERS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[LAST_NAME] LIKE '%' + @PRM_CUSTOMER_LAST_NAME + '%' 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 