SELECT COUNT(*) 
FROM [CUSTOMERS] C 
	INNER JOIN [CUSTOMER_TYPES] CT 
			ON C.[CUSTOMER_TYPE_ID] = CT.[ID] 
WHERE C.[IsDeleted] = 0 
	AND CT.[IsDeleted] = 0 
	AND C.[CUSTOMER_TYPE_ID] = @PRM_CUSTOMERS_CUSTOMER_TYPE_ID 
	AND CT.[ID] = @PRM_CUSTOMER_TYPES_ID 
	AND C.[STATUS] = @PRM_CUSTOMERS_STATUS 
ORDER BY C.[C.ID] 