SELECT C.[ID], C.[CUSTOMER_NUMBER], C.[FIRST_NAME], C.[LAST_NAME] 
FROM [CUSTOMERS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[STATUS] = @PRM_CUSTOMER_STATUS 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 