SELECT C.[ID], C.[CUSTOMER_NUMBER], C.[FIRST_NAME], C.[LAST_NAME], CT.[NAME] AS CUSTOMER_TYPE_NAME 
FROM [CUSTOMERS] C 
	INNER JOIN [CUSTOMER_TYPES] CT 
			ON C.[CUSTOMER_TYPE_ID] = CT.[ID] 
WHERE C.[IsDeleted] = 0 
	AND CT.[IsDeleted] = 0 
	AND C.[CUSTOMER_TYPE_ID] = @PRM_CUSTOMERS_CUSTOMER_TYPE_ID 
	AND CT.[ID] = @PRM_CUSTOMER_TYPES_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 