SELECT C.[ID], C.[CUSTOMER_NUMBER], C.[FIRST_NAME], C.[LAST_NAME], C.[CREATED_DATE] 
FROM [CUSTOMERS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[CREATED_DATE] > DATEADD(DAY, -30,
	GETDATE()) 
ORDER BY C.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 