SELECT
    [ID],
    [PRIMARY_CUSTOMER_ID],
    [RELATED_CUSTOMER_ID],
    [RELATIONSHIP_TYPE],
    [CREATED_DATE]
FROM [dbo].[CUSTOMER_RELATIONSHIPS]
WHERE
    [ID] = @PRM_CUSTOMER_RELATIONSHIP_ID
    AND [IsDeleted] = 0;