UPDATE [dbo].[CUSTOMER_RELATIONSHIPS]
SET
    [PRIMARY_CUSTOMER_ID] = @PRM_CUSTOMER_RELATIONSHIP_PRIMARY_CUSTOMER_ID,
    [RELATED_CUSTOMER_ID] = @PRM_CUSTOMER_RELATIONSHIP_RELATED_CUSTOMER_ID,
    [RELATIONSHIP_TYPE] = @PRM_CUSTOMER_RELATIONSHIP_RELATIONSHIP_TYPE,
    [CREATED_DATE] = @PRM_CUSTOMER_RELATIONSHIP_CREATED_DATE
WHERE
    [ID] = @PRM_CUSTOMER_RELATIONSHIP_ID
    AND [IsDeleted] = 0;