INSERT INTO [dbo].[CUSTOMER_RELATIONSHIPS] (
    [PRIMARY_CUSTOMER_ID],
    [RELATED_CUSTOMER_ID],
    [RELATIONSHIP_TYPE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CUSTOMER_RELATIONSHIP_PRIMARY_CUSTOMER_ID,
    @PRM_CUSTOMER_RELATIONSHIP_RELATED_CUSTOMER_ID,
    @PRM_CUSTOMER_RELATIONSHIP_RELATIONSHIP_TYPE,
    @PRM_CUSTOMER_RELATIONSHIP_CREATED_DATE
    );