SELECT
    [ID],
    [PRIMARY_CUSTOMER_ID],
    [RELATED_CUSTOMER_ID],
    [RELATIONSHIP_TYPE],
    [CREATED_DATE]
FROM [dbo].[CUSTOMER_RELATIONSHIPS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;