SELECT B.[ID], B.[NICKNAME], B.[BENEFICIARY_ACCOUNT_NUMBER], B.[BENEFICIARY_NAME] 
FROM [BENEFICIARIES] B 
WHERE B.[IsDeleted] = 0 
	AND B.[CUSTOMER_ID] = @PRM_BENEFICIARY_CUSTOMER_ID 
	AND B.[IS_ACTIVE] = @PRM_BENEFICIARY_IS_ACTIVE 
ORDER BY B.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 