SELECT B.[ID], B.[NICKNAME], B.[BENEFICIARY_ACCOUNT_NUMBER] 
FROM [BENEFICIARIES] B 
WHERE B.[IsDeleted] = 0 
	AND B.[CUSTOMER_ID] = @PRM_BENEFICIARY_CUSTOMER_ID 
	AND B.[NICKNAME] LIKE '%' + @PRM_BENEFICIARY_NICKNAME + '%' 
ORDER BY B.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 