//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.FeeType
{
    public record FeeTypeDto
    {
        public int Id { get; init; }
        public string Code { get; init; }
        public string Name { get; init; }
        public decimal FixedAmount { get; init; }
        public decimal PercentageRate { get; init; }
        public bool IsActive { get; init; }
    }
}