//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.DemoUzeyir.Portal.Models;
using QuickCode.DemoUzeyir.Portal.Models.LoanManagementModule;
using QuickCode.DemoUzeyir.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.DemoUzeyir.Common.Nswag.Clients.IdentityModuleApi.Contracts;
using LoanManagementModuleContracts = QuickCode.DemoUzeyir.Common.Nswag.Clients.LoanManagementModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.DemoUzeyir.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using AutoRest.Core.Utilities.Collections;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.DemoUzeyir.Portal.Controllers.LoanManagementModule
{
    [Permission("LoanManagementModuleLoanApplications")]
    [Area("LoanManagementModule")]
    [Route("LoanManagementModuleLoanApplications")]
    public partial class LoanApplicationsController : BaseController
    {
        private readonly LoanManagementModuleContracts.ILoanApplicationsClient pageClient;
        private readonly LoanManagementModuleContracts.ILoanProductsClient pageLoanProductClient;
        public LoanApplicationsController(LoanManagementModuleContracts.ILoanApplicationsClient pageClient, LoanManagementModuleContracts.ILoanProductsClient pageLoanProductClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageLoanProductClient = pageLoanProductClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(LoanApplicationData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(LoanApplicationData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.LoanApplicationsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(LoanApplicationData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.LoanApplicationsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(LoanApplicationData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.LoanApplicationsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(LoanApplicationData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(LoanApplicationData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(LoanApplicationData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(LoanApplicationData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<LoanApplicationData> PrepareModel()
        {
            var model = GetModel<LoanApplicationData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<LoanApplicationData> PrepareModel(LoanApplicationData model)
        {
            model.NumberOfRecord = await pageClient.LoanApplicationsCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.LoanApplicationsListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("LoanProducts", () => pageLoanProductClient.LoanProductsListAsync()));
            return comboBoxList;
        }
    }
}