//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.PortalMenu;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories;
internal static class PortalMenuCrudSqlBindings
{
    public const string StoreTableName = "PortalMenus";
    public const string ParameterNamePrefix = "PortalMenu";
    public const string KeyParameterName = "PRM_PORTAL_MENU_KEY";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string DeletePortalMenuItemsWithModelName = "DeletePortalMenuItemsWithModelName";
        public const string DeletePortalMenuItemsWithModuleName = "DeletePortalMenuItemsWithModuleName";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("Key", nameof(PortalMenuDto.Key)),
        ("Name", nameof(PortalMenuDto.Name)),
        ("Text", nameof(PortalMenuDto.Text)),
        ("Tooltip", nameof(PortalMenuDto.Tooltip)),
        ("ActionName", nameof(PortalMenuDto.ActionName)),
        ("OrderNo", nameof(PortalMenuDto.OrderNo)),
        ("ParentName", nameof(PortalMenuDto.ParentName))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("Name", nameof(PortalMenuDto.Name)),
        ("Text", nameof(PortalMenuDto.Text)),
        ("Tooltip", nameof(PortalMenuDto.Tooltip)),
        ("ActionName", nameof(PortalMenuDto.ActionName)),
        ("OrderNo", nameof(PortalMenuDto.OrderNo)),
        ("ParentName", nameof(PortalMenuDto.ParentName)),
        ("Key", nameof(PortalMenuDto.Key))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("Key", nameof(PortalMenuDto.Key))
    };
}