//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.Collateral;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories;
internal static class CollateralCrudSqlBindings
{
    public const string StoreTableName = "COLLATERALS";
    public const string ParameterNamePrefix = "COLLATERAL";
    public const string IdParameterName = "PRM_COLLATERAL_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByApplicationId = "GetByApplicationId";
        public const string GetByPk = "GetByPk";
        public const string GetCollateralsWithType = "GetCollateralsWithType";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateMarketValue = "UpdateMarketValue";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("LOAN_APPLICATION_ID", nameof(CollateralDto.LoanApplicationId)),
        ("COLLATERAL_TYPE_ID", nameof(CollateralDto.CollateralTypeId)),
        ("DESCRIPTION", nameof(CollateralDto.Description)),
        ("MARKET_VALUE", nameof(CollateralDto.MarketValue)),
        ("VALUATION_DATE", nameof(CollateralDto.ValuationDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("LOAN_APPLICATION_ID", nameof(CollateralDto.LoanApplicationId)),
        ("COLLATERAL_TYPE_ID", nameof(CollateralDto.CollateralTypeId)),
        ("DESCRIPTION", nameof(CollateralDto.Description)),
        ("MARKET_VALUE", nameof(CollateralDto.MarketValue)),
        ("VALUATION_DATE", nameof(CollateralDto.ValuationDate)),
        ("ID", nameof(CollateralDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CollateralDto.Id))
    };
}