SELECT RS.[ID], RS.[INSTALLMENT_NUMBER], RS.[DUE_DATE], RS.[TOTAL_AMOUNT], RS.[STATUS] 
FROM [REPAYMENT_SCHEDULES] RS 
WHERE RS.[IsDeleted] = 0 
	AND RS.[LOAN_ID] = @PRM_REPAYMENT_SCHEDULE_LOAN_ID 
ORDER BY RS.[INSTALLMENT_NUMBER] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 