SELECT RS.[ID], RS.[INSTALLMENT_NUMBER], RS.[DUE_DATE], RS.[TOTAL_AMOUNT] 
FROM [REPAYMENT_SCHEDULES] RS 
WHERE RS.[IsDeleted] = 0 
	AND RS.[LOAN_ID] = @PRM_REPAYMENT_SCHEDULE_LOAN_ID 
	AND RS.[STATUS] = @PRM_REPAYMENT_SCHEDULE_STATUS 
	AND RS.[DUE_DATE] < DATEADD(DAY,
	30,
	GETDATE()) 
ORDER BY RS.[DUE_DATE] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 