//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Contexts;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanApplication;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories
{
    public partial class LoanApplicationRepository : BaseRepository, ILoanApplicationRepository
    {
        public async Task<RepoResponse<int>> SubmitApplicationAsync(int loanApplicationId, SubmitApplicationRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("LoanApplication", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanApplication.Command.SubmitApplication);
                var parameters = new
                {
                    PRM_LOAN_APPLICATION_ID = loanApplicationId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> ApproveApplicationAsync(int loanApplicationId, ApproveApplicationRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("LoanApplication", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanApplication.Command.ApproveApplication);
                var parameters = new
                {
                    PRM_LOAN_APPLICATION_ID = loanApplicationId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> RejectApplicationAsync(int loanApplicationId, RejectApplicationRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("LoanApplication", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanApplication.Command.RejectApplication);
                var parameters = new
                {
                    PRM_LOAN_APPLICATION_ID = loanApplicationId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> WithdrawApplicationAsync(int loanApplicationId, WithdrawApplicationRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("LoanApplication", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanApplication.Command.WithdrawApplication);
                var parameters = new
                {
                    PRM_LOAN_APPLICATION_ID = loanApplicationId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}