//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanApplication;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories
{
    public partial class LoanApplicationRepository : BaseRepository, ILoanApplicationRepository
    {
        public async Task<RepoResponse<GetByApplicationNumberResponseDto>> GetByApplicationNumberAsync(Guid loanApplicationApplicationNumber)
        {
            return await ExecuteWithExceptionHandling(LoanApplicationCrudSqlBindings.OperationNames.GetByApplicationNumber, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoanApplication.Query.GetByApplicationNumber);
                var parameters = new
                {
                    PRM_LOAN_APPLICATION_APPLICATION_NUMBER = loanApplicationApplicationNumber
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByApplicationNumberResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in LoanApplication");
            });
        }

        public async Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int loanApplicationCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(LoanApplicationCrudSqlBindings.OperationNames.GetByCustomerId, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.LoanApplication.Query.GetByCustomerId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_LOAN_APPLICATION_CUSTOMER_ID = loanApplicationCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCustomerIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in LoanApplication");
                }
            });
        }

        public async Task<RepoResponse<List<GetPendingReviewResponseDto>>> GetPendingReviewAsync(LoanApplicationStatus loanApplicationStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(LoanApplicationCrudSqlBindings.OperationNames.GetPendingReview, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPendingReviewResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.LoanApplication.Query.GetPendingReview);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_LOAN_APPLICATION_STATUS = loanApplicationStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPendingReviewResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in LoanApplication");
                }
            });
        }

        public async Task<RepoResponse<List<GetApplicationsWithProductResponseDto>>> GetApplicationsWithProductAsync(int loanApplicationsCustomerId, int loanApplicationsLoanProductId, int loanProductsId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(LoanApplicationCrudSqlBindings.OperationNames.GetApplicationsWithProduct, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetApplicationsWithProductResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.LoanApplication.Query.GetApplicationsWithProduct);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_LOAN_APPLICATIONS_CUSTOMER_ID = loanApplicationsCustomerId,
                        PRM_LOAN_APPLICATIONS_LOAN_PRODUCT_ID = loanApplicationsLoanProductId,
                        PRM_LOAN_PRODUCTS_ID = loanProductsId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetApplicationsWithProductResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in LoanApplication");
                }
            });
        }
    }
}