//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.Module;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories;
internal static class ModuleCrudSqlBindings
{
    public const string StoreTableName = "Modules";
    public const string ParameterNamePrefix = "Module";
    public const string NameParameterName = "PRM_MODULE_NAME";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string ModuleNameIsExists = "ModuleNameIsExists";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("Name", nameof(ModuleDto.Name)),
        ("Description", nameof(ModuleDto.Description))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("Description", nameof(ModuleDto.Description)),
        ("Name", nameof(ModuleDto.Name))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("Name", nameof(ModuleDto.Name))
    };
}