//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.ColumnType;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories;
internal static class ColumnTypeCrudSqlBindings
{
    public const string StoreTableName = "ColumnTypes";
    public const string ParameterNamePrefix = "ColumnType";
    public const string IdParameterName = "PRM_COLUMN_TYPE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("TypeName", nameof(ColumnTypeDto.TypeName)),
        ("IosComponentName", nameof(ColumnTypeDto.IosComponentName)),
        ("IosType", nameof(ColumnTypeDto.IosType)),
        ("IconCode", nameof(ColumnTypeDto.IconCode))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("TypeName", nameof(ColumnTypeDto.TypeName)),
        ("IosComponentName", nameof(ColumnTypeDto.IosComponentName)),
        ("IosType", nameof(ColumnTypeDto.IosType)),
        ("IconCode", nameof(ColumnTypeDto.IconCode)),
        ("Id", nameof(ColumnTypeDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("Id", nameof(ColumnTypeDto.Id))
    };
}