//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.PortalPageAccessGrant;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class PortalPageAccessGrantRepository : BaseRepository, IPortalPageAccessGrantRepository
    {
        public async Task<RepoResponse<List<GetPortalPageAccessGrantsResponseDto>>> GetPortalPageAccessGrantsAsync(string portalPageAccessGrantPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling(PortalPageAccessGrantCrudSqlBindings.OperationNames.GetPortalPageAccessGrants, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Query.GetPortalPageAccessGrants);
                var parameters = new
                {
                    PRM_PortalPageAccessGrant_PermissionGroupName = portalPageAccessGrantPermissionGroupName
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetPortalPageAccessGrantsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageAccessGrant");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageAccessGrantResponseDto>>> GetPortalPageAccessGrantAsync(string portalPageAccessGrantPermissionGroupName, string portalPageAccessGrantPortalPageDefinitionKey, PageActionType portalPageAccessGrantPageAction)
        {
            return await ExecuteWithExceptionHandling(PortalPageAccessGrantCrudSqlBindings.OperationNames.GetPortalPageAccessGrant, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Query.GetPortalPageAccessGrant);
                var parameters = new
                {
                    PRM_PortalPageAccessGrant_PortalPageDefinitionKey = portalPageAccessGrantPortalPageDefinitionKey,
                    PRM_PortalPageAccessGrant_PermissionGroupName = portalPageAccessGrantPermissionGroupName,
                    PRM_PortalPageAccessGrant_PageAction = portalPageAccessGrantPageAction
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetPortalPageAccessGrantResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageAccessGrant");
            });
        }
    }
}