//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Entities;
using QuickCode.DemoUzeyir.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.PortalPageAccessGrant;
using QuickCode.DemoUzeyir.IdentityModule.Application.Mappings;
using QuickCode.DemoUzeyir.IdentityModule.Persistence.Sql;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Persistence.Repositories
{
    public partial class PortalPageAccessGrantRepository : BaseRepository, IPortalPageAccessGrantRepository
    {
        public async Task<RepoResponse<int>> ClearPortalPageAccessGrantsAsync()
        {
            return await ExecuteWithExceptionHandling(PortalPageAccessGrantCrudSqlBindings.OperationNames.ClearPortalPageAccessGrants, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Command.ClearPortalPageAccessGrants);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}