UPDATE [dbo].[TableComboboxSettings]
SET
    [IdColumn] = @PRM_TABLE_COMBOBOX_SETTING_ID_COLUMN,
    [TextColumns] = @PRM_TABLE_COMBOBOX_SETTING_TEXT_COLUMNS,
    [StringFormat] = @PRM_TABLE_COMBOBOX_SETTING_STRING_FORMAT
WHERE
    [TableName] = @PRM_TABLE_COMBOBOX_SETTING_TABLE_NAME;