//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.PendingTransfer;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Interfaces.Repositories
{
    public partial interface IPendingTransferRepository : IBaseRepository<PendingTransferDto>
    {
        Task<RepoResponse<PendingTransferDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetScheduledTransfersResponseDto>>> GetScheduledTransfersAsync(TransferStatus pendingTransferStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPendingApprovalResponseDto>>> GetPendingApprovalAsync(TransferStatus pendingTransferStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetBySourceAccountResponseDto>>> GetBySourceAccountAsync(int pendingTransferSourceAccountId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> ApproveTransferAsync(int pendingTransferId, ApproveTransferRequestDto updateRequest);
        Task<RepoResponse<int>> RejectTransferAsync(int pendingTransferId, RejectTransferRequestDto updateRequest);
        Task<RepoResponse<int>> CancelScheduledTransferAsync(int pendingTransferId, TransferStatus pendingTransferStatus);
    }
}