//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.TransactionChannel;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Interfaces.Repositories
{
    public partial interface ITransactionChannelRepository : IBaseRepository<TransactionChannelDto>
    {
        Task<RepoResponse<TransactionChannelDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool transactionChannelIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByCodeResponseDto>> GetByCodeAsync(string transactionChannelCode);
        Task<RepoResponse<int>> DeactivateAsync(int transactionChannelId, DeactivateRequestDto updateRequest);
    }
}