//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.DemoUzeyir.Portal.Models;
using QuickCode.DemoUzeyir.Portal.Models.AccountManagementModule;
using QuickCode.DemoUzeyir.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.DemoUzeyir.Common.Nswag.Clients.IdentityModuleApi.Contracts;
using AccountManagementModuleContracts = QuickCode.DemoUzeyir.Common.Nswag.Clients.AccountManagementModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.DemoUzeyir.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using AutoRest.Core.Utilities.Collections;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.DemoUzeyir.Portal.Controllers.AccountManagementModule
{
    [Permission("AccountManagementModuleAccounts")]
    [Area("AccountManagementModule")]
    [Route("AccountManagementModuleAccounts")]
    public partial class AccountsController : BaseController
    {
        private readonly AccountManagementModuleContracts.IAccountsClient pageClient;
        private readonly AccountManagementModuleContracts.IAccountTypesClient pageAccountTypeClient;
        private readonly AccountManagementModuleContracts.ICurrenciesClient pageCurrencyClient;
        public AccountsController(AccountManagementModuleContracts.IAccountsClient pageClient, AccountManagementModuleContracts.IAccountTypesClient pageAccountTypeClient, AccountManagementModuleContracts.ICurrenciesClient pageCurrencyClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageAccountTypeClient = pageAccountTypeClient;
            this.pageCurrencyClient = pageCurrencyClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(AccountData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(AccountData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.AccountsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(AccountData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.AccountsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(AccountData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.AccountsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(AccountData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(AccountData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(AccountData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(AccountData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<AccountData> PrepareModel()
        {
            var model = GetModel<AccountData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<AccountData> PrepareModel(AccountData model)
        {
            model.NumberOfRecord = await pageClient.AccountsCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.AccountsListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("AccountTypes", () => pageAccountTypeClient.AccountTypesListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("Currencies", () => pageCurrencyClient.CurrenciesListAsync()));
            return comboBoxList;
        }
    }
}