//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.DocumentType;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories;
internal static class DocumentTypeCrudSqlBindings
{
    public const string StoreTableName = "DOCUMENT_TYPES";
    public const string ParameterNamePrefix = "DOCUMENT_TYPE";
    public const string IdParameterName = "PRM_DOCUMENT_TYPE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCode = "GetByCode";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CODE", nameof(DocumentTypeDto.Code)),
        ("NAME", nameof(DocumentTypeDto.Name)),
        ("IS_ACTIVE", nameof(DocumentTypeDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CODE", nameof(DocumentTypeDto.Code)),
        ("NAME", nameof(DocumentTypeDto.Name)),
        ("IS_ACTIVE", nameof(DocumentTypeDto.IsActive)),
        ("ID", nameof(DocumentTypeDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(DocumentTypeDto.Id))
    };
}