INSERT INTO [dbo].[LOAN_PAYMENTS] (
    [LOAN_ID],
    [SCHEDULE_ID],
    [PAYMENT_REFERENCE],
    [AMOUNT_PAID],
    [PAYMENT_DATE],
    [PAYMENT_METHOD]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_LOAN_PAYMENT_LOAN_ID,
    @PRM_LOAN_PAYMENT_SCHEDULE_ID,
    @PRM_LOAN_PAYMENT_PAYMENT_REFERENCE,
    @PRM_LOAN_PAYMENT_AMOUNT_PAID,
    @PRM_LOAN_PAYMENT_PAYMENT_DATE,
    @PRM_LOAN_PAYMENT_PAYMENT_METHOD
    );