UPDATE [dbo].[LOAN_PAYMENTS]
SET
    [LOAN_ID] = @PRM_LOAN_PAYMENT_LOAN_ID,
    [SCHEDULE_ID] = @PRM_LOAN_PAYMENT_SCHEDULE_ID,
    [PAYMENT_REFERENCE] = @PRM_LOAN_PAYMENT_PAYMENT_REFERENCE,
    [AMOUNT_PAID] = @PRM_LOAN_PAYMENT_AMOUNT_PAID,
    [PAYMENT_DATE] = @PRM_LOAN_PAYMENT_PAYMENT_DATE,
    [PAYMENT_METHOD] = @PRM_LOAN_PAYMENT_PAYMENT_METHOD
WHERE
    [ID] = @PRM_LOAN_PAYMENT_ID
    AND [IsDeleted] = 0;