SELECT
    [ID],
    [LOAN_ID],
    [SCHEDULE_ID],
    [PAYMENT_REFERENCE],
    [AMOUNT_PAID],
    [PAYMENT_DATE],
    [PAYMENT_METHOD]
FROM [dbo].[LOAN_PAYMENTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;