//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.CollateralType;
using CollateralTypeEntity = QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities.CollateralType;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings
{
    public static class CollateralTypeMappings
    {
        public static List<CollateralTypeDto> ToDto(this IEnumerable<CollateralTypeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CollateralTypeDto ToDto(this CollateralTypeEntity model)
        {
            return new CollateralTypeDto
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                IsActive = model.IsActive
            };
        }

        public static CollateralTypeEntity ToEntity(this CollateralTypeDto model)
        {
            return new CollateralTypeEntity
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                IsActive = model.IsActive
            };
        }
    }
}