//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.Collateral;
using CollateralEntity = QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities.Collateral;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings
{
    public static class CollateralMappings
    {
        public static List<CollateralDto> ToDto(this IEnumerable<CollateralEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CollateralDto ToDto(this CollateralEntity model)
        {
            return new CollateralDto
            {
                Id = model.Id,
                LoanApplicationId = model.LoanApplicationId,
                CollateralTypeId = model.CollateralTypeId,
                Description = model.Description,
                MarketValue = model.MarketValue,
                ValuationDate = model.ValuationDate
            };
        }

        public static CollateralEntity ToEntity(this CollateralDto model)
        {
            return new CollateralEntity
            {
                Id = model.Id,
                LoanApplicationId = model.LoanApplicationId,
                CollateralTypeId = model.CollateralTypeId,
                Description = model.Description,
                MarketValue = model.MarketValue,
                ValuationDate = model.ValuationDate
            };
        }
    }
}