//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanApplication;
using LoanApplicationEntity = QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities.LoanApplication;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings
{
    public static class LoanApplicationMappings
    {
        public static List<LoanApplicationDto> ToDto(this IEnumerable<LoanApplicationEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static LoanApplicationDto ToDto(this LoanApplicationEntity model)
        {
            return new LoanApplicationDto
            {
                Id = model.Id,
                ApplicationNumber = model.ApplicationNumber,
                CustomerId = model.CustomerId,
                LoanProductId = model.LoanProductId,
                RequestedAmount = model.RequestedAmount,
                RequestedTermMonths = model.RequestedTermMonths,
                Purpose = model.Purpose,
                Status = model.Status,
                SubmittedDate = model.SubmittedDate,
                DecisionDate = model.DecisionDate
            };
        }

        public static LoanApplicationEntity ToEntity(this LoanApplicationDto model)
        {
            return new LoanApplicationEntity
            {
                Id = model.Id,
                ApplicationNumber = model.ApplicationNumber,
                CustomerId = model.CustomerId,
                LoanProductId = model.LoanProductId,
                RequestedAmount = model.RequestedAmount,
                RequestedTermMonths = model.RequestedTermMonths,
                Purpose = model.Purpose,
                Status = model.Status,
                SubmittedDate = model.SubmittedDate,
                DecisionDate = model.DecisionDate
            };
        }
    }
}