//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.Loan;
using LoanEntity = QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities.Loan;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings
{
    public static class LoanMappings
    {
        public static List<LoanDto> ToDto(this IEnumerable<LoanEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static LoanDto ToDto(this LoanEntity model)
        {
            return new LoanDto
            {
                Id = model.Id,
                LoanAccountNumber = model.LoanAccountNumber,
                ApplicationId = model.ApplicationId,
                CustomerId = model.CustomerId,
                PrincipalAmount = model.PrincipalAmount,
                OutstandingBalance = model.OutstandingBalance,
                InterestRate = model.InterestRate,
                TermMonths = model.TermMonths,
                DisbursementDate = model.DisbursementDate,
                MaturityDate = model.MaturityDate,
                Status = model.Status
            };
        }

        public static LoanEntity ToEntity(this LoanDto model)
        {
            return new LoanEntity
            {
                Id = model.Id,
                LoanAccountNumber = model.LoanAccountNumber,
                ApplicationId = model.ApplicationId,
                CustomerId = model.CustomerId,
                PrincipalAmount = model.PrincipalAmount,
                OutstandingBalance = model.OutstandingBalance,
                InterestRate = model.InterestRate,
                TermMonths = model.TermMonths,
                DisbursementDate = model.DisbursementDate,
                MaturityDate = model.MaturityDate,
                Status = model.Status
            };
        }
    }
}