//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanProduct;
using LoanProductEntity = QuickCode.DemoUzeyir.LoanManagementModule.Domain.Entities.LoanProduct;
using QuickCode.DemoUzeyir.LoanManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Application.Mappings
{
    public static class LoanProductMappings
    {
        public static List<LoanProductDto> ToDto(this IEnumerable<LoanProductEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static LoanProductDto ToDto(this LoanProductEntity model)
        {
            return new LoanProductDto
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                MinAmount = model.MinAmount,
                MaxAmount = model.MaxAmount,
                MinTermMonths = model.MinTermMonths,
                MaxTermMonths = model.MaxTermMonths,
                InterestRate = model.InterestRate,
                IsActive = model.IsActive
            };
        }

        public static LoanProductEntity ToEntity(this LoanProductDto model)
        {
            return new LoanProductEntity
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                MinAmount = model.MinAmount,
                MaxAmount = model.MaxAmount,
                MinTermMonths = model.MinTermMonths,
                MaxTermMonths = model.MaxTermMonths,
                InterestRate = model.InterestRate,
                IsActive = model.IsActive
            };
        }
    }
}