//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.CustomerRelationship;
using CustomerRelationshipEntity = QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities.CustomerRelationship;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings
{
    public static class CustomerRelationshipMappings
    {
        public static List<CustomerRelationshipDto> ToDto(this IEnumerable<CustomerRelationshipEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CustomerRelationshipDto ToDto(this CustomerRelationshipEntity model)
        {
            return new CustomerRelationshipDto
            {
                Id = model.Id,
                PrimaryCustomerId = model.PrimaryCustomerId,
                RelatedCustomerId = model.RelatedCustomerId,
                RelationshipType = model.RelationshipType,
                CreatedDate = model.CreatedDate
            };
        }

        public static CustomerRelationshipEntity ToEntity(this CustomerRelationshipDto model)
        {
            return new CustomerRelationshipEntity
            {
                Id = model.Id,
                PrimaryCustomerId = model.PrimaryCustomerId,
                RelatedCustomerId = model.RelatedCustomerId,
                RelationshipType = model.RelationshipType,
                CreatedDate = model.CreatedDate
            };
        }
    }
}