//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.CustomerType;
using CustomerTypeEntity = QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities.CustomerType;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings
{
    public static class CustomerTypeMappings
    {
        public static List<CustomerTypeDto> ToDto(this IEnumerable<CustomerTypeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CustomerTypeDto ToDto(this CustomerTypeEntity model)
        {
            return new CustomerTypeDto
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }

        public static CustomerTypeEntity ToEntity(this CustomerTypeDto model)
        {
            return new CustomerTypeEntity
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }
    }
}