//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.IdentificationDocument;
using IdentificationDocumentEntity = QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities.IdentificationDocument;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings
{
    public static class IdentificationDocumentMappings
    {
        public static List<IdentificationDocumentDto> ToDto(this IEnumerable<IdentificationDocumentEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static IdentificationDocumentDto ToDto(this IdentificationDocumentEntity model)
        {
            return new IdentificationDocumentDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                DocumentTypeId = model.DocumentTypeId,
                DocumentNumber = model.DocumentNumber,
                IssueDate = model.IssueDate,
                ExpiryDate = model.ExpiryDate,
                IssuingCountry = model.IssuingCountry,
                DocumentUrl = model.DocumentUrl,
                Status = model.Status
            };
        }

        public static IdentificationDocumentEntity ToEntity(this IdentificationDocumentDto model)
        {
            return new IdentificationDocumentEntity
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                DocumentTypeId = model.DocumentTypeId,
                DocumentNumber = model.DocumentNumber,
                IssueDate = model.IssueDate,
                ExpiryDate = model.ExpiryDate,
                IssuingCountry = model.IssuingCountry,
                DocumentUrl = model.DocumentUrl,
                Status = model.Status
            };
        }
    }
}