SELECT CT.[ID], CT.[CODE], CT.[NAME] 
FROM [CUSTOMER_TYPES] CT 
WHERE CT.[IsDeleted] = 0 
	AND CT.[IS_ACTIVE] = @PRM_CUSTOMER_TYPE_IS_ACTIVE 
ORDER BY CT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 