INSERT INTO [dbo].[TRANSACTION_TYPES] (
    [CODE],
    [NAME],
    [DIRECTION],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TRANSACTION_TYPE_CODE,
    @PRM_TRANSACTION_TYPE_NAME,
    @PRM_TRANSACTION_TYPE_DIRECTION,
    @PRM_TRANSACTION_TYPE_IS_ACTIVE
    );