UPDATE [dbo].[TRANSACTION_TYPES]
SET
    [CODE] = @PRM_TRANSACTION_TYPE_CODE,
    [NAME] = @PRM_TRANSACTION_TYPE_NAME,
    [DIRECTION] = @PRM_TRANSACTION_TYPE_DIRECTION,
    [IS_ACTIVE] = @PRM_TRANSACTION_TYPE_IS_ACTIVE
WHERE
    [ID] = @PRM_TRANSACTION_TYPE_ID
    AND [IsDeleted] = 0;