//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Entities;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Contexts;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Dtos.TransactionChannel;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Application.Mappings;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Sql;
using QuickCode.DemoUzeyir.TransactionProcessingModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.TransactionProcessingModule.Persistence.Repositories
{
    public partial class TransactionChannelRepository : BaseRepository, ITransactionChannelRepository
    {
        public async Task<RepoResponse<int>> DeactivateAsync(int transactionChannelId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("TransactionChannel", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TransactionChannel.Command.Deactivate);
                var parameters = new
                {
                    PRM_TRANSACTION_CHANNEL_ID = transactionChannelId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}