//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.LoanManagementModule.Application.Dtos.LoanProduct;

namespace QuickCode.DemoUzeyir.LoanManagementModule.Persistence.Repositories;
internal static class LoanProductCrudSqlBindings
{
    public const string StoreTableName = "LOAN_PRODUCTS";
    public const string ParameterNamePrefix = "LOAN_PRODUCT";
    public const string IdParameterName = "PRM_LOAN_PRODUCT_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCode = "GetByCode";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateInterestRate = "UpdateInterestRate";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CODE", nameof(LoanProductDto.Code)),
        ("NAME", nameof(LoanProductDto.Name)),
        ("MIN_AMOUNT", nameof(LoanProductDto.MinAmount)),
        ("MAX_AMOUNT", nameof(LoanProductDto.MaxAmount)),
        ("MIN_TERM_MONTHS", nameof(LoanProductDto.MinTermMonths)),
        ("MAX_TERM_MONTHS", nameof(LoanProductDto.MaxTermMonths)),
        ("INTEREST_RATE", nameof(LoanProductDto.InterestRate)),
        ("IS_ACTIVE", nameof(LoanProductDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CODE", nameof(LoanProductDto.Code)),
        ("NAME", nameof(LoanProductDto.Name)),
        ("MIN_AMOUNT", nameof(LoanProductDto.MinAmount)),
        ("MAX_AMOUNT", nameof(LoanProductDto.MaxAmount)),
        ("MIN_TERM_MONTHS", nameof(LoanProductDto.MinTermMonths)),
        ("MAX_TERM_MONTHS", nameof(LoanProductDto.MaxTermMonths)),
        ("INTEREST_RATE", nameof(LoanProductDto.InterestRate)),
        ("IS_ACTIVE", nameof(LoanProductDto.IsActive)),
        ("ID", nameof(LoanProductDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(LoanProductDto.Id))
    };
}