INSERT INTO [dbo].[ApiMethodDefinitions] (
    [Key],
    [ModuleName],
    [ModelName],
    [HttpMethod],
    [ControllerName],
    [MethodName],
    [UrlPath]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_API_METHOD_DEFINITION_KEY,
    @PRM_API_METHOD_DEFINITION_MODULE_NAME,
    @PRM_API_METHOD_DEFINITION_MODEL_NAME,
    @PRM_API_METHOD_DEFINITION_HTTP_METHOD,
    @PRM_API_METHOD_DEFINITION_CONTROLLER_NAME,
    @PRM_API_METHOD_DEFINITION_METHOD_NAME,
    @PRM_API_METHOD_DEFINITION_URL_PATH
    );