UPDATE [dbo].[ApiMethodDefinitions]
SET
    [ModuleName] = @PRM_API_METHOD_DEFINITION_MODULE_NAME,
    [ModelName] = @PRM_API_METHOD_DEFINITION_MODEL_NAME,
    [HttpMethod] = @PRM_API_METHOD_DEFINITION_HTTP_METHOD,
    [ControllerName] = @PRM_API_METHOD_DEFINITION_CONTROLLER_NAME,
    [MethodName] = @PRM_API_METHOD_DEFINITION_METHOD_NAME,
    [UrlPath] = @PRM_API_METHOD_DEFINITION_URL_PATH
WHERE
    [Key] = @PRM_API_METHOD_DEFINITION_KEY;