SELECT LA.[ID], LA.[APPLICATION_NUMBER], LP.[NAME] AS PRODUCT_NAME,
	LA.[REQUESTED_AMOUNT], LA.[STATUS] 
FROM [LOAN_APPLICATIONS] LA 
	INNER JOIN [LOAN_PRODUCTS] LP 
			ON LA.[LOAN_PRODUCT_ID] = LP.[ID] 
WHERE LA.[IsDeleted] = 0 
	AND LP.[IsDeleted] = 0 
	AND LA.[CUSTOMER_ID] = @PRM_LOAN_APPLICATIONS_CUSTOMER_ID 
	AND LA.[LOAN_PRODUCT_ID] = @PRM_LOAN_APPLICATIONS_LOAN_PRODUCT_ID 
	AND LP.[ID] = @PRM_LOAN_PRODUCTS_ID 
ORDER BY LA.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 