SELECT LA.[ID], LA.[APPLICATION_NUMBER], LA.[REQUESTED_AMOUNT], LA.[STATUS] 
FROM [LOAN_APPLICATIONS] LA 
WHERE LA.[IsDeleted] = 0 
	AND LA.[CUSTOMER_ID] = @PRM_LOAN_APPLICATION_CUSTOMER_ID 
ORDER BY LA.[SUBMITTED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 