SELECT LA.[ID], LA.[APPLICATION_NUMBER], LA.[CUSTOMER_ID], LA.[REQUESTED_AMOUNT] 
FROM [LOAN_APPLICATIONS] LA 
WHERE LA.[IsDeleted] = 0 
	AND LA.[STATUS] = @PRM_LOAN_APPLICATION_STATUS 
ORDER BY LA.[SUBMITTED_DATE] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 