SELECT TOP 1 LA.[ID], LA.[APPLICATION_NUMBER], LA.[CUSTOMER_ID], LA.[STATUS] 
FROM [LOAN_APPLICATIONS] LA 
WHERE LA.[IsDeleted] = 0 
	AND LA.[APPLICATION_NUMBER] = @PRM_LOAN_APPLICATION_APPLICATION_NUMBER 
ORDER BY LA.[ID] 