//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.AspNetUser;
using AspNetUserEntity = QuickCode.DemoUzeyir.IdentityModule.Domain.Entities.AspNetUser;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Application.Mappings
{
    public static class AspNetUserMappings
    {
        public static List<AspNetUserDto> ToDto(this IEnumerable<AspNetUserEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AspNetUserDto ToDto(this AspNetUserEntity model)
        {
            return new AspNetUserDto
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                PermissionGroupName = model.PermissionGroupName,
                UserName = model.UserName,
                NormalizedUserName = model.NormalizedUserName,
                Email = model.Email,
                NormalizedEmail = model.NormalizedEmail,
                EmailConfirmed = model.EmailConfirmed,
                PasswordHash = model.PasswordHash,
                SecurityStamp = model.SecurityStamp,
                ConcurrencyStamp = model.ConcurrencyStamp,
                PhoneNumber = model.PhoneNumber,
                PhoneNumberConfirmed = model.PhoneNumberConfirmed,
                TwoFactorEnabled = model.TwoFactorEnabled,
                LockoutEnd = model.LockoutEnd,
                LockoutEnabled = model.LockoutEnabled,
                AccessFailedCount = model.AccessFailedCount
            };
        }

        public static AspNetUserEntity ToEntity(this AspNetUserDto model)
        {
            return new AspNetUserEntity
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                PermissionGroupName = model.PermissionGroupName,
                UserName = model.UserName,
                NormalizedUserName = model.NormalizedUserName,
                Email = model.Email,
                NormalizedEmail = model.NormalizedEmail,
                EmailConfirmed = model.EmailConfirmed,
                PasswordHash = model.PasswordHash,
                SecurityStamp = model.SecurityStamp,
                ConcurrencyStamp = model.ConcurrencyStamp,
                PhoneNumber = model.PhoneNumber,
                PhoneNumberConfirmed = model.PhoneNumberConfirmed,
                TwoFactorEnabled = model.TwoFactorEnabled,
                LockoutEnd = model.LockoutEnd,
                LockoutEnabled = model.LockoutEnabled,
                AccessFailedCount = model.AccessFailedCount
            };
        }
    }
}