//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.AspNetUserToken;
using AspNetUserTokenEntity = QuickCode.DemoUzeyir.IdentityModule.Domain.Entities.AspNetUserToken;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Application.Mappings
{
    public static class AspNetUserTokenMappings
    {
        public static List<AspNetUserTokenDto> ToDto(this IEnumerable<AspNetUserTokenEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AspNetUserTokenDto ToDto(this AspNetUserTokenEntity model)
        {
            return new AspNetUserTokenDto
            {
                UserId = model.UserId,
                LoginProvider = model.LoginProvider,
                Name = model.Name,
                Value = model.Value
            };
        }

        public static AspNetUserTokenEntity ToEntity(this AspNetUserTokenDto model)
        {
            return new AspNetUserTokenEntity
            {
                UserId = model.UserId,
                LoginProvider = model.LoginProvider,
                Name = model.Name,
                Value = model.Value
            };
        }
    }
}