//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.ColumnType;
using ColumnTypeEntity = QuickCode.DemoUzeyir.IdentityModule.Domain.Entities.ColumnType;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Application.Mappings
{
    public static class ColumnTypeMappings
    {
        public static List<ColumnTypeDto> ToDto(this IEnumerable<ColumnTypeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ColumnTypeDto ToDto(this ColumnTypeEntity model)
        {
            return new ColumnTypeDto
            {
                Id = model.Id,
                TypeName = model.TypeName,
                IosComponentName = model.IosComponentName,
                IosType = model.IosType,
                IconCode = model.IconCode
            };
        }

        public static ColumnTypeEntity ToEntity(this ColumnTypeDto model)
        {
            return new ColumnTypeEntity
            {
                Id = model.Id,
                TypeName = model.TypeName,
                IosComponentName = model.IosComponentName,
                IosType = model.IosType,
                IconCode = model.IconCode
            };
        }
    }
}