//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.Model;
using ModelEntity = QuickCode.DemoUzeyir.IdentityModule.Domain.Entities.Model;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Application.Mappings
{
    public static class ModelMappings
    {
        public static List<ModelDto> ToDto(this IEnumerable<ModelEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ModelDto ToDto(this ModelEntity model)
        {
            return new ModelDto
            {
                Name = model.Name,
                ModuleName = model.ModuleName,
                Description = model.Description
            };
        }

        public static ModelEntity ToEntity(this ModelDto model)
        {
            return new ModelEntity
            {
                Name = model.Name,
                ModuleName = model.ModuleName,
                Description = model.Description
            };
        }
    }
}