//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.IdentityModule.Application.Dtos.PermissionGroup;
using PermissionGroupEntity = QuickCode.DemoUzeyir.IdentityModule.Domain.Entities.PermissionGroup;
using QuickCode.DemoUzeyir.IdentityModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.IdentityModule.Application.Mappings
{
    public static class PermissionGroupMappings
    {
        public static List<PermissionGroupDto> ToDto(this IEnumerable<PermissionGroupEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PermissionGroupDto ToDto(this PermissionGroupEntity model)
        {
            return new PermissionGroupDto
            {
                Name = model.Name,
                Description = model.Description
            };
        }

        public static PermissionGroupEntity ToEntity(this PermissionGroupDto model)
        {
            return new PermissionGroupEntity
            {
                Name = model.Name,
                Description = model.Description
            };
        }
    }
}