SELECT
    [ID],
    [ENTITY_NAME],
    [ENTITY_ID],
    [ACTION],
    [USER_ID],
    [USER_NAME],
    [USER_GROUP],
    [TIMESTAMP],
    [OLD_VALUES],
    [NEW_VALUES],
    [CHANGED_COLUMNS],
    [IS_CHANGED],
    [CHANGE_SUMMARY],
    [IP_ADDRESS],
    [USER_AGENT],
    [CORRELATION_ID],
    [IS_SUCCESS],
    [ERROR_MESSAGE],
    [HASH]
FROM [dbo].[AUDIT_LOGS]
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;