//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.Card
{
    public record CardDto
    {
        public int Id { get; init; }
        public int AccountId { get; init; }
        public string CardNumber { get; init; }
        public string CardHolderName { get; init; }
        public int CardTypeId { get; init; }
        public short ExpiryMonth { get; init; }
        public short ExpiryYear { get; init; }
        public string Cvv { get; init; }
        public CardStatus Status { get; init; }
        public DateTime ActivationDate { get; init; }
        public bool IsActive { get; init; }
    }
}