SELECT LP.[ID], LP.[CODE], LP.[NAME], LP.[MIN_AMOUNT], LP.[MAX_AMOUNT], LP.[INTEREST_RATE] 
FROM [LOAN_PRODUCTS] LP 
WHERE LP.[IsDeleted] = 0 
	AND LP.[IS_ACTIVE] = @PRM_LOAN_PRODUCT_IS_ACTIVE 
ORDER BY LP.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 