INSERT INTO [dbo].[LOAN_PRODUCTS] (
    [CODE],
    [NAME],
    [MIN_AMOUNT],
    [MAX_AMOUNT],
    [MIN_TERM_MONTHS],
    [MAX_TERM_MONTHS],
    [INTEREST_RATE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_LOAN_PRODUCT_CODE,
    @PRM_LOAN_PRODUCT_NAME,
    @PRM_LOAN_PRODUCT_MIN_AMOUNT,
    @PRM_LOAN_PRODUCT_MAX_AMOUNT,
    @PRM_LOAN_PRODUCT_MIN_TERM_MONTHS,
    @PRM_LOAN_PRODUCT_MAX_TERM_MONTHS,
    @PRM_LOAN_PRODUCT_INTEREST_RATE,
    @PRM_LOAN_PRODUCT_IS_ACTIVE
    );