SELECT
    [ID],
    [CODE],
    [NAME],
    [MIN_AMOUNT],
    [MAX_AMOUNT],
    [MIN_TERM_MONTHS],
    [MAX_TERM_MONTHS],
    [INTEREST_RATE],
    [IS_ACTIVE]
FROM [dbo].[LOAN_PRODUCTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;