UPDATE [dbo].[LOAN_PRODUCTS]
SET
    [CODE] = @PRM_LOAN_PRODUCT_CODE,
    [NAME] = @PRM_LOAN_PRODUCT_NAME,
    [MIN_AMOUNT] = @PRM_LOAN_PRODUCT_MIN_AMOUNT,
    [MAX_AMOUNT] = @PRM_LOAN_PRODUCT_MAX_AMOUNT,
    [MIN_TERM_MONTHS] = @PRM_LOAN_PRODUCT_MIN_TERM_MONTHS,
    [MAX_TERM_MONTHS] = @PRM_LOAN_PRODUCT_MAX_TERM_MONTHS,
    [INTEREST_RATE] = @PRM_LOAN_PRODUCT_INTEREST_RATE,
    [IS_ACTIVE] = @PRM_LOAN_PRODUCT_IS_ACTIVE
WHERE
    [ID] = @PRM_LOAN_PRODUCT_ID
    AND [IsDeleted] = 0;