SELECT LP.[ID], LP.[PAYMENT_REFERENCE], LP.[AMOUNT_PAID], LP.[PAYMENT_DATE] 
FROM [LOAN_PAYMENTS] LP 
WHERE LP.[IsDeleted] = 0 
	AND LP.[LOAN_ID] = @PRM_LOAN_PAYMENT_LOAN_ID 
ORDER BY LP.[PAYMENT_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 