SELECT LP.[ID], LP.[PAYMENT_REFERENCE], LP.[AMOUNT_PAID], LP.[PAYMENT_DATE] 
FROM [LOAN_PAYMENTS] LP 
WHERE LP.[IsDeleted] = 0 
	AND LP.[LOAN_ID] = @PRM_LOAN_PAYMENT_LOAN_ID 
	AND LP.[PAYMENT_DATE] BETWEEN @PRM_LOAN_PAYMENT_PAYMENT_DATE_From 
	AND @PRM_LOAN_PAYMENT_PAYMENT_DATE_To 
ORDER BY LP.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 