//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.CardType;
using System.Threading.Tasks;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Application.Interfaces.Repositories
{
    public partial interface ICardTypeRepository : IBaseRepository<CardTypeDto>
    {
        Task<RepoResponse<CardTypeDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool cardTypeIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByCodeResponseDto>> GetByCodeAsync(string cardTypeCode);
        Task<RepoResponse<int>> DeactivateAsync(int cardTypeId, DeactivateRequestDto updateRequest);
    }
}