SELECT TF.[ID], FT.[NAME] AS FEE_TYPE,
	TF.[FEE_AMOUNT], TF.[APPLIED_DATE] 
FROM [TRANSACTION_FEES] TF 
	INNER JOIN [FEE_TYPES] FT 
			ON TF.[FEE_TYPE_ID] = FT.[ID] 
WHERE TF.[IsDeleted] = 0 
	AND FT.[IsDeleted] = 0 
	AND TF.[TRANSACTION_ID] = @PRM_TRANSACTION_FEES_TRANSACTION_ID 
	AND TF.[FEE_TYPE_ID] = @PRM_TRANSACTION_FEES_FEE_TYPE_ID 
	AND FT.[ID] = @PRM_FEE_TYPES_ID 
ORDER BY TF.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 