SELECT TF.[ID], TF.[FEE_TYPE_ID], TF.[FEE_AMOUNT] 
FROM [TRANSACTION_FEES] TF 
WHERE TF.[IsDeleted] = 0 
	AND TF.[TRANSACTION_ID] = @PRM_TRANSACTION_FEE_TRANSACTION_ID 
ORDER BY TF.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 