INSERT INTO [dbo].[PENDING_TRANSFERS] (
    [TRANSFER_REFERENCE],
    [SOURCE_ACCOUNT_ID],
    [BENEFICIARY_ID],
    [AMOUNT],
    [SCHEDULED_DATE],
    [STATUS],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PENDING_TRANSFER_TRANSFER_REFERENCE,
    @PRM_PENDING_TRANSFER_SOURCE_ACCOUNT_ID,
    @PRM_PENDING_TRANSFER_BENEFICIARY_ID,
    @PRM_PENDING_TRANSFER_AMOUNT,
    @PRM_PENDING_TRANSFER_SCHEDULED_DATE,
    @PRM_PENDING_TRANSFER_STATUS,
    @PRM_PENDING_TRANSFER_CREATED_DATE
    );