UPDATE [dbo].[PENDING_TRANSFERS]
SET
    [TRANSFER_REFERENCE] = @PRM_PENDING_TRANSFER_TRANSFER_REFERENCE,
    [SOURCE_ACCOUNT_ID] = @PRM_PENDING_TRANSFER_SOURCE_ACCOUNT_ID,
    [BENEFICIARY_ID] = @PRM_PENDING_TRANSFER_BENEFICIARY_ID,
    [AMOUNT] = @PRM_PENDING_TRANSFER_AMOUNT,
    [SCHEDULED_DATE] = @PRM_PENDING_TRANSFER_SCHEDULED_DATE,
    [STATUS] = @PRM_PENDING_TRANSFER_STATUS,
    [CREATED_DATE] = @PRM_PENDING_TRANSFER_CREATED_DATE
WHERE
    [ID] = @PRM_PENDING_TRANSFER_ID
    AND [IsDeleted] = 0;