SELECT
    [ID],
    [TRANSFER_REFERENCE],
    [SOURCE_ACCOUNT_ID],
    [BENEFICIARY_ID],
    [AMOUNT],
    [SCHEDULED_DATE],
    [STATUS],
    [CREATED_DATE]
FROM [dbo].[PENDING_TRANSFERS]
WHERE
    [ID] = @PRM_PENDING_TRANSFER_ID
    AND [IsDeleted] = 0;