SELECT
    [ID],
    [TRANSFER_REFERENCE],
    [SOURCE_ACCOUNT_ID],
    [BENEFICIARY_ID],
    [AMOUNT],
    [SCHEDULED_DATE],
    [STATUS],
    [CREATED_DATE]
FROM [dbo].[PENDING_TRANSFERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;