//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.Card;
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.AccountManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories
{
    public partial class CardRepository : BaseRepository, ICardRepository
    {
        public async Task<RepoResponse<int>> ActivateCardAsync(int cardId, ActivateCardRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CardCrudSqlBindings.OperationNames.ActivateCard, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Card.Command.ActivateCard);
                var parameters = new
                {
                    PRM_CARD_ID = cardId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> BlockCardAsync(int cardId, BlockCardRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CardCrudSqlBindings.OperationNames.BlockCard, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Card.Command.BlockCard);
                var parameters = new
                {
                    PRM_CARD_ID = cardId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> ReportLostOrStolenAsync(int cardId, ReportLostOrStolenRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CardCrudSqlBindings.OperationNames.ReportLostOrStolen, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Card.Command.ReportLostOrStolen);
                var parameters = new
                {
                    PRM_CARD_ID = cardId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}