SELECT A.[ID], A.[ACCOUNT_NUMBER], AT.[NAME] AS ACCOUNT_TYPE,
	C.[CODE] AS CURRENCY,
	A.[BALANCE], A.[STATUS] 
FROM [ACCOUNTS] A 
	INNER JOIN [ACCOUNT_TYPES] AT 
			ON A.[ACCOUNT_TYPE_ID] = AT.[ID] 
	INNER JOIN [CURRENCIES] C 
			ON A.[CURRENCY_ID] = C.[ID] 
WHERE A.[IsDeleted] = 0 
	AND AT.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND A.[CUSTOMER_ID] = @PRM_ACCOUNTS_CUSTOMER_ID 
	AND A.[ACCOUNT_TYPE_ID] = @PRM_ACCOUNTS_ACCOUNT_TYPE_ID 
	AND AT.[ID] = @PRM_ACCOUNT_TYPES_ID 
	AND A.[CURRENCY_ID] = @PRM_ACCOUNTS_CURRENCY_ID 
	AND C.[ID] = @PRM_CURRENCIES_ID 
ORDER BY A.[ID], C.[CODE] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 