SELECT A.[ID], A.[ACCOUNT_NUMBER], A.[ACCOUNT_TYPE_ID], A.[BALANCE], A.[STATUS] 
FROM [ACCOUNTS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[CUSTOMER_ID] = @PRM_ACCOUNT_CUSTOMER_ID 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 