SELECT A.[ID], A.[ACCOUNT_NUMBER], A.[CUSTOMER_ID], A.[BALANCE] 
FROM [ACCOUNTS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[BALANCE] < '100' 
	AND A.[STATUS] = @PRM_ACCOUNT_STATUS 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 