//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.Customer;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories
{
    public partial class CustomerRepository : BaseRepository, ICustomerRepository
    {
        public async Task<RepoResponse<GetByCustomerNumberResponseDto>> GetByCustomerNumberAsync(Guid customerCustomerNumber)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.GetByCustomerNumber, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetByCustomerNumber);
                var parameters = new
                {
                    PRM_CUSTOMER_CUSTOMER_NUMBER = customerCustomerNumber
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetByCustomerNumberResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string customerLastName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.SearchByName, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Customer.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CUSTOMER_LAST_NAME = customerLastName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Customer");
                }
            });
        }

        public async Task<RepoResponse<List<GetActiveCustomersResponseDto>>> GetActiveCustomersAsync(CustomerStatus customerStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.GetActiveCustomers, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveCustomersResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetActiveCustomers);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CUSTOMER_STATUS = customerStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveCustomersResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Customer");
                }
            });
        }

        public async Task<RepoResponse<List<GetCustomersByTypeResponseDto>>> GetCustomersByTypeAsync(int customersCustomerTypeId, int customerTypesId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.GetCustomersByType, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetCustomersByTypeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomersByType);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CUSTOMERS_CUSTOMER_TYPE_ID = customersCustomerTypeId,
                        PRM_CUSTOMER_TYPES_ID = customerTypesId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetCustomersByTypeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Customer");
                }
            });
        }

        public async Task<RepoResponse<List<GetRecentlyJoinedResponseDto>>> GetRecentlyJoinedAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.GetRecentlyJoined, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetRecentlyJoinedResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetRecentlyJoined);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetRecentlyJoinedResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Customer");
                }
            });
        }

        public async Task<RepoResponse<long>> GetActiveCountByTypeAsync(int customersCustomerTypeId, CustomerStatus customersStatus, int customerTypesId)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.GetActiveCountByType, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetActiveCountByType);
                var parameters = new
                {
                    PRM_CUSTOMERS_CUSTOMER_TYPE_ID = customersCustomerTypeId,
                    PRM_CUSTOMER_TYPES_ID = customerTypesId,
                    PRM_CUSTOMERS_STATUS = customersStatus
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result);
            });
        }
    }
}