//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.Customer;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories;
internal static class CustomerCrudSqlBindings
{
    public const string StoreTableName = "CUSTOMERS";
    public const string ParameterNamePrefix = "CUSTOMER";
    public const string IdParameterName = "PRM_CUSTOMER_ID";
    public static class OperationNames
    {
        public const string ActivateCustomer = "ActivateCustomer";
        public const string CloseCustomer = "CloseCustomer";
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetActiveCountByType = "GetActiveCountByType";
        public const string GetActiveCustomers = "GetActiveCustomers";
        public const string GetByCustomerNumber = "GetByCustomerNumber";
        public const string GetByPk = "GetByPk";
        public const string GetCustomersByType = "GetCustomersByType";
        public const string GetRecentlyJoined = "GetRecentlyJoined";
        public const string Insert = "Insert";
        public const string SearchByName = "SearchByName";
        public const string Select = "Select";
        public const string SuspendCustomer = "SuspendCustomer";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CUSTOMER_NUMBER", nameof(CustomerDto.CustomerNumber)),
        ("FIRST_NAME", nameof(CustomerDto.FirstName)),
        ("LAST_NAME", nameof(CustomerDto.LastName)),
        ("DATE_OF_BIRTH", nameof(CustomerDto.DateOfBirth)),
        ("CUSTOMER_TYPE_ID", nameof(CustomerDto.CustomerTypeId)),
        ("STATUS", nameof(CustomerDto.Status)),
        ("CREATED_DATE", nameof(CustomerDto.CreatedDate)),
        ("IS_ACTIVE", nameof(CustomerDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CUSTOMER_NUMBER", nameof(CustomerDto.CustomerNumber)),
        ("FIRST_NAME", nameof(CustomerDto.FirstName)),
        ("LAST_NAME", nameof(CustomerDto.LastName)),
        ("DATE_OF_BIRTH", nameof(CustomerDto.DateOfBirth)),
        ("CUSTOMER_TYPE_ID", nameof(CustomerDto.CustomerTypeId)),
        ("STATUS", nameof(CustomerDto.Status)),
        ("CREATED_DATE", nameof(CustomerDto.CreatedDate)),
        ("IS_ACTIVE", nameof(CustomerDto.IsActive)),
        ("ID", nameof(CustomerDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CustomerDto.Id))
    };
}