//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoUzeyir.Common.Models;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.DemoUzeyir.Common;
using QuickCode.DemoUzeyir.Common.Extensions;
using QuickCode.DemoUzeyir.Common.Helpers;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Dtos.Customer;
using QuickCode.DemoUzeyir.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoUzeyir.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoUzeyir.CustomerManagementModule.Persistence.Repositories
{
    public partial class CustomerRepository : BaseRepository, ICustomerRepository
    {
        public async Task<RepoResponse<int>> ActivateCustomerAsync(int customerId, ActivateCustomerRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.ActivateCustomer, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.ActivateCustomer);
                var parameters = new
                {
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> SuspendCustomerAsync(int customerId, SuspendCustomerRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.SuspendCustomer, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.SuspendCustomer);
                var parameters = new
                {
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> CloseCustomerAsync(int customerId, CloseCustomerRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(CustomerCrudSqlBindings.OperationNames.CloseCustomer, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Command.CloseCustomer);
                var parameters = new
                {
                    PRM_CUSTOMER_ID = customerId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}