IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PENDING_TRANSFERS_BENEFICIARIES_BENEFICIARY_ID' AND parent_object_id = OBJECT_ID(N'dbo.PENDING_TRANSFERS'))
BEGIN
    ALTER TABLE [dbo].[PENDING_TRANSFERS] ADD CONSTRAINT [FK_PENDING_TRANSFERS_BENEFICIARIES_BENEFICIARY_ID] FOREIGN KEY ([BENEFICIARY_ID]) REFERENCES [dbo].[BENEFICIARIES] ([ID]);
END