IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTIONS_TRANSACTION_TYPES_TRANSACTION_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTIONS'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTIONS] ADD CONSTRAINT [FK_TRANSACTIONS_TRANSACTION_TYPES_TRANSACTION_TYPE_ID] FOREIGN KEY ([TRANSACTION_TYPE_ID]) REFERENCES [dbo].[TRANSACTION_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTIONS_TRANSACTION_CHANNELS_TRANSACTION_CHANNEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTIONS'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTIONS] ADD CONSTRAINT [FK_TRANSACTIONS_TRANSACTION_CHANNELS_TRANSACTION_CHANNEL_ID] FOREIGN KEY ([TRANSACTION_CHANNEL_ID]) REFERENCES [dbo].[TRANSACTION_CHANNELS] ([ID]);
END