IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTION_FEES_TRANSACTIONS_TRANSACTION_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTION_FEES'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_FEES] ADD CONSTRAINT [FK_TRANSACTION_FEES_TRANSACTIONS_TRANSACTION_ID] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[TRANSACTIONS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTION_FEES_FEE_TYPES_FEE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTION_FEES'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_FEES] ADD CONSTRAINT [FK_TRANSACTION_FEES_FEE_TYPES_FEE_TYPE_ID] FOREIGN KEY ([FEE_TYPE_ID]) REFERENCES [dbo].[FEE_TYPES] ([ID]);
END