IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PENDING_TRANSFERS_BENEFICIARIES_BENEFICIARY_ID' AND parent_object_id = OBJECT_ID(N'dbo.PENDING_TRANSFERS'))
BEGIN
    ALTER TABLE [dbo].[PENDING_TRANSFERS] ADD CONSTRAINT [FK_PENDING_TRANSFERS_BENEFICIARIES_BENEFICIARY_ID] FOREIGN KEY ([BENEFICIARY_ID]) REFERENCES [dbo].[BENEFICIARIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTIONS_TRANSACTION_TYPES_TRANSACTION_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTIONS'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTIONS] ADD CONSTRAINT [FK_TRANSACTIONS_TRANSACTION_TYPES_TRANSACTION_TYPE_ID] FOREIGN KEY ([TRANSACTION_TYPE_ID]) REFERENCES [dbo].[TRANSACTION_TYPES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTIONS_TRANSACTION_CHANNELS_TRANSACTION_CHANNEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTIONS'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTIONS] ADD CONSTRAINT [FK_TRANSACTIONS_TRANSACTION_CHANNELS_TRANSACTION_CHANNEL_ID] FOREIGN KEY ([TRANSACTION_CHANNEL_ID]) REFERENCES [dbo].[TRANSACTION_CHANNELS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTION_FEES_TRANSACTIONS_TRANSACTION_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTION_FEES'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_FEES] ADD CONSTRAINT [FK_TRANSACTION_FEES_TRANSACTIONS_TRANSACTION_ID] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[TRANSACTIONS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TRANSACTION_FEES_FEE_TYPES_FEE_TYPE_ID' AND parent_object_id = OBJECT_ID(N'dbo.TRANSACTION_FEES'))
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_FEES] ADD CONSTRAINT [FK_TRANSACTION_FEES_FEE_TYPES_FEE_TYPE_ID] FOREIGN KEY ([FEE_TYPE_ID]) REFERENCES [dbo].[FEE_TYPES] ([ID]);
END