//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.DemoUzeyir.AccountManagementModule.Application.Dtos.CardType;

namespace QuickCode.DemoUzeyir.AccountManagementModule.Persistence.Repositories;
internal static class CardTypeCrudSqlBindings
{
    public const string StoreTableName = "CARD_TYPES";
    public const string ParameterNamePrefix = "CARD_TYPE";
    public const string IdParameterName = "PRM_CARD_TYPE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByCode = "GetByCode";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CODE", nameof(CardTypeDto.Code)),
        ("NAME", nameof(CardTypeDto.Name)),
        ("NETWORK", nameof(CardTypeDto.Network)),
        ("IS_ACTIVE", nameof(CardTypeDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CODE", nameof(CardTypeDto.Code)),
        ("NAME", nameof(CardTypeDto.Name)),
        ("NETWORK", nameof(CardTypeDto.Network)),
        ("IS_ACTIVE", nameof(CardTypeDto.IsActive)),
        ("ID", nameof(CardTypeDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CardTypeDto.Id))
    };
}